/*
 blade/func Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/object Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/jig Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/array Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/url Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
*/
define("blade/fn",[],function(){var b=Array.prototype.slice,d=Object.prototype.toString;return{is:function(e){return d.call(e)==="[object Function]"},bind:function(e,c){if(!c)return e;if(typeof c==="string")c=e[c];var a=b.call(arguments,2);return function(){return c.apply(e,a.concat(b.call(arguments,0)))}}}});
define("blade/object",["./fn"],function(b){function d(){}var e={},c=function(a,f,g){a=a||{};var h,j=c.create(a.prototype,f);a=function(i,m,n){return j[m].apply(i,n)};f=c.create(j);c.mixin(f,b.is(g)?g(a):g,true);h=function(){if(!(this instanceof h))throw new Error('blade/object: constructor function called without "new" in front');this.init&&this.init.apply(this,arguments)};h.prototype=f;return h};c.create=function(a,f){d.prototype=a;a=new d;var g,h;d.prototype=null;if(f)for(g=0;h=f[g];g++)c.mixin(a,
h);return a};c.mixin=function(a,f,g){for(var h in f)if(!(h in e)&&(!(h in a)||g))a[h]=f[h]};return c});
define("blade/jig",["require","./object"],function(b,d){function e(k){return B.call(k)==="[object Array]"}function c(k,l,o){l=l;var p,u;for(p=0;l&&(u=k[p]);p++)l=typeof l==="object"&&u in l?l[u]:o&&p===0&&u in o?o[u]:undefined;return l}function a(k){return k?parseInt(k,10):0}function f(k,l,o){var p=/\[([\w0-9\.'":]+)\]/,u=k,r=l,w=true,E,F;if(k===A)return l;if(x.test(k))return a(k);if(k==="")return"";E=k.charAt(0);if(E==="'"||E==="'")return k.substring(1,k.length-1);if((E=k.indexOf("("))!==-1){p=k.lastIndexOf(")");
w=k.substring(0,E);u=o.fn[w];if(!u){n.error("Cannot find function named: "+w+" for "+k);return""}w=k.substring(E+1,p);if(w.indexOf(",")!==-1){w=w.split(",");for(r=w.length-1;r>=0;r--)w[r]=f(w[r],l,o);u=u.apply(null,w)}else u=u(f(w,l,o));if(p<k.length-1){if(k.charAt(p+1)===".")p+=1;return f(k.substring(p+1,k.length),u,o)}else return u}for(;E=p.exec(u);){l=E[1].replace(/['"]/g,"");F=u.substring(0,E.index);u=u.substring(E.index+E[0].length,u.length);if(u.indexOf(".")===0)u=u.substring(1,u.length);r=
c(F.split("."),r,w?o.context:null);w=false;if(!r&&l){n.error('blade/jig: No property "'+l+'" on '+r);return""}if(l.indexOf(":")!==-1){E=l.split(":");l=a(E[0]);r=(E=a(E[1]))?r.slice(l,E):r.slice(l)}else{o.strict&&!(l in r)&&n.error('blade/jig: no property "'+l+'"');r=r[l]}r=r}u=u?c(u.split("."),r,w?o.context:null):r;o.strict&&u===undefined&&n.error('blade/jig: undefined value for property "'+k+'"');return u}function g(k,l){l=l||{};var o=n.cache(k,l);if(o===undefined&&typeof document!=="undefined"){(o=
document.getElementById(k))&&n.parse([o],l);o=n.cache(k,l)}if(o===undefined)throw new Error("blade/jig: no template or node with ID: "+k);return o}function h(k,l){for(var o=[],p=0,u=false,r=0,w,E,F,R,S,P;(w=k.indexOf(l.startToken,p))!==-1;){w!==p&&o.push(k.substring(p,w));p=k.substring(w);if(E=l.endRegExp.exec(p)){p=w+E[0].length;F=k.substring(w+l.startToken.length,w+E[0].length-l.endToken.length).trim();F=C(F);if(D.test(F))throw new Error("blade/jig: end block tags should not be commented: "+F);
w=F.charAt(0);if(w==="]"&&r){u=F.substring(1).trim();if(u==="[")w=">";else{w=u.charAt(0);F=u}}if(w&&!l.propertyRegExp.test(w))F=F.substring(1).trim();else w="_default_";if(u=F.indexOf(l.rawHtmlToken)===0)F=F.substring(l.rawHtmlToken.length,F.length);if(w===K)u=true;F=F.split(l.argSeparator);R=F[F.length-1];S=R.charAt(R.length-1);P=null;if(w==="]"){if(S!=="["){o.templateEnd=p;o.endControl=true}else o.templateEnd=p-E[0].length;return o}else if(S==="["){r||(r=U++);F[F.length-1]=R.substring(0,R.length-
1);P=h(k.substring(p),l);p+=P.templateEnd}if(w==="+")l.templates[F[0]]=P;else if(w!=="/"){if(F.length>1)for(E=F.length-1;E>=0;E--)if(F[E].charAt(F[E].length-1)===","){F[E]+=F[E+1];F.splice(E+1,1)}o.push({action:l.commands[w].action,useRawHtml:u,args:F,controlId:r,children:P})}if(P&&P.endControl)r=0}else{o.push(p);return o}}p!==k.length-1&&o.push(k.substring(p,k.length));return o}function j(k,l){var o,p=k.id;o=l.templates||J;if(o[p])return o[p];l.onBeforeParse&&l.onBeforeParse(k);if(k.nodeName.toUpperCase()===
"SCRIPT"){o=k.text.trim();k.parentNode&&k.parentNode.removeChild(k)}else{V.appendChild(k);k.removeAttribute("id");(o=(k.getAttribute("class")||"").trim())&&k.setAttribute("class",o.replace(Z,"$1$3"));o=V.innerHTML.replace(/%7B/g,"{").replace(/%7D/g,"}");V.removeChild(k)}k=n.compile(o,l);n.cache(p,k,l);return k}function i(k,l,o){var p="",u,r,w,E,F;if(typeof k==="string")p=k;else if(e(k))for(u=0;u<k.length;u++){w=k[u].controlId;if(!w||w!==r||!F){E=i(k[u],l,o);p+=E;if(w){r=w;F=E}}}else if(p=k.action(k.args,
l,o,k.children,i)){if(!k.useRawHtml&&!k.children)p=n.htmlEscape(p.toString())}else p="";if(o.attachData)if(y.test(p)){k="id"+aa++;p=p.replace(y,'$& data-blade-jig="'+k+'" ');W[k]=l}return p}function m(k){k.fn.jig=function(l,o){o=o||{};var p=this.selector;if(p.charAt(0)!=="#")throw new Error('blade/jig: only ID selectors, like "#something" are allowed with jig()');p=p.substring(1,p.length);(p=(o.templates||J)[p])||(p=j(this[0]));return k(n.render(p,l,o))}}var n,v,B=Object.prototype.toString,C=typeof decodeURIComponent===
"undefined"?function(){}:decodeURIComponent,K="#",z=/[_\[\^\w]/,A="_",y=/<\s*\w+/,x=/^\d+$/,D=/\/(\/)?\s*\]/,J={},O={openCurly:function(){return"{"},closeCurly:function(){return"}"},eq:function(k,l){return k===l},gt:function(k,l){return k>l},gte:function(k,l){return k>=l},lt:function(k,l){return k<l},lte:function(k,l){return k<=l},or:function(k,l){return k||l},and:function(k,l){return k&&l},is:function(k){return!!k},eachProp:function(k){var l,o=[];for(l in k)k.hasOwnProperty(l)&&o.push({prop:l,value:k[l]});
return o.sort(function(p,u){return p.prop>u.prop?1:-1})}},aa=1,U=1,W={},V=typeof document!=="undefined"&&document.createElement?document.createElement("div"):null,Z=/(\s*)(template)(\s*)/;v={_default_:{doc:"Property reference",action:function(k,l,o,p,u){var r=k[0]?f(k[0],l,o):l,w=k[1]?f(k[1],l,o):undefined,E="";if(k[1]){w=r===w;r=l}else w=r;if(w===false||w===null||w===undefined||e(w)&&!w.length)return"";else if(p)if(e(r))for(k=0;k<r.length;k++)E+=u(p,r[k],o);else{if(typeof r==="boolean")r=l;E=u(p,
r,o)}else E=r;return E}},"!":{doc:"Not",action:function(k,l,o,p,u){var r=f(k[0],l,o),w=k[1]?f(k[1],l,o):undefined;w=k[1]?r===w:r;if(p&&!w)return u(p,l,o);return""}},"#":{doc:"Template reference",action:function(k,l,o,p,u){p=g(k[0],o);l=f(k.length>1?k[1]:A,l,o);return u(p,l,o)}},".":{doc:"Variable declaration",action:function(k,l,o){o.context[k[0]]=f(k[1],l,o);return""}},">":{doc:"Else",action:function(k,l,o,p,u){if(p)return u(p,l,o);return""}}};n=function(k,l,o){if(typeof k==="string")if(k.charAt(0)===
"#"){k=k.substring(1,k.length);k=g(k,o)}else k=n.compile(k,o);return n.render(k,l,o)};n.htmlEscape=function(k){return k.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};n.compile=function(k,l){l=l||{};d.mixin(l,{startToken:"{",endToken:"}",rawHtmlToken:"^",propertyRegExp:z,commands:v,argSeparator:" ",templates:J});l.endRegExp=/[^\r\n]*?}/;U=1;return h(k,l)};n.parse=function(k,l){if(k&&!k.length){l=k;k=null}l=l||{};k=k||document.querySelectorAll('.template, script[type="text/template"]');
var o,p;for(p=k.length-1;p>-1&&(o=k[p]);p--)j(o,l)};n.render=function(k,l,o){var p,u="";o=o||{};d.mixin(o,{templates:J,attachData:false,strict:n.strict});if(o.fn)d.mixin(o.fn,O);else o.fn=O;o.context=o.context||d.create(l);if(e(l)){for(p=0;p<l.length;p++)u+=i(k,l[p],o);return u}return i(k,l,o)};n.strict=false;n.error=function(k){throw k;};n.addFn=function(k){d.mixin(O,k,true)};n.data=function(k,l){if(typeof k!=="string"){k.nodeType||(k=k[0]);k=k.getAttribute("data-blade-jig")}return l!==undefined?
(W[k]=l):W[k]};n.removeData=function(k){delete W[k]};n.getObject=f;n.cache=function(k,l,o){if(typeof l==="string")l=n.compile(l,o);if(!e(l)){o=l;l=undefined}o=o&&o.templates||J;if(l!==undefined)o[k]=l;return o[k]||J[k]};typeof jQuery!=="undefined"&&m(jQuery);return n});
define("friendly",["require","exports","module"],function(){var b={timestamp:function(d){return b.date(new Date(d*1E3))},date:function(d){var e=((new Date).getTime()-d.getTime())/1E3,c=Math.floor(e/86400),a={friendly:d.toLocaleDateString(),additional:d.toLocaleTimeString(),utc:d.toUTCString(),locale:d.toLocaleString()};if(c<0){a.friendly="in the future";return a}else if(isNaN(c)){a.friendly=a.additional="unknown";return a}if(c===0){if(e<60){a.friendly="just now";return a}if(e<150){a.friendly="a minute ago";
return a}if(e<3600){a.friendly=Math.floor(e/60)+" minutes ago";return a}if(e<7200){a.friendly="1 hour ago";return a}if(e<86400){a.friendly=Math.floor(e/3600)+" hours ago";return a}}if(c===1){a.friendly="yesterday";return a}if(c<7){a.friendly=c+" days ago";return a}if(c<8){a.friendly="last week";return a}if(c<31){a.friendly=Math.ceil(c/7)+" weeks ago";return a}if(c<62){a.friendly="a month ago";return a}if(c<365){a.friendly=Math.ceil(c/31)+" months ago";return a}if(c>=365&&c<730){a.additional=d.toLocaleDateString();
a.friendly="a year ago";return a}if(c>=365){a.additional=d.toLocaleDateString();a.friendly=Math.ceil(c/365)+" years ago";return a}return a},name:function(d){d=d.split(" ")[0];if(d.indexOf("@")!==-1)d=d.split("@")[0];d=d.replace(" ","");d=d.replace("'","");return d=d.replace('"',"")}};return b});
define("isoDate",[],function(){var b=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+\-](\d{2}):(\d{2}))|Z)?)?$/,d=function(e,c){var a=b.exec(e);e=null;var f,g;if(a){a.shift();a[1]&&a[1]--;if(a[6])a[6]*=1E3;if(c){c=new Date(c);["FullYear","Month","Date","Hours","Minutes","Seconds","Milliseconds"].map(function(h){return c["get"+h]()}).forEach(function(h,j){a[j]=a[j]||h})}e=new Date(a[0]||1970,a[1]||0,a[2]||1,a[3]||0,a[4]||0,a[5]||0,a[6]||0);if(a[0]<100)e.setFullYear(a[0]||
1970);f=0;g=a[7]&&a[7].charAt(0);if(g!=="Z"){f=(a[8]||0)*60+(Number(a[9])||0);if(g!=="-")f*=-1}if(g)f-=e.getTimezoneOffset();f&&e.setTime(e.getTime()+f*6E4)}return e};d.toIsoString=function(e,c){var a=function(j){return j<10?"0"+j:j},f,g,h;c=c||{};f=[];g=c.zulu?"getUTC":"get";h="";if(c.selector!=="time"){h=e[g+"FullYear"]();h=["0000".substr((h+"").length)+h,a(e[g+"Month"]()+1),a(e[g+"Date"]())].join("-")}f.push(h);if(c.selector!=="date"){h=[a(e[g+"Hours"]()),a(e[g+"Minutes"]()),a(e[g+"Seconds"]())].join(":");
g=e[g+"Milliseconds"]();if(c.milliseconds)h+="."+(g<100?"0":"")+a(g);if(c.zulu)h+="Z";else if(c.selector!=="time"){e=e.getTimezoneOffset();c=Math.abs(e);h+=(e>0?"-":"+")+a(Math.floor(c/60))+":"+a(c%60)}f.push(h)}return f.join("T")};return d});var EXPORTED_SYMBOLS=["hex_md5"],hexcase=0,b64pad="";function hex_md5(b){return rstr2hex(rstr_md5(str2rstr_utf8(b)))}function b64_md5(b){return rstr2b64(rstr_md5(str2rstr_utf8(b)))}function any_md5(b,d){return rstr2any(rstr_md5(str2rstr_utf8(b)),d)}
function hex_hmac_md5(b,d){return rstr2hex(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)))}function b64_hmac_md5(b,d){return rstr2b64(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)))}function any_hmac_md5(b,d,e){return rstr2any(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)),e)}function md5_vm_test(){return hex_md5("abc").toLowerCase()=="900150983cd24fb0d6963f7d28e17f72"}function rstr_md5(b){return binl2rstr(binl_md5(rstr2binl(b),b.length*8))}
function rstr_hmac_md5(b,d){var e=rstr2binl(b);if(e.length>16)e=binl_md5(e,b.length*8);var c=Array(16);b=Array(16);for(var a=0;a<16;a++){c[a]=e[a]^909522486;b[a]=e[a]^1549556828}d=binl_md5(c.concat(rstr2binl(d)),512+d.length*8);return binl2rstr(binl_md5(b.concat(d),640))}function rstr2hex(b){for(var d=hexcase?"0123456789ABCDEF":"0123456789abcdef",e="",c,a=0;a<b.length;a++){c=b.charCodeAt(a);e+=d.charAt(c>>>4&15)+d.charAt(c&15)}return e}
function rstr2b64(b){for(var d="",e=b.length,c=0;c<e;c+=3)for(var a=b.charCodeAt(c)<<16|(c+1<e?b.charCodeAt(c+1)<<8:0)|(c+2<e?b.charCodeAt(c+2):0),f=0;f<4;f++)d+=c*8+f*6>b.length*8?b64pad:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>6*(3-f)&63);return d}
function rstr2any(b,d){var e=d.length,c,a,f,g,h,j=Array(Math.ceil(b.length/2));for(c=0;c<j.length;c++)j[c]=b.charCodeAt(c*2)<<8|b.charCodeAt(c*2+1);var i=Math.ceil(b.length*8/(Math.log(d.length)/Math.log(2)));b=Array(i);for(a=0;a<i;a++){h=Array();for(c=g=0;c<j.length;c++){g=(g<<16)+j[c];f=Math.floor(g/e);g-=f*e;if(h.length>0||f>0)h[h.length]=f}b[a]=g;j=h}e="";for(c=b.length-1;c>=0;c--)e+=d.charAt(b[c]);return e}
function str2rstr_utf8(b){for(var d="",e=-1,c,a;++e<b.length;){c=b.charCodeAt(e);a=e+1<b.length?b.charCodeAt(e+1):0;if(55296<=c&&c<=56319&&56320<=a&&a<=57343){c=65536+((c&1023)<<10)+(a&1023);e++}if(c<=127)d+=String.fromCharCode(c);else if(c<=2047)d+=String.fromCharCode(192|c>>>6&31,128|c&63);else if(c<=65535)d+=String.fromCharCode(224|c>>>12&15,128|c>>>6&63,128|c&63);else if(c<=2097151)d+=String.fromCharCode(240|c>>>18&7,128|c>>>12&63,128|c>>>6&63,128|c&63)}return d}
function str2rstr_utf16le(b){for(var d="",e=0;e<b.length;e++)d+=String.fromCharCode(b.charCodeAt(e)&255,b.charCodeAt(e)>>>8&255);return d}function str2rstr_utf16be(b){for(var d="",e=0;e<b.length;e++)d+=String.fromCharCode(b.charCodeAt(e)>>>8&255,b.charCodeAt(e)&255);return d}function rstr2binl(b){for(var d=Array(b.length>>2),e=0;e<d.length;e++)d[e]=0;for(e=0;e<b.length*8;e+=8)d[e>>5]|=(b.charCodeAt(e/8)&255)<<e%32;return d}
function binl2rstr(b){for(var d="",e=0;e<b.length*32;e+=8)d+=String.fromCharCode(b[e>>5]>>>e%32&255);return d}
function binl_md5(b,d){b[d>>5]|=128<<d%32;b[(d+64>>>9<<4)+14]=d;d=1732584193;for(var e=-271733879,c=-1732584194,a=271733878,f=0;f<b.length;f+=16){var g=d,h=e,j=c,i=a;d=md5_ff(d,e,c,a,b[f+0],7,-680876936);a=md5_ff(a,d,e,c,b[f+1],12,-389564586);c=md5_ff(c,a,d,e,b[f+2],17,606105819);e=md5_ff(e,c,a,d,b[f+3],22,-1044525330);d=md5_ff(d,e,c,a,b[f+4],7,-176418897);a=md5_ff(a,d,e,c,b[f+5],12,1200080426);c=md5_ff(c,a,d,e,b[f+6],17,-1473231341);e=md5_ff(e,c,a,d,b[f+7],22,-45705983);d=md5_ff(d,e,c,a,b[f+8],7,
1770035416);a=md5_ff(a,d,e,c,b[f+9],12,-1958414417);c=md5_ff(c,a,d,e,b[f+10],17,-42063);e=md5_ff(e,c,a,d,b[f+11],22,-1990404162);d=md5_ff(d,e,c,a,b[f+12],7,1804603682);a=md5_ff(a,d,e,c,b[f+13],12,-40341101);c=md5_ff(c,a,d,e,b[f+14],17,-1502002290);e=md5_ff(e,c,a,d,b[f+15],22,1236535329);d=md5_gg(d,e,c,a,b[f+1],5,-165796510);a=md5_gg(a,d,e,c,b[f+6],9,-1069501632);c=md5_gg(c,a,d,e,b[f+11],14,643717713);e=md5_gg(e,c,a,d,b[f+0],20,-373897302);d=md5_gg(d,e,c,a,b[f+5],5,-701558691);a=md5_gg(a,d,e,c,b[f+
10],9,38016083);c=md5_gg(c,a,d,e,b[f+15],14,-660478335);e=md5_gg(e,c,a,d,b[f+4],20,-405537848);d=md5_gg(d,e,c,a,b[f+9],5,568446438);a=md5_gg(a,d,e,c,b[f+14],9,-1019803690);c=md5_gg(c,a,d,e,b[f+3],14,-187363961);e=md5_gg(e,c,a,d,b[f+8],20,1163531501);d=md5_gg(d,e,c,a,b[f+13],5,-1444681467);a=md5_gg(a,d,e,c,b[f+2],9,-51403784);c=md5_gg(c,a,d,e,b[f+7],14,1735328473);e=md5_gg(e,c,a,d,b[f+12],20,-1926607734);d=md5_hh(d,e,c,a,b[f+5],4,-378558);a=md5_hh(a,d,e,c,b[f+8],11,-2022574463);c=md5_hh(c,a,d,e,b[f+
11],16,1839030562);e=md5_hh(e,c,a,d,b[f+14],23,-35309556);d=md5_hh(d,e,c,a,b[f+1],4,-1530992060);a=md5_hh(a,d,e,c,b[f+4],11,1272893353);c=md5_hh(c,a,d,e,b[f+7],16,-155497632);e=md5_hh(e,c,a,d,b[f+10],23,-1094730640);d=md5_hh(d,e,c,a,b[f+13],4,681279174);a=md5_hh(a,d,e,c,b[f+0],11,-358537222);c=md5_hh(c,a,d,e,b[f+3],16,-722521979);e=md5_hh(e,c,a,d,b[f+6],23,76029189);d=md5_hh(d,e,c,a,b[f+9],4,-640364487);a=md5_hh(a,d,e,c,b[f+12],11,-421815835);c=md5_hh(c,a,d,e,b[f+15],16,530742520);e=md5_hh(e,c,a,
d,b[f+2],23,-995338651);d=md5_ii(d,e,c,a,b[f+0],6,-198630844);a=md5_ii(a,d,e,c,b[f+7],10,1126891415);c=md5_ii(c,a,d,e,b[f+14],15,-1416354905);e=md5_ii(e,c,a,d,b[f+5],21,-57434055);d=md5_ii(d,e,c,a,b[f+12],6,1700485571);a=md5_ii(a,d,e,c,b[f+3],10,-1894986606);c=md5_ii(c,a,d,e,b[f+10],15,-1051523);e=md5_ii(e,c,a,d,b[f+1],21,-2054922799);d=md5_ii(d,e,c,a,b[f+8],6,1873313359);a=md5_ii(a,d,e,c,b[f+15],10,-30611744);c=md5_ii(c,a,d,e,b[f+6],15,-1560198380);e=md5_ii(e,c,a,d,b[f+13],21,1309151649);d=md5_ii(d,
e,c,a,b[f+4],6,-145523070);a=md5_ii(a,d,e,c,b[f+11],10,-1120210379);c=md5_ii(c,a,d,e,b[f+2],15,718787259);e=md5_ii(e,c,a,d,b[f+9],21,-343485551);d=safe_add(d,g);e=safe_add(e,h);c=safe_add(c,j);a=safe_add(a,i)}return Array(d,e,c,a)}function md5_cmn(b,d,e,c,a,f){return safe_add(bit_rol(safe_add(safe_add(d,b),safe_add(c,f)),a),e)}function md5_ff(b,d,e,c,a,f,g){return md5_cmn(d&e|~d&c,b,d,a,f,g)}function md5_gg(b,d,e,c,a,f,g){return md5_cmn(d&c|e&~c,b,d,a,f,g)}
function md5_hh(b,d,e,c,a,f,g){return md5_cmn(d^e^c,b,d,a,f,g)}function md5_ii(b,d,e,c,a,f,g){return md5_cmn(e^(d|~c),b,d,a,f,g)}function safe_add(b,d){var e=(b&65535)+(d&65535);return(b>>16)+(d>>16)+(e>>16)<<16|e&65535}function bit_rol(b,d){return b<<d|b>>>32-d}define("md5",function(){});
define("rdapi",["require","jquery","blade/object","blade/jig","friendly","isoDate","md5"],function(b,d,e,c,a,f){function g(z){if(typeof z==="string")z={template:z};else if(z.templateId)z.template=c.cache(z.templateId);if(!("attachData"in z))z.attachData=m.attachTemplateData;if(z.emptyTemplateId)z.emptyTemplate=c.cache(z.emptyTemplateId);return z}function h(){var z=v.exec(document.cookie);return z&&z[1]?z[1]:null}function j(z,A){A.url=K.baseUrl+K.apiPath+z;e.mixin(A,{limit:30,message_limit:3,dataType:"json",
error:function(D,J,O){throw O;}});var y=A.success,x=h();A.success=function(D){D&&D.contacts&&e.mixin(B,D.contacts,true);return y?y.apply(null,arguments):D};if(x)A.beforeSend=function(D){D.setRequestHeader(n,x)};d.ajax(A)}function i(z,A){var y=A.forId?document.getElementById(A.forId):null;if(y)y.innerHTML=z;A.onTemplateDone&&A.onTemplateDone(z);d(document).trigger("rdapi-done",y)}var m,n="X-CSRF",v=/csrf=([^\; ]+)/,B={},C={contact:function(z){return z.iid&&z.domain?B[z.iid]||{}:z},contactPhotoUrl:function(z){var A=
"i/face2.png",y,x;z=C.contact(z);if((y=z.photos)&&y.length){A=y[0].value;y.forEach(function(D){if(D.primary)A=D.value})}else if(z.emails&&z.emails.length){x=z.emails[0].value;z.emails.forEach(function(D){if(D.primary)x=D.value});A="http://www.gravatar.com/avatar/"+hex_md5(x)+"?s=24 &d=identicon"}return A},allMessages:function(z){return[z.topic].concat(z.messages||[])},friendlyDate:function(z){return a.date(f(z)).friendly},htmlBody:function(z){return c.htmlEscape(z).replace(/\n/g,"<br>")}},K={baseUrl:"/",
apiPath:"api/",saveTemplateData:true};c.addFn(C);m=function(z,A){A=g(A);e.mixin(A,{success:function(y){var x=A.template,D=A.emptyTemplate,J="";if(A.forId&&x){if(A.prop)y=c.getObject(A.prop,y,A);if(b.isArray(y))if(y.length)y.forEach(function(O){J+=c(x,O,A)});else J+=c(D,y,A);else J+=c(!y?D:x,y,A);i(J,A)}},error:function(y,x,D){if(A.emptyTemplate){y=c(A.emptyTemplate,D,A);i(y,A)}else throw D;}});j(z,A)};m.contactPhotoUrl=C.contactPhotoUrl;m.attachTemplateData=false;b.ready(function(){var z=[];c.parse({onBeforeParse:function(A){var y=
A.id,x=A.getAttribute("data-rdapi"),D=A.getAttribute("data-rdfor"),J=A.getAttribute("data-rdprop");x&&z.push({templateId:y,api:x,forId:D,prop:J});["data-rdapi","data-rdprop","data-rdfor"].forEach(function(O){A.removeAttribute(O)})}});z.forEach(function(A){m(A.api,A)})});return m});define("storage",[],function(){function b(){return d}var d=localStorage,e="localStorage";try{d.tempVar="temp";delete d.tempVar}catch(c){d={};e="memory"}b.type=e;return b});
define("dispatch",["jquery"],function(){var b=location.protocol+"//"+location.host;return{sub:function(d,e,c,a){c=c||window;a=a||b;var f=function(g){if(g.origin===a||g.origin==="chrome://browser")try{var h=JSON.parse(g.data),j=h.topic;j&&j===d&&e(h.data)}catch(i){}};c.addEventListener("message",f,false);return f},unsub:function(d,e){e=e||window;e.removeEventListener("message",d,false)},pub:function(d,e,c){c=c||window;c.postMessage(JSON.stringify({topic:d,data:e}),b)}}});
define("blade/array",[],function(){var b=Object.prototype.toString,d=Array.prototype.slice;return{is:function(e){return b.call(e)==="[object Array]"},to:function(){return[].concat(d.call(arguments,0))}}});
define("TextCounter",["jquery","blade/object","blade/fn"],function(b,d,e){return d(null,null,{init:function(c,a,f){this.dom=b(c);this.domPlaceholderText=this.dom[0].getAttribute("placeholder")||"";this.countDom=b(a);this.limit=f;this.dom.bind("keyup",e.bind(this,"checkCount"));this.checkCount()},checkCount:function(){var c=this.dom[0].value;if(c.trim()===this.domPlaceholderText)c="";c=this.limit-c.length;c<0?this.countDom.addClass("TextCountOver"):this.countDom.removeClass("TextCountOver");this.countDom.text(c===
this.limit?"":c)},updateLimit:function(c){this.limit=c;this.checkCount()},isOver:function(){return this.dom[0].value.length>this.limit}})});
define("services",["rdapi","blade/object","blade/array","TextCounter"],function(b,d,e){function c(h,j){if(h){this.name=h;this.type=h.replace(/\s/g,"").toLowerCase();this.tabName=this.type+"Tab";this.icon="i/"+this.type+"Icon.png";this.autoCompleteWidget=null;this.acformat="{name}";this.features={counter:false,direct:false,subject:false};d.mixin(this,j,true)}}function a(){c.constructor.apply(this,arguments);this.features.direct=true;this.features.subject=true;this.acformat="{name} {email}"}var f,g;
c.constructor=c;c.prototype={clearCache:function(h){delete h[this.type+"Contacts"]},getContacts:function(h){if(h[this.type+"Contacts"]){var j=JSON.parse(h[this.type+"Contacts"]);if(!f.isFF36&&j&&e.is(j)){j=null;delete h[this.type+"Contacts"]}return j}return null},setContacts:function(h,j){h[this.type+"Contacts"]=JSON.stringify(j)},getFormattedContacts:function(h){var j={};h.forEach(function(i){i.accounts&&i.accounts.length&&i.accounts.forEach(function(m){j[i.displayName]={email:"",userid:m.userid,
username:m.username}})});return j},get36FormattedContacts:function(){return null}};a.prototype=new c;a.constructor=a;a.prototype.validate=function(h){if(!h.to||!h.to.trim())return false;return true};a.prototype.getFormattedContacts=function(h){var j={};h.forEach(function(i){i.emails&&i.emails.length&&i.emails.forEach(function(m){j[i.displayName?i.displayName:m.value]={email:m.value,userid:null,username:null}})});return j};a.prototype.get36FormattedContacts=function(h){var j=[];h.forEach(function(i){i.emails&&
i.emails.length&&i.emails.forEach(function(m){j.push({displayName:i.displayName?i.displayName:m.value,email:m.value})})});return j};f={domains:{"twitter.com":new c("Twitter",{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"public",name:"public"},{type:"direct",name:"direct message",showTo:true,toLabel:"type in name of recipient"}],acformat:"{username}",textLimit:140,shorten:true,serviceUrl:"http://twitter.com",revokeUrl:"http://twitter.com/settings/connections",signOutUrl:"http://twitter.com/logout",
accountLink:function(h){return"http://twitter.com/"+h.username}}),"facebook.com":new c("Facebook",{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"wall",name:"my wall"},{type:"groupWall",name:"group wall",showTo:true,toLabel:"type in the name of the group"}],textLimit:420,serviceUrl:"http://facebook.com",revokeUrl:"http://www.facebook.com/editapps.php?v=allowed",signOutUrl:"http://facebook.com",accountLink:function(h){return"http://www.facebook.com/profile.php?id="+h.userid}}),
"google.com":new a("Gmail",{shareTypes:[{type:"direct",name:"direct",showTo:true}],serviceUrl:"https://mail.google.com",revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(h){return"http://google.com/profiles/"+h.username}}),"googleapps.com":new a("Google Apps",{shareTypes:[{type:"direct",name:"direct",showTo:true}],icon:"i/gmailIcon.png",serviceUrl:"https://mail.google.com",revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",
signOutUrl:"http://google.com/preferences",accountLink:function(h){return"http://google.com/profiles/"+h.username}}),"yahoo.com":new a("Yahoo",{shareTypes:[{type:"direct",name:"direct",showTo:true}],name:"Yahoo!",serviceUrl:"http://mail.yahoo.com",revokeUrl:"https://api.login.yahoo.com/WSLogin/V1/unlink",signOutUrl:"https://login.yahoo.com/config/login?logout=1",accountLink:function(h){return"http://profiles.yahoo.com/"+h.username}}),"linkedin.com":new c("LinkedIn",{isNew:true,features:{direct:true,
subject:true,counter:false},shareTypes:[{type:"public",name:"anyone"},{type:"myConnections",name:"connections only",specialTo:"connections-only"},{type:"contact",name:"send message",showTo:true,toLabel:"type in the name of the contact"}],serviceUrl:"http://linkedin.com",revokeUrl:"http://linkedin.com/settings/connections",signOutUrl:"http://linkedin.com/logout",accountLink:function(h){return"http://linkedin.com/"+h.username},overlays:{"widgets/AccountPanel":"widgets/AccountPanelLinkedIn"}})},domainList:[],
svcBaseProto:c.prototype};for(g in f.domains)f.domains.hasOwnProperty(g)&&f.domainList.push(g);return f});
define("accounts",["storage","dispatch","rdapi","services"],function(b,d,e,c){function a(i,m,n,v){return i.domain===m&&(n&&i.userid===n||v&&i.username===v)}function f(i,m){return j.accounts(i,m)}function g(){location.reload()}var h=b(),j;j={localStorage:{accounts:function(i,m){var n=h.accountCache,v=h.serviceCache;n=n?JSON.parse(n):[];if(v){v=v?JSON.parse(v):[];i&&i(n,v)}else j.fetch(i,m)},update:function(i){var m=h.accountCache,n=h.serviceCache,v=false,B,C;m=m?JSON.parse(m):[];B=i.profile;for(C=
0;C<m.length;C++)if(m[C].providerName===B.providerName){m[C]=B;v=true;break}v||m.push(B);h.accountCache=JSON.stringify(m);if(n){v=false;n=JSON.parse(n);for(m=0;m<n.length;m++)if(a(n[m],i.domain,i.userid,i.username)){n[m]=i;v=true;break}}else n=[];v||n.push(i);h.serviceCache=JSON.stringify(n);j.changed()},fetch:function(i,m){e("account/get/full",{success:function(n){if(n.error)n=[];h.serviceCache=JSON.stringify(n);var v=[],B,C;for(C=0;C<n.length;C++){v.push(n[C].profile);B=c.domains[n[C].domain];B.clearCache(h)}h.accountCache=
JSON.stringify(v);i&&i(v,n)},error:m||function(){}})},remove:function(i,m,n){var v=h.accountCache,B=h.serviceCache,C,K;if(B){B=JSON.parse(B);for(C=0;K=B[C];C++)if(a(K,i,m,n)){B.splice(C,1);break}h.serviceCache=JSON.stringify(B)}if(v){v=JSON.parse(v);for(C=0;C<v.length;C++){K=v[C].accounts;for(B=0;B<K.length;B++)if(a(K[B],i,m,n)){v.splice(C,1);break}}h.accountCache=JSON.stringify(v)}c.domains[i].clearCache(h);j.changed()},getService:function(i,m,n){var v=h.serviceCache,B,C;if(v){v=JSON.parse(v);for(B=
0;C=v[B];B++)if(a(C,i,m,n))return C}return null},changed:function(){h.accountChanged=(new Date).getTime();opener&&!opener.closed&&d.pub("accountsChanged",null,opener);d.pub("accountsChanged")},onChange:function(i){var m=h.accountChanged;window.addEventListener("storage",function(){h.accountChanged!==m&&i()},false);d.sub("accountsChanged",i)}},memory:{accounts:function(){},changed:function(){h.accountChanged=(new Date).getTime();opener&&d.pub("accountsChanged",null,opener);d.pub("accountsChanged")},
onChange:function(i){d.sub("accountsChanged",i)}}}[b.type];f.update=function(i){j.update(i)};f.remove=function(i,m,n){j.remove(i,m,n)};f.fetch=function(i,m){j.fetch(i,m)};f.getService=function(i,m,n){return j.getService(i,m,n)};f.clear=function(){delete h.accountCache;delete h.serviceCache};f.changed=function(){return j.changed()};f.onChange=function(i){return j.onChange(i||g)};return f});
define("oauth",["accounts"],function(b){var d,e,c=0;window.addEventListener("message",function(a){var f;try{f=JSON.parse(a.data)}catch(g){return}if(f.target){if(f.target==="oauth_success"&&f.account){a=true;b.update(f.account)}else a=false;e=null;if(d){d(a);d=null}}},false);return function(a,f){if(f)d=f;f=location.protocol+"//"+location.host+"/auth.html";var g=(new Date).getTime();if(e&&e.closed)e=null;if(g>c+4E3){c=g;a=f+"?domain="+a;try{e=window.open(a,"ffshareOAuth","dialog=yes, modal=yes, width=900, height=500, scrollbars=yes");
e.focus()}catch(h){window.location=a+"&end_point_success="+encodeURI(window.location)}}else e&&e.focus()}});
define("blade/url",["./array"],function(b){var d=Object.prototype.toString;return{objectToQuery:function(e){var c=encodeURIComponent,a=[],f={},g,h,j,i;for(g in e)if(e.hasOwnProperty(g)){h=e[g];if(h!==f[g]){j=c(g)+"=";if(b.is(h))for(i=0;i<h.length;i++)a.push(j+c(h[i]));else a.push(j+c(h))}}return a.join("&")},queryToObject:function(e){var c={};e=e.split("&");var a=decodeURIComponent,f,g,h;e.forEach(function(j){if(j.length){f=j.split("=");g=a(f.shift());h=a(f.join("="));if(typeof c[g]==="string")c[g]=
[c[g]];if(d.call(c[g])==="[object Array]")c[g].push(h);else c[g]=h}});return c}}});
define("placeholder",["jquery"],function(b){function d(a){var f=!("placeholder"in a),g=a.getAttribute("placeholder"),h=a.value.trim();if(!h||h===g){if(f){b(a).addClass("placeholder");a.value=g;if(g==="password"&&a.type==="password")a.type="text"}}else b(a).removeClass("placeholder")}function e(a){a=a.target;var f=a.getAttribute("placeholder");if(a.value===f){if(!("placeholder"in a)){a.value="";if(f==="password"&&a.type==="text")a.type="password"}b(a).removeClass("placeholder")}}function c(a){d(a.target)}
return function(a){b('input[type="text"], input[type="password"], textarea',a).each(function(f,g){if(g.getAttribute("data-rdwPlaceholder")!=="set"){b(g).focus(e).blur(c);g.setAttribute("data-rdwPlaceholder","set")}d(g)})}});define("AutoComplete",["jquery","blade/object","blade/fn","dispatch"],function(b,d,e){return d(null,null,{init:function(c){this.dom=b(c);this.dom.bind("keyup",e.bind(this,"onKeyUp"))},onKeyUp:function(){}})});
(function(b,d){function e(c){return!b(c).parents().andSelf().filter(function(){return b.curCSS(this,"visibility")==="hidden"||b.expr.filters.hidden(this)}).length}b.ui=b.ui||{};if(!b.ui.version){b.extend(b.ui,{version:"1.8.6",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});b.fn.extend({_focus:b.fn.focus,focus:function(c,a){return typeof c==="number"?this.each(function(){var f=this;setTimeout(function(){b(f).focus();a&&a.call(f)},c)}):this._focus.apply(this,arguments)},scrollParent:function(){var c;c=b.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.curCSS(this,
"position",1))&&/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!c.length?b(document):c},zIndex:function(c){if(c!==d)return this.css("zIndex",c);if(this.length){c=b(this[0]);for(var a;c.length&&c[0]!==document;){a=c.css("position");
if(a==="absolute"||a==="relative"||a==="fixed"){a=parseInt(c.css("zIndex"),10);if(!isNaN(a)&&a!==0)return a}c=c.parent()}}return 0},disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(c){c.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});b.each(["Width","Height"],function(c,a){function f(i,m,n,v){b.each(g,function(){m-=parseFloat(b.curCSS(i,"padding"+this,true))||0;if(n)m-=parseFloat(b.curCSS(i,
"border"+this+"Width",true))||0;if(v)m-=parseFloat(b.curCSS(i,"margin"+this,true))||0});return m}var g=a==="Width"?["Left","Right"]:["Top","Bottom"],h=a.toLowerCase(),j={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+a]=function(i){if(i===d)return j["inner"+a].call(this);return this.each(function(){b(this).css(h,f(this,i)+"px")})};b.fn["outer"+a]=function(i,m){if(typeof i!=="number")return j["outer"+a].call(this,i);return this.each(function(){b(this).css(h,
f(this,i,true,m)+"px")})}});b.extend(b.expr[":"],{data:function(c,a,f){return!!b.data(c,f[3])},focusable:function(c){var a=c.nodeName.toLowerCase(),f=b.attr(c,"tabindex");if("area"===a){a=c.parentNode;f=a.name;if(!c.href||!f||a.nodeName.toLowerCase()!=="map")return false;c=b("img[usemap=#"+f+"]")[0];return!!c&&e(c)}return(/input|select|textarea|button|object/.test(a)?!c.disabled:"a"==a?c.href||!isNaN(f):!isNaN(f))&&e(c)},tabbable:function(c){var a=b.attr(c,"tabindex");return(isNaN(a)||a>=0)&&b(c).is(":focusable")}});
b(function(){var c=document.body,a=c.appendChild(a=document.createElement("div"));b.extend(a.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});b.support.minHeight=a.offsetHeight===100;b.support.selectstart="onselectstart"in a;c.removeChild(a).style.display="none"});b.extend(b.ui,{plugin:{add:function(c,a,f){c=b.ui[c].prototype;for(var g in f){c.plugins[g]=c.plugins[g]||[];c.plugins[g].push([a,f[g]])}},call:function(c,a,f){if((a=c.plugins[a])&&c.element[0].parentNode)for(var g=0;g<a.length;g++)c.options[a[g][0]]&&
a[g][1].apply(c.element,f)}},contains:function(c,a){return document.compareDocumentPosition?c.compareDocumentPosition(a)&16:c!==a&&c.contains(a)},hasScroll:function(c,a){if(b(c).css("overflow")==="hidden")return false;a=a&&a==="left"?"scrollLeft":"scrollTop";var f=false;if(c[a]>0)return true;c[a]=1;f=c[a]>0;c[a]=0;return f},isOverAxis:function(c,a,f){return c>a&&c<a+f},isOver:function(c,a,f,g,h,j){return b.ui.isOverAxis(c,f,h)&&b.ui.isOverAxis(a,g,j)}})}})(jQuery);
(function(b,d){if(b.cleanData){var e=b.cleanData;b.cleanData=function(a){for(var f=0,g;(g=a[f])!=null;f++)b(g).triggerHandler("remove");e(a)}}else{var c=b.fn.remove;b.fn.remove=function(a,f){return this.each(function(){if(!f)if(!a||b.filter(a,[this]).length)b("*",this).add([this]).each(function(){b(this).triggerHandler("remove")});return c.call(b(this),a,f)})}}b.widget=function(a,f,g){var h=a.split(".")[0],j;a=a.split(".")[1];j=h+"-"+a;if(!g){g=f;f=b.Widget}b.expr[":"][j]=function(i){return!!b.data(i,
a)};b[h]=b[h]||{};b[h][a]=function(i,m){arguments.length&&this._createWidget(i,m)};f=new f;f.options=b.extend(true,{},f.options);b[h][a].prototype=b.extend(true,f,{namespace:h,widgetName:a,widgetEventPrefix:b[h][a].prototype.widgetEventPrefix||a,widgetBaseClass:j},g);b.widget.bridge(a,b[h][a])};b.widget.bridge=function(a,f){b.fn[a]=function(g){var h=typeof g==="string",j=Array.prototype.slice.call(arguments,1),i=this;g=!h&&j.length?b.extend.apply(null,[true,g].concat(j)):g;if(h&&g.charAt(0)==="_")return i;
h?this.each(function(){var m=b.data(this,a),n=m&&b.isFunction(m[g])?m[g].apply(m,j):m;if(n!==m&&n!==d){i=n;return false}}):this.each(function(){var m=b.data(this,a);m?m.option(g||{})._init():b.data(this,a,new f(g,this))});return i}};b.Widget=function(a,f){arguments.length&&this._createWidget(a,f)};b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(a,f){b.data(f,this.widgetName,this);this.element=b(f);this.options=b.extend(true,{},this.options,
this._getCreateOptions(),a);var g=this;this.element.bind("remove."+this.widgetName,function(){g.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return b.metadata&&b.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(a,f){var g=a;if(arguments.length===0)return b.extend({},this.options);if(typeof a==="string"){if(f===d)return this.options[a];g={};g[a]=f}this._setOptions(g);return this},_setOptions:function(a){var f=this;b.each(a,function(g,h){f._setOption(g,h)});return this},_setOption:function(a,f){this.options[a]=f;if(a==="disabled")this.widget()[f?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",f);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(a,f,g){var h=this.options[a];f=b.Event(f);f.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase();g=g||{};if(f.originalEvent){a=b.event.props.length;for(var j;a;){j=b.event.props[--a];f[j]=f.originalEvent[j]}}this.element.trigger(f,g);return!(b.isFunction(h)&&h.call(this.element[0],f,g)===false||f.isDefaultPrevented())}}})(jQuery);
(function(b,d){function e(){return++a}function c(){return++f}var a=0,f=0;b.widget("ui.tabs",{options:{add:null,ajaxOptions:null,cache:false,cookie:null,collapsible:false,disable:null,disabled:[],enable:null,event:"click",fx:null,idPrefix:"ui-tabs-",load:null,panelTemplate:"<div></div>",remove:null,select:null,show:null,spinner:"<em>Loading&#8230;</em>",tabTemplate:"<li><a href='#{href}'><span>#{label}</span></a></li>"},_create:function(){this._tabify(true)},_setOption:function(g,h){if(g=="selected")this.options.collapsible&&
h==this.options.selected||this.select(h);else{this.options[g]=h;this._tabify()}},_tabId:function(g){return g.title&&g.title.replace(/\s/g,"_").replace(/[^\w\u00c0-\uFFFF-]/g,"")||this.options.idPrefix+e()},_sanitizeSelector:function(g){return g.replace(/:/g,"\\:")},_cookie:function(){var g=this.cookie||(this.cookie=this.options.cookie.name||"ui-tabs-"+c());return b.cookie.apply(null,[g].concat(b.makeArray(arguments)))},_ui:function(g,h){return{tab:g,panel:h,index:this.anchors.index(g)}},_cleanup:function(){this.lis.filter(".ui-state-processing").removeClass("ui-state-processing").find("span:data(label.tabs)").each(function(){var g=
b(this);g.html(g.data("label.tabs")).removeData("label.tabs")})},_tabify:function(g){function h(y,x){y.css("display","");!b.support.opacity&&x.opacity&&y[0].style.removeAttribute("filter")}var j=this,i=this.options,m=/^#.+/;this.list=this.element.find("ol,ul").eq(0);this.lis=b(" > li:has(a[href])",this.list);this.anchors=this.lis.map(function(){return b("a",this)[0]});this.panels=b([]);this.anchors.each(function(y,x){var D=b(x).attr("href"),J=D.split("#")[0],O;if(J&&(J===location.toString().split("#")[0]||
(O=b("base")[0])&&J===O.href)){D=x.hash;x.href=D}if(m.test(D))j.panels=j.panels.add(j._sanitizeSelector(D));else if(D&&D!=="#"){b.data(x,"href.tabs",D);b.data(x,"load.tabs",D.replace(/#.*$/,""));D=j._tabId(x);x.href="#"+D;x=b("#"+D);if(!x.length){x=b(i.panelTemplate).attr("id",D).addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").insertAfter(j.panels[y-1]||j.list);x.data("destroy.tabs",true)}j.panels=j.panels.add(x)}else i.disabled.push(y)});if(g){this.element.addClass("ui-tabs ui-widget ui-widget-content ui-corner-all");
this.list.addClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.lis.addClass("ui-state-default ui-corner-top");this.panels.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom");if(i.selected===d){location.hash&&this.anchors.each(function(y,x){if(x.hash==location.hash){i.selected=y;return false}});if(typeof i.selected!=="number"&&i.cookie)i.selected=parseInt(j._cookie(),10);if(typeof i.selected!=="number"&&this.lis.filter(".ui-tabs-selected").length)i.selected=
this.lis.index(this.lis.filter(".ui-tabs-selected"));i.selected=i.selected||(this.lis.length?0:-1)}else if(i.selected===null)i.selected=-1;i.selected=i.selected>=0&&this.anchors[i.selected]||i.selected<0?i.selected:0;i.disabled=b.unique(i.disabled.concat(b.map(this.lis.filter(".ui-state-disabled"),function(y){return j.lis.index(y)}))).sort();b.inArray(i.selected,i.disabled)!=-1&&i.disabled.splice(b.inArray(i.selected,i.disabled),1);this.panels.addClass("ui-tabs-hide");this.lis.removeClass("ui-tabs-selected ui-state-active");
if(i.selected>=0&&this.anchors.length){b(j._sanitizeSelector(j.anchors[i.selected].hash)).removeClass("ui-tabs-hide");this.lis.eq(i.selected).addClass("ui-tabs-selected ui-state-active");j.element.queue("tabs",function(){j._trigger("show",null,j._ui(j.anchors[i.selected],b(j._sanitizeSelector(j.anchors[i.selected].hash))))});this.load(i.selected)}b(window).bind("unload",function(){j.lis.add(j.anchors).unbind(".tabs");j.lis=j.anchors=j.panels=null})}else i.selected=this.lis.index(this.lis.filter(".ui-tabs-selected"));
this.element[i.collapsible?"addClass":"removeClass"]("ui-tabs-collapsible");i.cookie&&this._cookie(i.selected,i.cookie);g=0;for(var n;n=this.lis[g];g++)b(n)[b.inArray(g,i.disabled)!=-1&&!b(n).hasClass("ui-tabs-selected")?"addClass":"removeClass"]("ui-state-disabled");i.cache===false&&this.anchors.removeData("cache.tabs");this.lis.add(this.anchors).unbind(".tabs");if(i.event!=="mouseover"){var v=function(y,x){x.is(":not(.ui-state-disabled)")&&x.addClass("ui-state-"+y)},B=function(y,x){x.removeClass("ui-state-"+
y)};this.lis.bind("mouseover.tabs",function(){v("hover",b(this))});this.lis.bind("mouseout.tabs",function(){B("hover",b(this))});this.anchors.bind("focus.tabs",function(){v("focus",b(this).closest("li"))});this.anchors.bind("blur.tabs",function(){B("focus",b(this).closest("li"))})}var C,K;if(i.fx)if(b.isArray(i.fx)){C=i.fx[0];K=i.fx[1]}else C=K=i.fx;var z=K?function(y,x){b(y).closest("li").addClass("ui-tabs-selected ui-state-active");x.hide().removeClass("ui-tabs-hide").animate(K,K.duration||"normal",
function(){h(x,K);j._trigger("show",null,j._ui(y,x[0]))})}:function(y,x){b(y).closest("li").addClass("ui-tabs-selected ui-state-active");x.removeClass("ui-tabs-hide");j._trigger("show",null,j._ui(y,x[0]))},A=C?function(y,x){x.animate(C,C.duration||"normal",function(){j.lis.removeClass("ui-tabs-selected ui-state-active");x.addClass("ui-tabs-hide");h(x,C);j.element.dequeue("tabs")})}:function(y,x){j.lis.removeClass("ui-tabs-selected ui-state-active");x.addClass("ui-tabs-hide");j.element.dequeue("tabs")};
this.anchors.bind(i.event+".tabs",function(){var y=this,x=b(y).closest("li"),D=j.panels.filter(":not(.ui-tabs-hide)"),J=b(j._sanitizeSelector(y.hash));if(x.hasClass("ui-tabs-selected")&&!i.collapsible||x.hasClass("ui-state-disabled")||x.hasClass("ui-state-processing")||j.panels.filter(":animated").length||j._trigger("select",null,j._ui(this,J[0]))===false){this.blur();return false}i.selected=j.anchors.index(this);j.abort();if(i.collapsible)if(x.hasClass("ui-tabs-selected")){i.selected=-1;i.cookie&&
j._cookie(i.selected,i.cookie);j.element.queue("tabs",function(){A(y,D)}).dequeue("tabs");this.blur();return false}else if(!D.length){i.cookie&&j._cookie(i.selected,i.cookie);j.element.queue("tabs",function(){z(y,J)});j.load(j.anchors.index(this));this.blur();return false}i.cookie&&j._cookie(i.selected,i.cookie);if(J.length){D.length&&j.element.queue("tabs",function(){A(y,D)});j.element.queue("tabs",function(){z(y,J)});j.load(j.anchors.index(this))}else throw"jQuery UI Tabs: Mismatching fragment identifier.";
b.browser.msie&&this.blur()});this.anchors.bind("click.tabs",function(){return false})},_getIndex:function(g){if(typeof g=="string")g=this.anchors.index(this.anchors.filter("[href$="+g+"]"));return g},destroy:function(){var g=this.options;this.abort();this.element.unbind(".tabs").removeClass("ui-tabs ui-widget ui-widget-content ui-corner-all ui-tabs-collapsible").removeData("tabs");this.list.removeClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.anchors.each(function(){var h=
b.data(this,"href.tabs");if(h)this.href=h;var j=b(this).unbind(".tabs");b.each(["href","load","cache"],function(i,m){j.removeData(m+".tabs")})});this.lis.unbind(".tabs").add(this.panels).each(function(){b.data(this,"destroy.tabs")?b(this).remove():b(this).removeClass("ui-state-default ui-corner-top ui-tabs-selected ui-state-active ui-state-hover ui-state-focus ui-state-disabled ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide")});g.cookie&&this._cookie(null,g.cookie);return this},add:function(g,
h,j){if(j===d)j=this.anchors.length;var i=this,m=this.options;h=b(m.tabTemplate.replace(/#\{href\}/g,g).replace(/#\{label\}/g,h));g=!g.indexOf("#")?g.replace("#",""):this._tabId(b("a",h)[0]);h.addClass("ui-state-default ui-corner-top").data("destroy.tabs",true);var n=b("#"+g);n.length||(n=b(m.panelTemplate).attr("id",g).data("destroy.tabs",true));n.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide");if(j>=this.lis.length){h.appendTo(this.list);n.appendTo(this.list[0].parentNode)}else{h.insertBefore(this.lis[j]);
n.insertBefore(this.panels[j])}m.disabled=b.map(m.disabled,function(v){return v>=j?++v:v});this._tabify();if(this.anchors.length==1){m.selected=0;h.addClass("ui-tabs-selected ui-state-active");n.removeClass("ui-tabs-hide");this.element.queue("tabs",function(){i._trigger("show",null,i._ui(i.anchors[0],i.panels[0]))});this.load(0)}this._trigger("add",null,this._ui(this.anchors[j],this.panels[j]));return this},remove:function(g){g=this._getIndex(g);var h=this.options,j=this.lis.eq(g).remove(),i=this.panels.eq(g).remove();
if(j.hasClass("ui-tabs-selected")&&this.anchors.length>1)this.select(g+(g+1<this.anchors.length?1:-1));h.disabled=b.map(b.grep(h.disabled,function(m){return m!=g}),function(m){return m>=g?--m:m});this._tabify();this._trigger("remove",null,this._ui(j.find("a")[0],i[0]));return this},enable:function(g){g=this._getIndex(g);var h=this.options;if(b.inArray(g,h.disabled)!=-1){this.lis.eq(g).removeClass("ui-state-disabled");h.disabled=b.grep(h.disabled,function(j){return j!=g});this._trigger("enable",null,
this._ui(this.anchors[g],this.panels[g]));return this}},disable:function(g){g=this._getIndex(g);var h=this.options;if(g!=h.selected){this.lis.eq(g).addClass("ui-state-disabled");h.disabled.push(g);h.disabled.sort();this._trigger("disable",null,this._ui(this.anchors[g],this.panels[g]))}return this},select:function(g){g=this._getIndex(g);if(g==-1)if(this.options.collapsible&&this.options.selected!=-1)g=this.options.selected;else return this;this.anchors.eq(g).trigger(this.options.event+".tabs");return this},
load:function(g){g=this._getIndex(g);var h=this,j=this.options,i=this.anchors.eq(g)[0],m=b.data(i,"load.tabs");this.abort();if(!m||this.element.queue("tabs").length!==0&&b.data(i,"cache.tabs"))this.element.dequeue("tabs");else{this.lis.eq(g).addClass("ui-state-processing");if(j.spinner){var n=b("span",i);n.data("label.tabs",n.html()).html(j.spinner)}this.xhr=b.ajax(b.extend({},j.ajaxOptions,{url:m,success:function(v,B){b(h._sanitizeSelector(i.hash)).html(v);h._cleanup();j.cache&&b.data(i,"cache.tabs",
true);h._trigger("load",null,h._ui(h.anchors[g],h.panels[g]));try{j.ajaxOptions.success(v,B)}catch(C){}},error:function(v,B){h._cleanup();h._trigger("load",null,h._ui(h.anchors[g],h.panels[g]));try{j.ajaxOptions.error(v,B,g,i)}catch(C){}}}));h.element.dequeue("tabs");return this}},abort:function(){this.element.queue([]);this.panels.stop(false,true);this.element.queue("tabs",this.element.queue("tabs").splice(-2,2));if(this.xhr){this.xhr.abort();delete this.xhr}this._cleanup();return this},url:function(g,
h){this.anchors.eq(g).removeData("cache.tabs").data("load.tabs",h);return this},length:function(){return this.anchors.length}});b.extend(b.ui.tabs,{version:"1.8.6"});b.extend(b.ui.tabs.prototype,{rotation:null,rotate:function(g,h){var j=this,i=this.options,m=j._rotate||(j._rotate=function(n){clearTimeout(j.rotation);j.rotation=setTimeout(function(){var v=i.selected;j.select(++v<j.anchors.length?v:0)},g);n&&n.stopPropagation()});h=j._unrotate||(j._unrotate=!h?function(n){n.clientX&&j.rotate(null)}:
function(){t=i.selected;m()});if(g){this.element.bind("tabsshow",m);this.anchors.bind(i.event+".tabs",h);m()}else{clearTimeout(j.rotation);this.element.unbind("tabsshow",m);this.anchors.unbind(i.event+".tabs",h);delete this._rotate;delete this._unrotate}return this}})})(jQuery);define("jquery-ui-1.8.6.custom.min",function(){});
(function(b){var d=document.documentElement.style,e="textOverflow"in d||"OTextOverflow"in d,c=function(a,f){var g=0,h=[],j=function(i){var m=0,n;if(!(g>f))for(m=0;m<i.length;m+=1)if(i[m].nodeType===1){n=i[m].cloneNode(false);h[h.length-1].appendChild(n);h.push(n);j(i[m].childNodes);h.pop()}else if(i[m].nodeType===3){if(g+i[m].length<f)h[h.length-1].appendChild(i[m].cloneNode(false));else{n=i[m].cloneNode(false);n.textContent=b.trim(n.textContent.substring(0,f-g));h[h.length-1].appendChild(n)}g+=i[m].length}else h.appendChild(i[m].cloneNode(false))};
h.push(a.cloneNode(false));j(a.childNodes);return b(h.pop().childNodes)};b.extend(b.fn,{textOverflow:function(a,f){var g=a||"&#x2026;";return e?this:this.each(function(){var h=b(this),j=h.clone(),i=h.clone(),m=h.text(),n=h.width(),v=0,B=0,C=m.length,K=function(){if(n!==h.width()){h.replaceWith(i);h=i;i=h.clone();h.textOverflow(a,false);n=h.width()}};h.after(j.hide().css({position:"absolute",width:"auto",overflow:"visible","max-width":"inherit"}));if(j.width()>n){for(;v<C;){B=Math.floor(v+(C-v)/2);
j.empty().append(c(i.get(0),B)).append(g);if(j.width()<n)v=B+1;else C=B}v<m.length&&h.empty().append(c(i.get(0),v-1)).append(g)}j.remove();f&&setInterval(K,200)})}})})(jQuery);define("jquery.textOverflow",function(){});
define("index",["require","jquery","blade/fn","rdapi","oauth","blade/jig","blade/url","placeholder","TextCounter","AutoComplete","dispatch","accounts","storage","services","blade/object","jquery-ui-1.8.6.custom.min","jquery.textOverflow"],function(b,d,e,c,a,f,g,h,j,i,m,n,v,B,C){function K(q){return q?q.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"):q}function z(){m.pub("hide")}function A(){F.addClass("hidden");d("div.status").addClass("hidden");h()}function y(){var q=p&&p.domain||
"twitter.com",s=r.siteName,G=r.url||"",H=G.indexOf("//")+2;d("#statusShared").empty().append(f("#sharedTemplate",{domain:s||G.slice(H,G.indexOf("/",H)),service:o[q].name,href:o[q].serviceUrl})).find(".shareTitle").textOverflow(null,true);l("statusShared",true)}function x(q,s){d("#captchaImage").attr("src",q.imageurl);s&&d("#captchaMsg").text(s.message);d("#captchaSound").attr("src",q.audiourl);l("statusCaptcha",false)}function D(){var q={link:p.link,domain:p.domain,formData:o[p.domain].getFormData()};
L.sessionRestore=JSON.stringify(q);l("statusAuth")}function J(){l("statusSharing");if(o[p.domain].validate(p)){var q=n.getService(p.domain,p.userid,p.username);p.account=JSON.stringify(q);c("send",{type:"POST",data:p,success:function(s){if(s.error&&s.error.status){var G=s.error.status;if(G===401||G===535)D();else if(s.error.code==="Client.HumanVerificationRequired")x(s.error.detail);else s.error.code==="Client.WrongInput"?x(s.error.detail,s.error):l("statusError",s.error.message)}else if(s.error)l("statusError",
s.error.message);else{L.lastSelection=o[p.domain].type;y()}delete L.sessionRestore},error:function(s,G,H){if(s.status===403)D();else s.status===503?l("statusServerBusy"):l("statusError",H)}})}else l("statusToError")}function O(q){var s=B.domains[q],G=d("#"+s.type).find('[name="to"]')[0],H=s.getContacts(L);H||(H=[]);if(!s.autoCompleteWidget)s.autoCompleteWidget=new i(G);q==="google.com"&&m.pub("autoCompleteData",H)}function aa(q,s){var G=s.accounts[0],H=B.domains[G.domain];if(H.getContacts(L))O(G.domain);
else{q=n.getService(G.domain,G.userid,G.username);c("contacts/"+G.domain,{type:"POST",data:{username:G.username,userid:G.userid,startindex:0,maxresults:500,account:JSON.stringify(q)},success:function(M){if(M&&!M.error){var N=[];N=H.get36FormattedContacts(M.result.entry);H.setContacts(L,N);O(G.domain)}}})}}function U(q,s){var G=q="",H=true,M="",N=s.panel.id,I=d(".user-info");if(N!=="debug"){q=d(s.panel).find("div.user img.avatar").attr("src");G=d(s.panel).find("div.user .username").text();H=d(s.panel).find("div.user").hasClass("inactive");
M=d(s.panel).find("div.user input[type='hidden'][name='domain']").val()}d(".user-info img.avatar").attr("src",q);q?I.show():I.hide();d(".user-info .status").toggleClass("inactive",H);d(".user-info .username").text(G);d(".user-info").attr("data-domain",M)}function W(q,s){d(function(){var G=s.displayName,H=s.accounts[0],M=s.photos&&s.photos[0]&&s.photos[0].value,N=d("#"+q),I;if((I=H.username)&&I!==G)G=G+" <"+I+">";d("."+q+"Tab").removeClass("hidden");G&&N.find(".username").text(G);M&&N.find(".avatar").attr("src",
M);N.find('input[name="userid"]').val(H.userid);N.find('input[name="username"]').val(H.username);N.find("div.user").removeClass("inactive")})}function V(){var q,s;if(L.lastSelection)q="#"+L.lastSelection;else if(P&&P.length){s=P[0].accounts[0].domain;if(o[s])if(s=o[s].type)q="#"+s}return q}function Z(){d(".ui-tabs-nav > li").removeClass("first").removeClass("last").filter(function(){var q=d(this),s=q.hasClass("hidden");q=q.hasClass("debugTab");return!s&&!q}).first().addClass("first").end().last().addClass("last")}
function k(q){var s=false,G={},H=L.sessionRestore,M;q&&q.length&&q.forEach(function(N){var I=N.accounts[0].domain;if(I&&o[I]){s||(s=o[I].type===L.lastSelection);G[o[I].type]=N}});!s&&!L.accountAdded&&L.lastSelection&&delete L.lastSelection;L.accountAdded&&delete L.accountAdded;for(M in G)if(G.hasOwnProperty(M)){W(M,G[M]);aa(M,G[M])}if(H){H=JSON.parse(H);if(r.link!==H.link){H=null;delete L.sessionRestore}if(H){o[H.domain].setFormData(H.formData);h()}}if(R){q=V();w.tabs("select",q);U(null,{panel:d(q)[0]})}Z()}
B.isFF36=true;var l,o=B.domains;b=location.href.split("#")[1];var p,u,r={},w,E,F,R=true,S,P,ba,L=v();C.mixin(B.svcBaseProto,{validate:function(){if(this.counter)return!this.counter||!this.counter.isOver();return true},startCounter:function(q){if(!(this.textLimit<1)){if(!this.counter)this.counter=new j(d("#"+this.type+" textarea.message"),d("#"+this.type+" .counter"),this.textLimit-26);this.counter.updateLimit(q.shortUrl?this.textLimit-(q.shortUrl.length+1):this.textLimit-26)}},getFormData:function(){var q=
d("#"+this.type);return{to:q.find('[name="to"]').val().trim()||"",subject:q.find('[name="subject"]').val().trim()||"",message:q.find("textarea.message").val().trim()||"",picture:q.find('[name="picture"]').val().trim()||"",canonicalUrl:q.find('[name="link"]').val().trim()||"",title:q.find('[name="title"]').val().trim()||"",description:q.find('[name="description"]').val().trim()||"",shortUrl:(q.find('[name="surl"]').val()||"").trim()}},setFormData:function(q){var s=d("#"+this.type);q.to&&s.find('[name="to"]').val(q.to);
q.subject&&s.find('[name="subject"]').val(q.subject);q.message&&s.find("textarea.message").val(q.message);q.previews&&q.previews.length&&s.find('[name="picture"]').val(q.previews[0]);if(q.canonicalUrl||q.url)s.find('[name="link"]').val(q.canonicalUrl||q.url);q.title&&s.find('[name="title"]').val(q.title);q.description&&s.find('[name="description"]').val(q.description);q.shortUrl&&s.find('[name="surl"]').val(q.shortUrl);this.startCounter(q)}});f.addFn({profilePic:function(q){return q&&q[0]&&q[0].value||
"i/face2.png"},serviceName:function(q){return o[q].name}});window.closeShare=z;l=function(q,s){d("div.status").addClass("hidden");F.removeClass("hidden");d("#"+q).removeClass("hidden");if(s===true)setTimeout(function(){m.pub("success",{domain:p.domain,username:p.username,userid:p.userid})},2E3);else s&&d("#"+q+"Message").text(s)};window.showStatus=l;window.showStatusShared=y;window.handleCaptcha=x;if(b){g=g.queryToObject(b);if(g.options)r=JSON.parse(g.options)}r.prefs=r.prefs||{};if(!r.title)r.title=
r.url;if(!r.prefs.system)r.prefs.system="prod";if(r.version)L.extensionVersion=r.version;if(r.prefs)for(u in r.prefs)if(r.prefs.hasOwnProperty(u))L["prefs."+u]=r.prefs[u];if(u=L.newTimerV2){u=JSON.parse(u);if((new Date).getTime()-u<2592E5)ba=true}else{L.newTimerV1=(new Date).getTime();ba=true}d(function(){var q,s=L.sessionRestore,G,H="",M="",N;B.domainList.forEach(function(I){var Q=B.domains[I];Q.domain=I;if(I==="linkedin.com")Q.features.subject=false;H+=f("#tabsTemplate",Q);M+=f("#panelsTemplate",
Q)});d(".nav .debugTab").before(H);d("#tabs #debug").before(M);q=d("img.thumb");E=d("body");F=d("#clickBlock");r.prefs.system&&d(document.documentElement).addClass(r.prefs.system);if(r.prefs.system==="dev"){d("#debugOutput").val(JSON.stringify(r));d("#debugCurrentLocation").val(location.href)}ba&&d("#newLink").removeClass("hidden");E.delegate("#statusAuthButton, .statusErrorButton","click",function(){A()}).delegate(".statusErrorCloseButton","click",function(){z()}).delegate(".statusResetErrorButton",
"click",function(){location.reload()}).delegate(".nav .close","click",z);d("#authOkButton").click(function(){a(p.domain,function(I){if(I){n.clear();n()}else l("statusOAuthFailed")})});d("#captchaButton").click(function(){A();F.removeClass("hidden");p.HumanVerification=d("#captcha").attr("value");p.HumanVerificationImage=d("#captchaImage").attr("src");J()});n.onChange();if(v.type==="memory")l("statusEnableLocalStorage");else{n(function(I){P=I;R=false;k(P);R=true;if(S=V()){d("."+S.slice(1)+"Tab").addClass("ui-tabs-selected ui-state-active");
G=d(S);G.removeClass("ui-tabs-hide");U(null,{panel:G[0]});w=d("#tabs");w.tabs({fx:{opacity:"toggle",duration:100}});w.bind("tabsselect",U);w.removeClass("invisible");E.removeClass("loading");Z()}else l("statusSettings")},function(I,Q,T){I.status===503?l("statusServerBusyClose"):l("statusServerError",T)});for(N in B.domains)B.domains.hasOwnProperty(N)&&B.domains[N].setFormData(r);if(s)s=JSON.parse(s);r.title&&d(".title").text(r.title);r.description&&d(".description").text(r.description);if(r.previews&&
r.previews.length){s=K(r.previews[0]);q.attr("src",s)}else r.thumbnail&&q.attr("src",K(r.thumbnail));d(".title").textOverflow(null,true);d(".description").textOverflow(null,true);d(".url").textOverflow(null,true);d(".surl").textOverflow(null,true);d("form.messageForm").submit(function(I){I=I.target;var Q,T,$;p={};d.each(I.elements,function(X,Y){X=Y.value.trim();if(Y.getAttribute("placeholder")===X)X="";Y.value=X;if(Y.value)p[Y.name]=Y.value});I=B.domains[p.domain];if(r.shortUrl)p.shorturl=r.shortUrl;
else if(I.shorten)p.shorten=true;if(p.to){Q=I.getContacts(L);$=[];if(Q){I=p.to.split(",");I.forEach(function(X){if((T=Q[X.trim()])&&!T.email)$.push(T.userid?T.userid:T.username)})}if($.length>0)p.to=$.join(", ")}J();return false}).each(function(I,Q){h(Q)})}})});