/*
 blade/func Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/object Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/jig Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/array Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/url Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
*/
define("blade/fn",[],function(){var b=Array.prototype.slice,d=Object.prototype.toString;return{is:function(e){return d.call(e)==="[object Function]"},bind:function(e,c){if(!c)return e;if(typeof c==="string")c=e[c];var a=b.call(arguments,2);return function(){return c.apply(e,a.concat(b.call(arguments,0)))}}}});
define("blade/object",["./fn"],function(b){function d(){}var e={},c=function(a,f,g){a=a||{};var h,j=c.create(a.prototype,f);a=function(k,l,o){return j[l].apply(k,o)};f=c.create(j);c.mixin(f,b.is(g)?g(a):g,true);h=function(){if(!(this instanceof h))throw new Error('blade/object: constructor function called without "new" in front');this.init&&this.init.apply(this,arguments)};h.prototype=f;return h};c.create=function(a,f){d.prototype=a;a=new d;var g,h;d.prototype=null;if(f)for(g=0;h=f[g];g++)c.mixin(a,
h);return a};c.mixin=function(a,f,g){for(var h in f)if(!(h in e)&&(!(h in a)||g))a[h]=f[h]};return c});
define("blade/jig",["require","./object"],function(b,d){function e(i){return z.call(i)==="[object Array]"}function c(i,m,n){m=m;var r,p;for(r=0;m&&(p=i[r]);r++)m=typeof m==="object"&&p in m?m[p]:n&&r===0&&p in n?n[p]:undefined;return m}function a(i){return i?parseInt(i,10):0}function f(i,m,n){var r=/\[([\w0-9\.'":]+)\]/,p=i,B=m,y=true,E,G;if(i===A)return m;if(x.test(i))return a(i);if(i==="")return"";E=i.charAt(0);if(E==="'"||E==="'")return i.substring(1,i.length-1);if((E=i.indexOf("("))!==-1){r=i.lastIndexOf(")");
y=i.substring(0,E);p=n.fn[y];if(!p){o.error("Cannot find function named: "+y+" for "+i);return""}y=i.substring(E+1,r);if(y.indexOf(",")!==-1){y=y.split(",");for(B=y.length-1;B>=0;B--)y[B]=f(y[B],m,n);p=p.apply(null,y)}else p=p(f(y,m,n));if(r<i.length-1){if(i.charAt(r+1)===".")r+=1;return f(i.substring(r+1,i.length),p,n)}else return p}for(;E=r.exec(p);){m=E[1].replace(/['"]/g,"");G=p.substring(0,E.index);p=p.substring(E.index+E[0].length,p.length);if(p.indexOf(".")===0)p=p.substring(1,p.length);B=
c(G.split("."),B,y?n.context:null);y=false;if(!B&&m){o.error('blade/jig: No property "'+m+'" on '+B);return""}if(m.indexOf(":")!==-1){E=m.split(":");m=a(E[0]);B=(E=a(E[1]))?B.slice(m,E):B.slice(m)}else{n.strict&&!(m in B)&&o.error('blade/jig: no property "'+m+'"');B=B[m]}B=B}p=p?c(p.split("."),B,y?n.context:null):B;n.strict&&p===undefined&&o.error('blade/jig: undefined value for property "'+i+'"');return p}function g(i,m){m=m||{};var n=o.cache(i,m);if(n===undefined&&typeof document!=="undefined"){(n=
document.getElementById(i))&&o.parse([n],m);n=o.cache(i,m)}if(n===undefined)throw new Error("blade/jig: no template or node with ID: "+i);return n}function h(i,m){for(var n=[],r=0,p=false,B=0,y,E,G,R,S,P;(y=i.indexOf(m.startToken,r))!==-1;){y!==r&&n.push(i.substring(r,y));r=i.substring(y);if(E=m.endRegExp.exec(r)){r=y+E[0].length;G=i.substring(y+m.startToken.length,y+E[0].length-m.endToken.length).trim();G=C(G);if(D.test(G))throw new Error("blade/jig: end block tags should not be commented: "+G);
y=G.charAt(0);if(y==="]"&&B){p=G.substring(1).trim();if(p==="[")y=">";else{y=p.charAt(0);G=p}}if(y&&!m.propertyRegExp.test(y))G=G.substring(1).trim();else y="_default_";if(p=G.indexOf(m.rawHtmlToken)===0)G=G.substring(m.rawHtmlToken.length,G.length);if(y===F)p=true;G=G.split(m.argSeparator);R=G[G.length-1];S=R.charAt(R.length-1);P=null;if(y==="]"){if(S!=="["){n.templateEnd=r;n.endControl=true}else n.templateEnd=r-E[0].length;return n}else if(S==="["){B||(B=Z++);G[G.length-1]=R.substring(0,R.length-
1);P=h(i.substring(r),m);r+=P.templateEnd}if(y==="+")m.templates[G[0]]=P;else if(y!=="/"){if(G.length>1)for(E=G.length-1;E>=0;E--)if(G[E].charAt(G[E].length-1)===","){G[E]+=G[E+1];G.splice(E+1,1)}n.push({action:m.commands[y].action,useRawHtml:p,args:G,controlId:B,children:P})}if(P&&P.endControl)B=0}else{n.push(r);return n}}r!==i.length-1&&n.push(i.substring(r,i.length));return n}function j(i,m){var n,r=i.id;n=m.templates||K;if(n[r])return n[r];m.onBeforeParse&&m.onBeforeParse(i);if(i.nodeName.toUpperCase()===
"SCRIPT"){n=i.text.trim();i.parentNode&&i.parentNode.removeChild(i)}else{V.appendChild(i);i.removeAttribute("id");(n=(i.getAttribute("class")||"").trim())&&i.setAttribute("class",n.replace(aa,"$1$3"));n=V.innerHTML.replace(/%7B/g,"{").replace(/%7D/g,"}");V.removeChild(i)}i=o.compile(n,m);o.cache(r,i,m);return i}function k(i,m,n){var r="",p,B,y,E,G;if(typeof i==="string")r=i;else if(e(i))for(p=0;p<i.length;p++){y=i[p].controlId;if(!y||y!==B||!G){E=k(i[p],m,n);r+=E;if(y){B=y;G=E}}}else if(r=i.action(i.args,
m,n,i.children,k)){if(!i.useRawHtml&&!i.children)r=o.htmlEscape(r.toString())}else r="";if(n.attachData)if(w.test(r)){i="id"+Y++;r=r.replace(w,'$& data-blade-jig="'+i+'" ');T[i]=m}return r}function l(i){i.fn.jig=function(m,n){n=n||{};var r=this.selector;if(r.charAt(0)!=="#")throw new Error('blade/jig: only ID selectors, like "#something" are allowed with jig()');r=r.substring(1,r.length);(r=(n.templates||K)[r])||(r=j(this[0]));return i(o.render(r,m,n))}}var o,s,z=Object.prototype.toString,C=typeof decodeURIComponent===
"undefined"?function(){}:decodeURIComponent,F="#",v=/[_\[\^\w]/,A="_",w=/<\s*\w+/,x=/^\d+$/,D=/\/(\/)?\s*\]/,K={},O={openCurly:function(){return"{"},closeCurly:function(){return"}"},eq:function(i,m){return i===m},gt:function(i,m){return i>m},gte:function(i,m){return i>=m},lt:function(i,m){return i<m},lte:function(i,m){return i<=m},or:function(i,m){return i||m},and:function(i,m){return i&&m},is:function(i){return!!i},eachProp:function(i){var m,n=[];for(m in i)i.hasOwnProperty(m)&&n.push({prop:m,value:i[m]});
return n.sort(function(r,p){return r.prop>p.prop?1:-1})}},Y=1,Z=1,T={},V=typeof document!=="undefined"&&document.createElement?document.createElement("div"):null,aa=/(\s*)(template)(\s*)/;s={_default_:{doc:"Property reference",action:function(i,m,n,r,p){var B=i[0]?f(i[0],m,n):m,y=i[1]?f(i[1],m,n):undefined,E="";if(i[1]){y=B===y;B=m}else y=B;if(y===false||y===null||y===undefined||e(y)&&!y.length)return"";else if(r)if(e(B))for(i=0;i<B.length;i++)E+=p(r,B[i],n);else{if(typeof B==="boolean")B=m;E=p(r,
B,n)}else E=B;return E}},"!":{doc:"Not",action:function(i,m,n,r,p){var B=f(i[0],m,n),y=i[1]?f(i[1],m,n):undefined;y=i[1]?B===y:B;if(r&&!y)return p(r,m,n);return""}},"#":{doc:"Template reference",action:function(i,m,n,r,p){r=g(i[0],n);m=f(i.length>1?i[1]:A,m,n);return p(r,m,n)}},".":{doc:"Variable declaration",action:function(i,m,n){n.context[i[0]]=f(i[1],m,n);return""}},">":{doc:"Else",action:function(i,m,n,r,p){if(r)return p(r,m,n);return""}}};o=function(i,m,n){if(typeof i==="string")if(i.charAt(0)===
"#"){i=i.substring(1,i.length);i=g(i,n)}else i=o.compile(i,n);return o.render(i,m,n)};o.htmlEscape=function(i){return i.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};o.compile=function(i,m){m=m||{};d.mixin(m,{startToken:"{",endToken:"}",rawHtmlToken:"^",propertyRegExp:v,commands:s,argSeparator:" ",templates:K});m.endRegExp=/[^\r\n]*?}/;Z=1;return h(i,m)};o.parse=function(i,m){if(i&&!i.length){m=i;i=null}m=m||{};i=i||document.querySelectorAll('.template, script[type="text/template"]');
var n,r;for(r=i.length-1;r>-1&&(n=i[r]);r--)j(n,m)};o.render=function(i,m,n){var r,p="";n=n||{};d.mixin(n,{templates:K,attachData:false,strict:o.strict});if(n.fn)d.mixin(n.fn,O);else n.fn=O;n.context=n.context||d.create(m);if(e(m)){for(r=0;r<m.length;r++)p+=k(i,m[r],n);return p}return k(i,m,n)};o.strict=false;o.error=function(i){throw i;};o.addFn=function(i){d.mixin(O,i,true)};o.data=function(i,m){if(typeof i!=="string"){i.nodeType||(i=i[0]);i=i.getAttribute("data-blade-jig")}return m!==undefined?
(T[i]=m):T[i]};o.removeData=function(i){delete T[i]};o.getObject=f;o.cache=function(i,m,n){if(typeof m==="string")m=o.compile(m,n);if(!e(m)){n=m;m=undefined}n=n&&n.templates||K;if(m!==undefined)n[i]=m;return n[i]||K[i]};typeof jQuery!=="undefined"&&l(jQuery);return o});
define("friendly",["require","exports","module"],function(){var b={timestamp:function(d){return b.date(new Date(d*1E3))},date:function(d){var e=((new Date).getTime()-d.getTime())/1E3,c=Math.floor(e/86400),a={friendly:d.toLocaleDateString(),additional:d.toLocaleTimeString(),utc:d.toUTCString(),locale:d.toLocaleString()};if(c<0){a.friendly="in the future";return a}else if(isNaN(c)){a.friendly=a.additional="unknown";return a}if(c===0){if(e<60){a.friendly="just now";return a}if(e<150){a.friendly="a minute ago";
return a}if(e<3600){a.friendly=Math.floor(e/60)+" minutes ago";return a}if(e<7200){a.friendly="1 hour ago";return a}if(e<86400){a.friendly=Math.floor(e/3600)+" hours ago";return a}}if(c===1){a.friendly="yesterday";return a}if(c<7){a.friendly=c+" days ago";return a}if(c<8){a.friendly="last week";return a}if(c<31){a.friendly=Math.ceil(c/7)+" weeks ago";return a}if(c<62){a.friendly="a month ago";return a}if(c<365){a.friendly=Math.ceil(c/31)+" months ago";return a}if(c>=365&&c<730){a.additional=d.toLocaleDateString();
a.friendly="a year ago";return a}if(c>=365){a.additional=d.toLocaleDateString();a.friendly=Math.ceil(c/365)+" years ago";return a}return a},name:function(d){d=d.split(" ")[0];if(d.indexOf("@")!==-1)d=d.split("@")[0];d=d.replace(" ","");d=d.replace("'","");return d=d.replace('"',"")}};return b});
define("isoDate",[],function(){var b=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+\-](\d{2}):(\d{2}))|Z)?)?$/,d=function(e,c){var a=b.exec(e);e=null;var f,g;if(a){a.shift();a[1]&&a[1]--;if(a[6])a[6]*=1E3;if(c){c=new Date(c);["FullYear","Month","Date","Hours","Minutes","Seconds","Milliseconds"].map(function(h){return c["get"+h]()}).forEach(function(h,j){a[j]=a[j]||h})}e=new Date(a[0]||1970,a[1]||0,a[2]||1,a[3]||0,a[4]||0,a[5]||0,a[6]||0);if(a[0]<100)e.setFullYear(a[0]||
1970);f=0;g=a[7]&&a[7].charAt(0);if(g!=="Z"){f=(a[8]||0)*60+(Number(a[9])||0);if(g!=="-")f*=-1}if(g)f-=e.getTimezoneOffset();f&&e.setTime(e.getTime()+f*6E4)}return e};d.toIsoString=function(e,c){var a=function(j){return j<10?"0"+j:j},f,g,h;c=c||{};f=[];g=c.zulu?"getUTC":"get";h="";if(c.selector!=="time"){h=e[g+"FullYear"]();h=["0000".substr((h+"").length)+h,a(e[g+"Month"]()+1),a(e[g+"Date"]())].join("-")}f.push(h);if(c.selector!=="date"){h=[a(e[g+"Hours"]()),a(e[g+"Minutes"]()),a(e[g+"Seconds"]())].join(":");
g=e[g+"Milliseconds"]();if(c.milliseconds)h+="."+(g<100?"0":"")+a(g);if(c.zulu)h+="Z";else if(c.selector!=="time"){e=e.getTimezoneOffset();c=Math.abs(e);h+=(e>0?"-":"+")+a(Math.floor(c/60))+":"+a(c%60)}f.push(h)}return f.join("T")};return d});var EXPORTED_SYMBOLS=["hex_md5"],hexcase=0,b64pad="";function hex_md5(b){return rstr2hex(rstr_md5(str2rstr_utf8(b)))}function b64_md5(b){return rstr2b64(rstr_md5(str2rstr_utf8(b)))}function any_md5(b,d){return rstr2any(rstr_md5(str2rstr_utf8(b)),d)}
function hex_hmac_md5(b,d){return rstr2hex(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)))}function b64_hmac_md5(b,d){return rstr2b64(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)))}function any_hmac_md5(b,d,e){return rstr2any(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)),e)}function md5_vm_test(){return hex_md5("abc").toLowerCase()=="900150983cd24fb0d6963f7d28e17f72"}function rstr_md5(b){return binl2rstr(binl_md5(rstr2binl(b),b.length*8))}
function rstr_hmac_md5(b,d){var e=rstr2binl(b);if(e.length>16)e=binl_md5(e,b.length*8);var c=Array(16);b=Array(16);for(var a=0;a<16;a++){c[a]=e[a]^909522486;b[a]=e[a]^1549556828}d=binl_md5(c.concat(rstr2binl(d)),512+d.length*8);return binl2rstr(binl_md5(b.concat(d),640))}function rstr2hex(b){for(var d=hexcase?"0123456789ABCDEF":"0123456789abcdef",e="",c,a=0;a<b.length;a++){c=b.charCodeAt(a);e+=d.charAt(c>>>4&15)+d.charAt(c&15)}return e}
function rstr2b64(b){for(var d="",e=b.length,c=0;c<e;c+=3)for(var a=b.charCodeAt(c)<<16|(c+1<e?b.charCodeAt(c+1)<<8:0)|(c+2<e?b.charCodeAt(c+2):0),f=0;f<4;f++)d+=c*8+f*6>b.length*8?b64pad:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>6*(3-f)&63);return d}
function rstr2any(b,d){var e=d.length,c,a,f,g,h,j=Array(Math.ceil(b.length/2));for(c=0;c<j.length;c++)j[c]=b.charCodeAt(c*2)<<8|b.charCodeAt(c*2+1);var k=Math.ceil(b.length*8/(Math.log(d.length)/Math.log(2)));b=Array(k);for(a=0;a<k;a++){h=Array();for(c=g=0;c<j.length;c++){g=(g<<16)+j[c];f=Math.floor(g/e);g-=f*e;if(h.length>0||f>0)h[h.length]=f}b[a]=g;j=h}e="";for(c=b.length-1;c>=0;c--)e+=d.charAt(b[c]);return e}
function str2rstr_utf8(b){for(var d="",e=-1,c,a;++e<b.length;){c=b.charCodeAt(e);a=e+1<b.length?b.charCodeAt(e+1):0;if(55296<=c&&c<=56319&&56320<=a&&a<=57343){c=65536+((c&1023)<<10)+(a&1023);e++}if(c<=127)d+=String.fromCharCode(c);else if(c<=2047)d+=String.fromCharCode(192|c>>>6&31,128|c&63);else if(c<=65535)d+=String.fromCharCode(224|c>>>12&15,128|c>>>6&63,128|c&63);else if(c<=2097151)d+=String.fromCharCode(240|c>>>18&7,128|c>>>12&63,128|c>>>6&63,128|c&63)}return d}
function str2rstr_utf16le(b){for(var d="",e=0;e<b.length;e++)d+=String.fromCharCode(b.charCodeAt(e)&255,b.charCodeAt(e)>>>8&255);return d}function str2rstr_utf16be(b){for(var d="",e=0;e<b.length;e++)d+=String.fromCharCode(b.charCodeAt(e)>>>8&255,b.charCodeAt(e)&255);return d}function rstr2binl(b){for(var d=Array(b.length>>2),e=0;e<d.length;e++)d[e]=0;for(e=0;e<b.length*8;e+=8)d[e>>5]|=(b.charCodeAt(e/8)&255)<<e%32;return d}
function binl2rstr(b){for(var d="",e=0;e<b.length*32;e+=8)d+=String.fromCharCode(b[e>>5]>>>e%32&255);return d}
function binl_md5(b,d){b[d>>5]|=128<<d%32;b[(d+64>>>9<<4)+14]=d;d=1732584193;for(var e=-271733879,c=-1732584194,a=271733878,f=0;f<b.length;f+=16){var g=d,h=e,j=c,k=a;d=md5_ff(d,e,c,a,b[f+0],7,-680876936);a=md5_ff(a,d,e,c,b[f+1],12,-389564586);c=md5_ff(c,a,d,e,b[f+2],17,606105819);e=md5_ff(e,c,a,d,b[f+3],22,-1044525330);d=md5_ff(d,e,c,a,b[f+4],7,-176418897);a=md5_ff(a,d,e,c,b[f+5],12,1200080426);c=md5_ff(c,a,d,e,b[f+6],17,-1473231341);e=md5_ff(e,c,a,d,b[f+7],22,-45705983);d=md5_ff(d,e,c,a,b[f+8],7,
1770035416);a=md5_ff(a,d,e,c,b[f+9],12,-1958414417);c=md5_ff(c,a,d,e,b[f+10],17,-42063);e=md5_ff(e,c,a,d,b[f+11],22,-1990404162);d=md5_ff(d,e,c,a,b[f+12],7,1804603682);a=md5_ff(a,d,e,c,b[f+13],12,-40341101);c=md5_ff(c,a,d,e,b[f+14],17,-1502002290);e=md5_ff(e,c,a,d,b[f+15],22,1236535329);d=md5_gg(d,e,c,a,b[f+1],5,-165796510);a=md5_gg(a,d,e,c,b[f+6],9,-1069501632);c=md5_gg(c,a,d,e,b[f+11],14,643717713);e=md5_gg(e,c,a,d,b[f+0],20,-373897302);d=md5_gg(d,e,c,a,b[f+5],5,-701558691);a=md5_gg(a,d,e,c,b[f+
10],9,38016083);c=md5_gg(c,a,d,e,b[f+15],14,-660478335);e=md5_gg(e,c,a,d,b[f+4],20,-405537848);d=md5_gg(d,e,c,a,b[f+9],5,568446438);a=md5_gg(a,d,e,c,b[f+14],9,-1019803690);c=md5_gg(c,a,d,e,b[f+3],14,-187363961);e=md5_gg(e,c,a,d,b[f+8],20,1163531501);d=md5_gg(d,e,c,a,b[f+13],5,-1444681467);a=md5_gg(a,d,e,c,b[f+2],9,-51403784);c=md5_gg(c,a,d,e,b[f+7],14,1735328473);e=md5_gg(e,c,a,d,b[f+12],20,-1926607734);d=md5_hh(d,e,c,a,b[f+5],4,-378558);a=md5_hh(a,d,e,c,b[f+8],11,-2022574463);c=md5_hh(c,a,d,e,b[f+
11],16,1839030562);e=md5_hh(e,c,a,d,b[f+14],23,-35309556);d=md5_hh(d,e,c,a,b[f+1],4,-1530992060);a=md5_hh(a,d,e,c,b[f+4],11,1272893353);c=md5_hh(c,a,d,e,b[f+7],16,-155497632);e=md5_hh(e,c,a,d,b[f+10],23,-1094730640);d=md5_hh(d,e,c,a,b[f+13],4,681279174);a=md5_hh(a,d,e,c,b[f+0],11,-358537222);c=md5_hh(c,a,d,e,b[f+3],16,-722521979);e=md5_hh(e,c,a,d,b[f+6],23,76029189);d=md5_hh(d,e,c,a,b[f+9],4,-640364487);a=md5_hh(a,d,e,c,b[f+12],11,-421815835);c=md5_hh(c,a,d,e,b[f+15],16,530742520);e=md5_hh(e,c,a,
d,b[f+2],23,-995338651);d=md5_ii(d,e,c,a,b[f+0],6,-198630844);a=md5_ii(a,d,e,c,b[f+7],10,1126891415);c=md5_ii(c,a,d,e,b[f+14],15,-1416354905);e=md5_ii(e,c,a,d,b[f+5],21,-57434055);d=md5_ii(d,e,c,a,b[f+12],6,1700485571);a=md5_ii(a,d,e,c,b[f+3],10,-1894986606);c=md5_ii(c,a,d,e,b[f+10],15,-1051523);e=md5_ii(e,c,a,d,b[f+1],21,-2054922799);d=md5_ii(d,e,c,a,b[f+8],6,1873313359);a=md5_ii(a,d,e,c,b[f+15],10,-30611744);c=md5_ii(c,a,d,e,b[f+6],15,-1560198380);e=md5_ii(e,c,a,d,b[f+13],21,1309151649);d=md5_ii(d,
e,c,a,b[f+4],6,-145523070);a=md5_ii(a,d,e,c,b[f+11],10,-1120210379);c=md5_ii(c,a,d,e,b[f+2],15,718787259);e=md5_ii(e,c,a,d,b[f+9],21,-343485551);d=safe_add(d,g);e=safe_add(e,h);c=safe_add(c,j);a=safe_add(a,k)}return Array(d,e,c,a)}function md5_cmn(b,d,e,c,a,f){return safe_add(bit_rol(safe_add(safe_add(d,b),safe_add(c,f)),a),e)}function md5_ff(b,d,e,c,a,f,g){return md5_cmn(d&e|~d&c,b,d,a,f,g)}function md5_gg(b,d,e,c,a,f,g){return md5_cmn(d&c|e&~c,b,d,a,f,g)}
function md5_hh(b,d,e,c,a,f,g){return md5_cmn(d^e^c,b,d,a,f,g)}function md5_ii(b,d,e,c,a,f,g){return md5_cmn(e^(d|~c),b,d,a,f,g)}function safe_add(b,d){var e=(b&65535)+(d&65535);return(b>>16)+(d>>16)+(e>>16)<<16|e&65535}function bit_rol(b,d){return b<<d|b>>>32-d}define("md5",function(){});
define("rdapi",["require","jquery","blade/object","blade/jig","friendly","isoDate","md5"],function(b,d,e,c,a,f){function g(v){if(typeof v==="string")v={template:v};else if(v.templateId)v.template=c.cache(v.templateId);if(!("attachData"in v))v.attachData=l.attachTemplateData;if(v.emptyTemplateId)v.emptyTemplate=c.cache(v.emptyTemplateId);return v}function h(){var v=s.exec(document.cookie);return v&&v[1]?v[1]:null}function j(v,A){A.url=F.baseUrl+F.apiPath+v;e.mixin(A,{limit:30,message_limit:3,dataType:"json",
error:function(D,K,O){throw O;}});var w=A.success,x=h();A.success=function(D){D&&D.contacts&&e.mixin(z,D.contacts,true);return w?w.apply(null,arguments):D};if(x)A.beforeSend=function(D){D.setRequestHeader(o,x)};d.ajax(A)}function k(v,A){var w=A.forId?document.getElementById(A.forId):null;if(w)w.innerHTML=v;A.onTemplateDone&&A.onTemplateDone(v);d(document).trigger("rdapi-done",w)}var l,o="X-CSRF",s=/csrf=([^\; ]+)/,z={},C={contact:function(v){return v.iid&&v.domain?z[v.iid]||{}:v},contactPhotoUrl:function(v){var A=
"i/face2.png",w,x;v=C.contact(v);if((w=v.photos)&&w.length){A=w[0].value;w.forEach(function(D){if(D.primary)A=D.value})}else if(v.emails&&v.emails.length){x=v.emails[0].value;v.emails.forEach(function(D){if(D.primary)x=D.value});A="http://www.gravatar.com/avatar/"+hex_md5(x)+"?s=24 &d=identicon"}return A},allMessages:function(v){return[v.topic].concat(v.messages||[])},friendlyDate:function(v){return a.date(f(v)).friendly},htmlBody:function(v){return c.htmlEscape(v).replace(/\n/g,"<br>")}},F={baseUrl:"/",
apiPath:"api/",saveTemplateData:true};c.addFn(C);l=function(v,A){A=g(A);e.mixin(A,{success:function(w){var x=A.template,D=A.emptyTemplate,K="";if(A.forId&&x){if(A.prop)w=c.getObject(A.prop,w,A);if(b.isArray(w))if(w.length)w.forEach(function(O){K+=c(x,O,A)});else K+=c(D,w,A);else K+=c(!w?D:x,w,A);k(K,A)}},error:function(w,x,D){if(A.emptyTemplate){w=c(A.emptyTemplate,D,A);k(w,A)}else throw D;}});j(v,A)};l.contactPhotoUrl=C.contactPhotoUrl;l.attachTemplateData=false;b.ready(function(){var v=[];c.parse({onBeforeParse:function(A){var w=
A.id,x=A.getAttribute("data-rdapi"),D=A.getAttribute("data-rdfor"),K=A.getAttribute("data-rdprop");x&&v.push({templateId:w,api:x,forId:D,prop:K});["data-rdapi","data-rdprop","data-rdfor"].forEach(function(O){A.removeAttribute(O)})}});v.forEach(function(A){l(A.api,A)})});return l});define("storage",[],function(){function b(){return d}var d=localStorage,e="localStorage";try{d.tempVar="temp";delete d.tempVar}catch(c){d={};e="memory"}b.type=e;return b});
define("dispatch",["jquery"],function(){var b=location.protocol+"//"+location.host;return{sub:function(d,e,c,a){c=c||window;a=a||b;var f=function(g){if(g.origin===a||g.origin==="chrome://browser")try{var h=JSON.parse(g.data),j=h.topic;j&&j===d&&e(h.data)}catch(k){}};c.addEventListener("message",f,false);return f},unsub:function(d,e){e=e||window;e.removeEventListener("message",d,false)},pub:function(d,e,c){c=c||window;c.postMessage(JSON.stringify({topic:d,data:e}),b)}}});
define("services",["blade/object","storage"],function(b,d){function e(h,j){if(h){this.name=h;this.type=h.replace(/\s/g,"").toLowerCase();this.tabName=this.type+"Tab";this.icon="i/"+this.type+"Icon.png";this.features={counter:false,direct:false,subject:false};b.mixin(this,j,true)}}function c(){e.constructor.apply(this,arguments);this.features.direct=true;this.features.subject=true}var a=parseFloat(navigator.userAgent.split("Firefox/")[1])>=4;d=d();var f,g;e.constructor=e;e.prototype={clearCache:function(h){delete h[this.type+
"Contacts"]},getContacts:function(h){if(h[this.type+"Contacts"])return JSON.parse(h[this.type+"Contacts"]);return null},setContacts:function(h,j){h[this.type+"Contacts"]=JSON.stringify(j)},get36FormattedContacts:function(){return null}};c.prototype=new e;c.constructor=c;c.prototype.validate=function(h){if(!h.to||!h.to.trim())return false;return true};c.prototype.get36FormattedContacts=function(h){var j=[];h.forEach(function(k){k.emails&&k.emails.length&&k.emails.forEach(function(l){j.push({displayName:k.displayName?
k.displayName:l.value,email:l.value})})});return j};c.prototype.overlays={Contacts:"ContactsEmail"};f={domains:{"twitter.com":new e("Twitter",{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"public",name:"public"},{type:"direct",name:"direct message",showTo:true,toLabel:"type in name of recipient"}],textLimit:140,shorten:true,serviceUrl:"http://twitter.com",revokeUrl:"http://twitter.com/settings/connections",signOutUrl:"http://twitter.com/logout",accountLink:function(h){return"http://twitter.com/"+
h.username},forceLogin:{name:"force_login",value:true},overlays:{Contacts:"ContactsTwitter"}}),"facebook.com":new e("Facebook",{features:{direct:true,subject:false,counter:true,medium:true},shareTypes:[{type:"wall",name:"my wall"},{type:"groupWall",name:"group wall",showTo:true,toLabel:"type in the name of the group"}],textLimit:420,serviceUrl:"http://facebook.com",revokeUrl:"http://www.facebook.com/editapps.php?v=allowed",signOutUrl:"http://facebook.com",accountLink:function(h){return"http://www.facebook.com/profile.php?id="+
h.userid},overlays:{"widgets/AccountPanel":"widgets/AccountPanelFaceBook"}}),"google.com":new c("Gmail",{shareTypes:[{type:"direct",name:"direct",showTo:true}],serviceUrl:"https://mail.google.com",revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(h){return"http://google.com/profiles/"+h.username},forceLogin:{name:"pape_max_auth_age",value:0}}),"googleapps.com":new c("Google Apps",{shareTypes:[{type:"direct",name:"direct",
showTo:true}],icon:"i/gmailIcon.png",serviceUrl:"https://mail.google.com",revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(h){return"http://google.com/profiles/"+h.username},forceLogin:{name:"pape_max_auth_age",value:0}}),"yahoo.com":new c("Yahoo",{shareTypes:[{type:"direct",name:"direct",showTo:true}],name:"Yahoo!",serviceUrl:"http://mail.yahoo.com",revokeUrl:"https://api.login.yahoo.com/WSLogin/V1/unlink",signOutUrl:"https://login.yahoo.com/config/login?logout=1",
accountLink:function(h){return"http://profiles.yahoo.com/"+h.username}}),"linkedin.com":new e("LinkedIn",{isNew:true,features:{direct:true,subject:true,counter:false},shareTypes:[{type:"public",name:"anyone"},{type:"myConnections",name:"connections only",specialTo:"connections-only"},{type:"contact",name:"send message",showTo:true,toLabel:"type in the name of the contact"}],serviceUrl:"http://linkedin.com",revokeUrl:"http://linkedin.com/settings/connections",signOutUrl:"https://www.linkedin.com/secure/login?session_full_logout=&trk=hb_signout",
accountLink:function(h){return"http://linkedin.com/"+h.username},overlays:{"widgets/AccountPanel":"widgets/AccountPanelLinkedIn"}})},domainList:[],svcBaseProto:e.prototype};for(g in f.domains)if(f.domains.hasOwnProperty(g)){f.domainList.push(g);if(a){delete d[f.domains[g].type+"Contacts"];delete d.contactsModelVersion}}return f});
define("accounts",["storage","dispatch","rdapi","services"],function(b,d,e,c){function a(l,o,s,z){return l.domain===o&&(s&&l.userid===s||z&&l.username===z)}function f(l){if(l)l=JSON.parse(l);return l}function g(l,o){return k.accounts(l,o)}function h(){location.reload()}var j=b(),k;k={localStorage:{accounts:function(l,o){var s=f(j.accountCache)||[],z=f(j.serviceCache);if(z){z=z||[];l&&l(s,z)}else k.fetch(l,o)},update:function(l){var o=f(j.accountCache)||[],s=f(j.serviceCache),z=false,C,F,v;C=l.profile;
for(F=0;F<o.length;F++){v=o[F].accounts[0];if(a(v,l.domain,l.userid,l.username)){o[F]=C;z=true;break}}z||o.push(C);j.accountCache=JSON.stringify(o);if(s){z=false;for(o=0;o<s.length;o++)if(a(s[o],l.domain,l.userid,l.username)){s[o]=l;z=true;break}}else s=[];z||s.push(l);j.serviceCache=JSON.stringify(s);k.changed()},fetch:function(l,o){e("account/get/full",{success:function(s){if(s.error)s=[];j.serviceCache=JSON.stringify(s);var z=[],C,F;for(F=0;F<s.length;F++){z.push(s[F].profile);C=c.domains[s[F].domain];
C.clearCache(j)}j.accountCache=JSON.stringify(z);l&&l(z,s)},error:o||function(){}})},remove:function(l,o,s){var z=f(j.accountCache),C=f(j.serviceCache),F,v;if(C){for(F=0;v=C[F];F++)if(a(v,l,o,s)){C.splice(F,1);break}j.serviceCache=JSON.stringify(C)}if(z){for(F=0;F<z.length;F++){v=z[F].accounts;for(C=0;C<v.length;C++)if(a(v[C],l,o,s)){z.splice(F,1);break}}j.accountCache=JSON.stringify(z)}c.domains[l].clearCache(j);k.clearData(l,o,s);k.changed()},setData:function(l,o,s,z,C){l=[l,o,s].join("|")+"Data";
o=f(j[l])||{};if(C===undefined||C===null)delete o[z];else o[z]=C;j[l]=JSON.stringify(o);return C},getData:function(l,o,s,z){l=[l,o,s].join("|")+"Data";return(l=f(j[l])||{})?l[z]:null},clearData:function(l,o,s){l=[l,o,s].join("|")+"Data";delete j[l]},getService:function(l,o,s){var z=f(j.serviceCache),C,F;if(z)for(C=0;F=z[C];C++)if(a(F,l,o,s))return F;return null},changed:function(){j.accountChanged=(new Date).getTime();opener&&!opener.closed&&d.pub("accountsChanged",null,opener);d.pub("accountsChanged")},
onChange:function(l){var o=j.accountChanged;window.addEventListener("storage",function(){j.accountChanged!==o&&l()},false);d.sub("accountsChanged",l)}},memory:{accounts:function(){},changed:function(){j.accountChanged=(new Date).getTime();opener&&d.pub("accountsChanged",null,opener);d.pub("accountsChanged")},onChange:function(l){d.sub("accountsChanged",l)}}}[b.type];g.update=function(l){k.update(l)};g.remove=function(l,o,s){k.remove(l,o,s)};g.fetch=function(l,o){k.fetch(l,o)};g.getService=function(l,
o,s){return k.getService(l,o,s)};g.clear=function(){delete j.accountCache;delete j.serviceCache};g.setData=function(l,o,s,z,C){return k.setData(l,o,s,z,C)};g.getData=function(l,o,s,z){return k.getData(l,o,s,z)};g.clearData=function(l,o,s){return k.clearData(l,o,s)};g.changed=function(){return k.changed()};g.onChange=function(l){return k.onChange(l||h)};return g});
define("oauth",["accounts"],function(b){var d,e,c=0;window.addEventListener("message",function(a){var f;try{f=JSON.parse(a.data)}catch(g){return}if(f.target){if(f.target==="oauth_success"&&f.account){a=true;b.update(f.account)}else a=false;e=null;if(d){d(a);d=null}}},false);return function(a,f,g){if(g)d=g;g=location.protocol+"//"+location.host+"/0.3.3/auth.html";var h=(new Date).getTime();if(e&&e.closed)e=null;if(h>c+4E3){c=h;a=g+"?domain="+a+(f?"&forceLogin=1":"");try{e=window.open(a,"ffshareOAuth",
"dialog=yes, modal=yes, width=900, height=500, scrollbars=yes");e.focus()}catch(j){window.location=a+"&end_point_success="+encodeURI(window.location)}}else e&&e.focus()}});define("blade/array",[],function(){var b=Object.prototype.toString,d=Array.prototype.slice;return{is:function(e){return b.call(e)==="[object Array]"},to:function(){return[].concat(d.call(arguments,0))}}});
define("blade/url",["./array"],function(b){var d=Object.prototype.toString;return{objectToQuery:function(e){var c=encodeURIComponent,a=[],f={},g,h,j,k;for(g in e)if(e.hasOwnProperty(g)){h=e[g];if(h!==f[g]){j=c(g)+"=";if(b.is(h))for(k=0;k<h.length;k++)a.push(j+c(h[k]));else a.push(j+c(h))}}return a.join("&")},queryToObject:function(e){var c={};e=e.split("&");var a=decodeURIComponent,f,g,h;e.forEach(function(j){if(j.length){f=j.split("=");g=a(f.shift());h=a(f.join("="));if(typeof c[g]==="string")c[g]=
[c[g]];if(d.call(c[g])==="[object Array]")c[g].push(h);else c[g]=h}});return c}}});
define("placeholder",["jquery"],function(b){function d(a){var f=!("placeholder"in a),g=a.getAttribute("placeholder"),h=a.value.trim();if(!h||h===g){if(f){b(a).addClass("placeholder");a.value=g;if(g==="password"&&a.type==="password")a.type="text"}}else b(a).removeClass("placeholder")}function e(a){a=a.target;var f=a.getAttribute("placeholder");if(a.value===f){if(!("placeholder"in a)){a.value="";if(f==="password"&&a.type==="text")a.type="password"}b(a).removeClass("placeholder")}}function c(a){d(a.target)}
return function(a){b('input[type="text"], input[type="password"], textarea',a).each(function(f,g){if(g.getAttribute("data-rdwPlaceholder")!=="set"){b(g).focus(e).blur(c);g.setAttribute("data-rdwPlaceholder","set")}d(g)})}});
define("TextCounter",["jquery","blade/object","blade/fn"],function(b,d,e){return d(null,null,{init:function(c,a,f){this.dom=b(c);this.domPlaceholderText=this.dom[0].getAttribute("placeholder")||"";this.countDom=b(a);this.limit=f;this.dom.bind("keyup",e.bind(this,"checkCount"));this.checkCount()},checkCount:function(){var c=this.dom[0].value;if(c.trim()===this.domPlaceholderText)c="";c=this.limit-c.length;c<0?this.countDom.addClass("TextCountOver"):this.countDom.removeClass("TextCountOver");this.countDom.text(c===
this.limit?"":c)},updateLimit:function(c){this.limit=c;this.checkCount()},isOver:function(){return this.dom[0].value.length>this.limit}})});
(function(b,d){function e(c){return!b(c).parents().andSelf().filter(function(){return b.curCSS(this,"visibility")==="hidden"||b.expr.filters.hidden(this)}).length}b.ui=b.ui||{};if(!b.ui.version){b.extend(b.ui,{version:"1.8.6",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});b.fn.extend({_focus:b.fn.focus,focus:function(c,a){return typeof c==="number"?this.each(function(){var f=this;setTimeout(function(){b(f).focus();a&&a.call(f)},c)}):this._focus.apply(this,arguments)},scrollParent:function(){var c;c=b.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.curCSS(this,
"position",1))&&/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!c.length?b(document):c},zIndex:function(c){if(c!==d)return this.css("zIndex",c);if(this.length){c=b(this[0]);for(var a;c.length&&c[0]!==document;){a=c.css("position");
if(a==="absolute"||a==="relative"||a==="fixed"){a=parseInt(c.css("zIndex"),10);if(!isNaN(a)&&a!==0)return a}c=c.parent()}}return 0},disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(c){c.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});b.each(["Width","Height"],function(c,a){function f(k,l,o,s){b.each(g,function(){l-=parseFloat(b.curCSS(k,"padding"+this,true))||0;if(o)l-=parseFloat(b.curCSS(k,
"border"+this+"Width",true))||0;if(s)l-=parseFloat(b.curCSS(k,"margin"+this,true))||0});return l}var g=a==="Width"?["Left","Right"]:["Top","Bottom"],h=a.toLowerCase(),j={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+a]=function(k){if(k===d)return j["inner"+a].call(this);return this.each(function(){b(this).css(h,f(this,k)+"px")})};b.fn["outer"+a]=function(k,l){if(typeof k!=="number")return j["outer"+a].call(this,k);return this.each(function(){b(this).css(h,
f(this,k,true,l)+"px")})}});b.extend(b.expr[":"],{data:function(c,a,f){return!!b.data(c,f[3])},focusable:function(c){var a=c.nodeName.toLowerCase(),f=b.attr(c,"tabindex");if("area"===a){a=c.parentNode;f=a.name;if(!c.href||!f||a.nodeName.toLowerCase()!=="map")return false;c=b("img[usemap=#"+f+"]")[0];return!!c&&e(c)}return(/input|select|textarea|button|object/.test(a)?!c.disabled:"a"==a?c.href||!isNaN(f):!isNaN(f))&&e(c)},tabbable:function(c){var a=b.attr(c,"tabindex");return(isNaN(a)||a>=0)&&b(c).is(":focusable")}});
b(function(){var c=document.body,a=c.appendChild(a=document.createElement("div"));b.extend(a.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});b.support.minHeight=a.offsetHeight===100;b.support.selectstart="onselectstart"in a;c.removeChild(a).style.display="none"});b.extend(b.ui,{plugin:{add:function(c,a,f){c=b.ui[c].prototype;for(var g in f){c.plugins[g]=c.plugins[g]||[];c.plugins[g].push([a,f[g]])}},call:function(c,a,f){if((a=c.plugins[a])&&c.element[0].parentNode)for(var g=0;g<a.length;g++)c.options[a[g][0]]&&
a[g][1].apply(c.element,f)}},contains:function(c,a){return document.compareDocumentPosition?c.compareDocumentPosition(a)&16:c!==a&&c.contains(a)},hasScroll:function(c,a){if(b(c).css("overflow")==="hidden")return false;a=a&&a==="left"?"scrollLeft":"scrollTop";var f=false;if(c[a]>0)return true;c[a]=1;f=c[a]>0;c[a]=0;return f},isOverAxis:function(c,a,f){return c>a&&c<a+f},isOver:function(c,a,f,g,h,j){return b.ui.isOverAxis(c,f,h)&&b.ui.isOverAxis(a,g,j)}})}})(jQuery);
(function(b,d){if(b.cleanData){var e=b.cleanData;b.cleanData=function(a){for(var f=0,g;(g=a[f])!=null;f++)b(g).triggerHandler("remove");e(a)}}else{var c=b.fn.remove;b.fn.remove=function(a,f){return this.each(function(){if(!f)if(!a||b.filter(a,[this]).length)b("*",this).add([this]).each(function(){b(this).triggerHandler("remove")});return c.call(b(this),a,f)})}}b.widget=function(a,f,g){var h=a.split(".")[0],j;a=a.split(".")[1];j=h+"-"+a;if(!g){g=f;f=b.Widget}b.expr[":"][j]=function(k){return!!b.data(k,
a)};b[h]=b[h]||{};b[h][a]=function(k,l){arguments.length&&this._createWidget(k,l)};f=new f;f.options=b.extend(true,{},f.options);b[h][a].prototype=b.extend(true,f,{namespace:h,widgetName:a,widgetEventPrefix:b[h][a].prototype.widgetEventPrefix||a,widgetBaseClass:j},g);b.widget.bridge(a,b[h][a])};b.widget.bridge=function(a,f){b.fn[a]=function(g){var h=typeof g==="string",j=Array.prototype.slice.call(arguments,1),k=this;g=!h&&j.length?b.extend.apply(null,[true,g].concat(j)):g;if(h&&g.charAt(0)==="_")return k;
h?this.each(function(){var l=b.data(this,a),o=l&&b.isFunction(l[g])?l[g].apply(l,j):l;if(o!==l&&o!==d){k=o;return false}}):this.each(function(){var l=b.data(this,a);l?l.option(g||{})._init():b.data(this,a,new f(g,this))});return k}};b.Widget=function(a,f){arguments.length&&this._createWidget(a,f)};b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(a,f){b.data(f,this.widgetName,this);this.element=b(f);this.options=b.extend(true,{},this.options,
this._getCreateOptions(),a);var g=this;this.element.bind("remove."+this.widgetName,function(){g.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return b.metadata&&b.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(a,f){var g=a;if(arguments.length===0)return b.extend({},this.options);if(typeof a==="string"){if(f===d)return this.options[a];g={};g[a]=f}this._setOptions(g);return this},_setOptions:function(a){var f=this;b.each(a,function(g,h){f._setOption(g,h)});return this},_setOption:function(a,f){this.options[a]=f;if(a==="disabled")this.widget()[f?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",f);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(a,f,g){var h=this.options[a];f=b.Event(f);f.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase();g=g||{};if(f.originalEvent){a=b.event.props.length;for(var j;a;){j=b.event.props[--a];f[j]=f.originalEvent[j]}}this.element.trigger(f,g);return!(b.isFunction(h)&&h.call(this.element[0],f,g)===false||f.isDefaultPrevented())}}})(jQuery);
(function(b,d){function e(){return++a}function c(){return++f}var a=0,f=0;b.widget("ui.tabs",{options:{add:null,ajaxOptions:null,cache:false,cookie:null,collapsible:false,disable:null,disabled:[],enable:null,event:"click",fx:null,idPrefix:"ui-tabs-",load:null,panelTemplate:"<div></div>",remove:null,select:null,show:null,spinner:"<em>Loading&#8230;</em>",tabTemplate:"<li><a href='#{href}'><span>#{label}</span></a></li>"},_create:function(){this._tabify(true)},_setOption:function(g,h){if(g=="selected")this.options.collapsible&&
h==this.options.selected||this.select(h);else{this.options[g]=h;this._tabify()}},_tabId:function(g){return g.title&&g.title.replace(/\s/g,"_").replace(/[^\w\u00c0-\uFFFF-]/g,"")||this.options.idPrefix+e()},_sanitizeSelector:function(g){return g.replace(/:/g,"\\:")},_cookie:function(){var g=this.cookie||(this.cookie=this.options.cookie.name||"ui-tabs-"+c());return b.cookie.apply(null,[g].concat(b.makeArray(arguments)))},_ui:function(g,h){return{tab:g,panel:h,index:this.anchors.index(g)}},_cleanup:function(){this.lis.filter(".ui-state-processing").removeClass("ui-state-processing").find("span:data(label.tabs)").each(function(){var g=
b(this);g.html(g.data("label.tabs")).removeData("label.tabs")})},_tabify:function(g){function h(w,x){w.css("display","");!b.support.opacity&&x.opacity&&w[0].style.removeAttribute("filter")}var j=this,k=this.options,l=/^#.+/;this.list=this.element.find("ol,ul").eq(0);this.lis=b(" > li:has(a[href])",this.list);this.anchors=this.lis.map(function(){return b("a",this)[0]});this.panels=b([]);this.anchors.each(function(w,x){var D=b(x).attr("href"),K=D.split("#")[0],O;if(K&&(K===location.toString().split("#")[0]||
(O=b("base")[0])&&K===O.href)){D=x.hash;x.href=D}if(l.test(D))j.panels=j.panels.add(j._sanitizeSelector(D));else if(D&&D!=="#"){b.data(x,"href.tabs",D);b.data(x,"load.tabs",D.replace(/#.*$/,""));D=j._tabId(x);x.href="#"+D;x=b("#"+D);if(!x.length){x=b(k.panelTemplate).attr("id",D).addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").insertAfter(j.panels[w-1]||j.list);x.data("destroy.tabs",true)}j.panels=j.panels.add(x)}else k.disabled.push(w)});if(g){this.element.addClass("ui-tabs ui-widget ui-widget-content ui-corner-all");
this.list.addClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.lis.addClass("ui-state-default ui-corner-top");this.panels.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom");if(k.selected===d){location.hash&&this.anchors.each(function(w,x){if(x.hash==location.hash){k.selected=w;return false}});if(typeof k.selected!=="number"&&k.cookie)k.selected=parseInt(j._cookie(),10);if(typeof k.selected!=="number"&&this.lis.filter(".ui-tabs-selected").length)k.selected=
this.lis.index(this.lis.filter(".ui-tabs-selected"));k.selected=k.selected||(this.lis.length?0:-1)}else if(k.selected===null)k.selected=-1;k.selected=k.selected>=0&&this.anchors[k.selected]||k.selected<0?k.selected:0;k.disabled=b.unique(k.disabled.concat(b.map(this.lis.filter(".ui-state-disabled"),function(w){return j.lis.index(w)}))).sort();b.inArray(k.selected,k.disabled)!=-1&&k.disabled.splice(b.inArray(k.selected,k.disabled),1);this.panels.addClass("ui-tabs-hide");this.lis.removeClass("ui-tabs-selected ui-state-active");
if(k.selected>=0&&this.anchors.length){b(j._sanitizeSelector(j.anchors[k.selected].hash)).removeClass("ui-tabs-hide");this.lis.eq(k.selected).addClass("ui-tabs-selected ui-state-active");j.element.queue("tabs",function(){j._trigger("show",null,j._ui(j.anchors[k.selected],b(j._sanitizeSelector(j.anchors[k.selected].hash))))});this.load(k.selected)}b(window).bind("unload",function(){j.lis.add(j.anchors).unbind(".tabs");j.lis=j.anchors=j.panels=null})}else k.selected=this.lis.index(this.lis.filter(".ui-tabs-selected"));
this.element[k.collapsible?"addClass":"removeClass"]("ui-tabs-collapsible");k.cookie&&this._cookie(k.selected,k.cookie);g=0;for(var o;o=this.lis[g];g++)b(o)[b.inArray(g,k.disabled)!=-1&&!b(o).hasClass("ui-tabs-selected")?"addClass":"removeClass"]("ui-state-disabled");k.cache===false&&this.anchors.removeData("cache.tabs");this.lis.add(this.anchors).unbind(".tabs");if(k.event!=="mouseover"){var s=function(w,x){x.is(":not(.ui-state-disabled)")&&x.addClass("ui-state-"+w)},z=function(w,x){x.removeClass("ui-state-"+
w)};this.lis.bind("mouseover.tabs",function(){s("hover",b(this))});this.lis.bind("mouseout.tabs",function(){z("hover",b(this))});this.anchors.bind("focus.tabs",function(){s("focus",b(this).closest("li"))});this.anchors.bind("blur.tabs",function(){z("focus",b(this).closest("li"))})}var C,F;if(k.fx)if(b.isArray(k.fx)){C=k.fx[0];F=k.fx[1]}else C=F=k.fx;var v=F?function(w,x){b(w).closest("li").addClass("ui-tabs-selected ui-state-active");x.hide().removeClass("ui-tabs-hide").animate(F,F.duration||"normal",
function(){h(x,F);j._trigger("show",null,j._ui(w,x[0]))})}:function(w,x){b(w).closest("li").addClass("ui-tabs-selected ui-state-active");x.removeClass("ui-tabs-hide");j._trigger("show",null,j._ui(w,x[0]))},A=C?function(w,x){x.animate(C,C.duration||"normal",function(){j.lis.removeClass("ui-tabs-selected ui-state-active");x.addClass("ui-tabs-hide");h(x,C);j.element.dequeue("tabs")})}:function(w,x){j.lis.removeClass("ui-tabs-selected ui-state-active");x.addClass("ui-tabs-hide");j.element.dequeue("tabs")};
this.anchors.bind(k.event+".tabs",function(){var w=this,x=b(w).closest("li"),D=j.panels.filter(":not(.ui-tabs-hide)"),K=b(j._sanitizeSelector(w.hash));if(x.hasClass("ui-tabs-selected")&&!k.collapsible||x.hasClass("ui-state-disabled")||x.hasClass("ui-state-processing")||j.panels.filter(":animated").length||j._trigger("select",null,j._ui(this,K[0]))===false){this.blur();return false}k.selected=j.anchors.index(this);j.abort();if(k.collapsible)if(x.hasClass("ui-tabs-selected")){k.selected=-1;k.cookie&&
j._cookie(k.selected,k.cookie);j.element.queue("tabs",function(){A(w,D)}).dequeue("tabs");this.blur();return false}else if(!D.length){k.cookie&&j._cookie(k.selected,k.cookie);j.element.queue("tabs",function(){v(w,K)});j.load(j.anchors.index(this));this.blur();return false}k.cookie&&j._cookie(k.selected,k.cookie);if(K.length){D.length&&j.element.queue("tabs",function(){A(w,D)});j.element.queue("tabs",function(){v(w,K)});j.load(j.anchors.index(this))}else throw"jQuery UI Tabs: Mismatching fragment identifier.";
b.browser.msie&&this.blur()});this.anchors.bind("click.tabs",function(){return false})},_getIndex:function(g){if(typeof g=="string")g=this.anchors.index(this.anchors.filter("[href$="+g+"]"));return g},destroy:function(){var g=this.options;this.abort();this.element.unbind(".tabs").removeClass("ui-tabs ui-widget ui-widget-content ui-corner-all ui-tabs-collapsible").removeData("tabs");this.list.removeClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.anchors.each(function(){var h=
b.data(this,"href.tabs");if(h)this.href=h;var j=b(this).unbind(".tabs");b.each(["href","load","cache"],function(k,l){j.removeData(l+".tabs")})});this.lis.unbind(".tabs").add(this.panels).each(function(){b.data(this,"destroy.tabs")?b(this).remove():b(this).removeClass("ui-state-default ui-corner-top ui-tabs-selected ui-state-active ui-state-hover ui-state-focus ui-state-disabled ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide")});g.cookie&&this._cookie(null,g.cookie);return this},add:function(g,
h,j){if(j===d)j=this.anchors.length;var k=this,l=this.options;h=b(l.tabTemplate.replace(/#\{href\}/g,g).replace(/#\{label\}/g,h));g=!g.indexOf("#")?g.replace("#",""):this._tabId(b("a",h)[0]);h.addClass("ui-state-default ui-corner-top").data("destroy.tabs",true);var o=b("#"+g);o.length||(o=b(l.panelTemplate).attr("id",g).data("destroy.tabs",true));o.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide");if(j>=this.lis.length){h.appendTo(this.list);o.appendTo(this.list[0].parentNode)}else{h.insertBefore(this.lis[j]);
o.insertBefore(this.panels[j])}l.disabled=b.map(l.disabled,function(s){return s>=j?++s:s});this._tabify();if(this.anchors.length==1){l.selected=0;h.addClass("ui-tabs-selected ui-state-active");o.removeClass("ui-tabs-hide");this.element.queue("tabs",function(){k._trigger("show",null,k._ui(k.anchors[0],k.panels[0]))});this.load(0)}this._trigger("add",null,this._ui(this.anchors[j],this.panels[j]));return this},remove:function(g){g=this._getIndex(g);var h=this.options,j=this.lis.eq(g).remove(),k=this.panels.eq(g).remove();
if(j.hasClass("ui-tabs-selected")&&this.anchors.length>1)this.select(g+(g+1<this.anchors.length?1:-1));h.disabled=b.map(b.grep(h.disabled,function(l){return l!=g}),function(l){return l>=g?--l:l});this._tabify();this._trigger("remove",null,this._ui(j.find("a")[0],k[0]));return this},enable:function(g){g=this._getIndex(g);var h=this.options;if(b.inArray(g,h.disabled)!=-1){this.lis.eq(g).removeClass("ui-state-disabled");h.disabled=b.grep(h.disabled,function(j){return j!=g});this._trigger("enable",null,
this._ui(this.anchors[g],this.panels[g]));return this}},disable:function(g){g=this._getIndex(g);var h=this.options;if(g!=h.selected){this.lis.eq(g).addClass("ui-state-disabled");h.disabled.push(g);h.disabled.sort();this._trigger("disable",null,this._ui(this.anchors[g],this.panels[g]))}return this},select:function(g){g=this._getIndex(g);if(g==-1)if(this.options.collapsible&&this.options.selected!=-1)g=this.options.selected;else return this;this.anchors.eq(g).trigger(this.options.event+".tabs");return this},
load:function(g){g=this._getIndex(g);var h=this,j=this.options,k=this.anchors.eq(g)[0],l=b.data(k,"load.tabs");this.abort();if(!l||this.element.queue("tabs").length!==0&&b.data(k,"cache.tabs"))this.element.dequeue("tabs");else{this.lis.eq(g).addClass("ui-state-processing");if(j.spinner){var o=b("span",k);o.data("label.tabs",o.html()).html(j.spinner)}this.xhr=b.ajax(b.extend({},j.ajaxOptions,{url:l,success:function(s,z){b(h._sanitizeSelector(k.hash)).html(s);h._cleanup();j.cache&&b.data(k,"cache.tabs",
true);h._trigger("load",null,h._ui(h.anchors[g],h.panels[g]));try{j.ajaxOptions.success(s,z)}catch(C){}},error:function(s,z){h._cleanup();h._trigger("load",null,h._ui(h.anchors[g],h.panels[g]));try{j.ajaxOptions.error(s,z,g,k)}catch(C){}}}));h.element.dequeue("tabs");return this}},abort:function(){this.element.queue([]);this.panels.stop(false,true);this.element.queue("tabs",this.element.queue("tabs").splice(-2,2));if(this.xhr){this.xhr.abort();delete this.xhr}this._cleanup();return this},url:function(g,
h){this.anchors.eq(g).removeData("cache.tabs").data("load.tabs",h);return this},length:function(){return this.anchors.length}});b.extend(b.ui.tabs,{version:"1.8.6"});b.extend(b.ui.tabs.prototype,{rotation:null,rotate:function(g,h){var j=this,k=this.options,l=j._rotate||(j._rotate=function(o){clearTimeout(j.rotation);j.rotation=setTimeout(function(){var s=k.selected;j.select(++s<j.anchors.length?s:0)},g);o&&o.stopPropagation()});h=j._unrotate||(j._unrotate=!h?function(o){o.clientX&&j.rotate(null)}:
function(){t=k.selected;l()});if(g){this.element.bind("tabsshow",l);this.anchors.bind(k.event+".tabs",h);l()}else{clearTimeout(j.rotation);this.element.unbind("tabsshow",l);this.anchors.unbind(k.event+".tabs",h);delete this._rotate;delete this._unrotate}return this}})})(jQuery);define("jquery-ui-1.8.6.custom.min",function(){});
(function(b){var d=document.documentElement.style,e="textOverflow"in d||"OTextOverflow"in d,c=function(a,f){var g=0,h=[],j=function(k){var l=0,o;if(!(g>f))for(l=0;l<k.length;l+=1)if(k[l].nodeType===1){o=k[l].cloneNode(false);h[h.length-1].appendChild(o);h.push(o);j(k[l].childNodes);h.pop()}else if(k[l].nodeType===3){if(g+k[l].length<f)h[h.length-1].appendChild(k[l].cloneNode(false));else{o=k[l].cloneNode(false);o.textContent=b.trim(o.textContent.substring(0,f-g));h[h.length-1].appendChild(o)}g+=k[l].length}else h.appendChild(k[l].cloneNode(false))};
h.push(a.cloneNode(false));j(a.childNodes);return b(h.pop().childNodes)};b.extend(b.fn,{textOverflow:function(a,f){var g=a||"&#x2026;";return e?this:this.each(function(){var h=b(this),j=h.clone(),k=h.clone(),l=h.text(),o=h.width(),s=0,z=0,C=l.length,F=function(){if(o!==h.width()){h.replaceWith(k);h=k;k=h.clone();h.textOverflow(a,false);o=h.width()}};h.after(j.hide().css({position:"absolute",width:"auto",overflow:"visible","max-width":"inherit"}));if(j.width()>o){for(;s<C;){z=Math.floor(s+(C-s)/2);
j.empty().append(c(k.get(0),z)).append(g);if(j.width()<o)s=z+1;else C=z}s<l.length&&h.empty().append(c(k.get(0),s-1)).append(g)}j.remove();f&&setInterval(F,200)})}})})(jQuery);define("jquery.textOverflow",function(){});
define("index",["require","jquery","blade/fn","rdapi","oauth","blade/jig","blade/url","placeholder","TextCounter","dispatch","accounts","storage","services","blade/object","jquery-ui-1.8.6.custom.min","jquery.textOverflow"],function(b,d,e,c,a,f,g,h,j,k,l,o,s,z){function C(q){return q?q.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"):q}function F(){k.pub("hide")}function v(){E.addClass("hidden");d("div.status").addClass("hidden");h()}function A(){var q=n&&n.domain||"twitter.com",u=
p.siteName,H=p.url||"",J=H.indexOf("//")+2;d("#statusShared").empty().append(f("#sharedTemplate",{domain:u||H.slice(J,H.indexOf("/",J)),service:m[q].name,href:m[q].serviceUrl})).find(".shareTitle").textOverflow(null,true);i("statusShared",true)}function w(q,u){d("#captchaImage").attr("src",q.imageurl);u&&d("#captchaMsg").text(u.message);d("#captchaSound").attr("src",q.audiourl);i("statusCaptcha",false)}function x(){var q={link:n.link,domain:n.domain,formData:m[n.domain].getFormData()};L.sessionRestore=
JSON.stringify(q);i("statusAuth")}function D(){i("statusSharing");if(m[n.domain].validate(n)){var q=l.getService(n.domain,n.userid,n.username);n.account=JSON.stringify(q);c("send",{type:"POST",data:n,success:function(u){if(u.error&&u.error.status){var H=u.error.status;if(H===401||H===535)x();else if(u.error.code==="Client.HumanVerificationRequired")w(u.error.detail);else u.error.code==="Client.WrongInput"?w(u.error.detail,u.error):i("statusError",u.error.message)}else if(u.error)i("statusError",u.error.message);
else{L.lastSelection=m[n.domain].type;A()}delete L.sessionRestore},error:function(u,H,J){if(u.status===403)x();else u.status===503?i("statusServerBusy"):i("statusError",J)}})}else i("statusToError")}function K(q){var u=s.domains[q];d("#"+u.type).find('[name="to"]');(u=u.getContacts(L))||(u=[]);q==="google.com"&&k.pub("autoCompleteData",u)}function O(q,u){var H=u.accounts[0],J=s.domains[H.domain];if(J.getContacts(L))K(H.domain);else{q=l.getService(H.domain,H.userid,H.username);c("contacts/"+H.domain,
{type:"POST",data:{username:H.username,userid:H.userid,startindex:0,maxresults:500,account:JSON.stringify(q)},success:function(M){if(M&&!M.error){var N=[];N=J.get36FormattedContacts(M.result.entry);J.setContacts(L,N);K(H.domain)}}})}}function Y(q,u){var H=q="",J=true,M="",N=u.panel.id,I=d(".user-info");if(N!=="debug"){q=d(u.panel).find("div.user img.avatar").attr("src");H=d(u.panel).find("div.user .username").text();J=d(u.panel).find("div.user").hasClass("inactive");M=d(u.panel).find("div.user input[type='hidden'][name='domain']").val()}d(".user-info img.avatar").attr("src",
q);q?I.show():I.hide();d(".user-info .status").toggleClass("inactive",J);d(".user-info .username").text(H);d(".user-info").attr("data-domain",M)}function Z(q,u){d(function(){var H=u.displayName,J=u.accounts[0],M=u.photos&&u.photos[0]&&u.photos[0].value,N=d("#"+q),I;if((I=J.username)&&I!==H)H=H+" <"+I+">";d("."+q+"Tab").removeClass("hidden");H&&N.find(".username").text(H);M&&N.find(".avatar").attr("src",M);N.find('input[name="userid"]').val(J.userid);N.find('input[name="username"]').val(J.username);
N.find("div.user").removeClass("inactive")})}function T(){var q,u;if(L.lastSelection)q="#"+L.lastSelection;else if(S&&S.length){u=S[0].accounts[0].domain;if(m[u])if(u=m[u].type)q="#"+u}return q}function V(){d(".ui-tabs-nav > li").removeClass("first").removeClass("last").filter(function(){var q=d(this),u=q.hasClass("hidden");q=q.hasClass("debugTab");return!u&&!q}).first().addClass("first").end().last().addClass("last")}function aa(q){var u=false,H={},J=L.sessionRestore,M;q&&q.length&&q.forEach(function(N){var I=
N.accounts[0].domain;if(I&&m[I]){u||(u=m[I].type===L.lastSelection);H[m[I].type]=N}});!u&&!L.accountAdded&&L.lastSelection&&delete L.lastSelection;L.accountAdded&&delete L.accountAdded;for(M in H)if(H.hasOwnProperty(M)){Z(M,H[M]);O(M,H[M])}if(J){J=JSON.parse(J);if(p.link!==J.link){J=null;delete L.sessionRestore}if(J){m[J.domain].setFormData(J.formData);h()}}if(G){q=T();B.tabs("select",q);Y(null,{panel:d(q)[0]})}V()}var i,m=s.domains;b=location.href.split("#")[1];var n,r,p={},B,y,E,G=true,R,S,P,L=
o();z.mixin(s.svcBaseProto,{validate:function(){if(this.counter)return!this.counter||!this.counter.isOver();return true},startCounter:function(q){if(!(this.textLimit<1)){if(!this.counter)this.counter=new j(d("#"+this.type+" textarea.message"),d("#"+this.type+" .counter"),this.textLimit-26);this.counter.updateLimit(q.shortUrl?this.textLimit-(q.shortUrl.length+1):this.textLimit-26)}},getFormData:function(){var q=d("#"+this.type);return{to:q.find('[name="to"]').val().trim()||"",subject:q.find('[name="subject"]').val().trim()||
"",message:q.find("textarea.message").val().trim()||"",picture:q.find('[name="picture"]').val().trim()||"",canonicalUrl:q.find('[name="link"]').val().trim()||"",title:q.find('[name="title"]').val().trim()||"",description:q.find('[name="description"]').val().trim()||"",shortUrl:(q.find('[name="surl"]').val()||"").trim()}},setFormData:function(q){var u=d("#"+this.type);q.to&&u.find('[name="to"]').val(q.to);q.subject&&u.find('[name="subject"]').val(q.subject);q.message&&u.find("textarea.message").val(q.message);
q.previews&&q.previews.length&&u.find('[name="picture"]').val(q.previews[0]);if(q.canonicalUrl||q.url)u.find('[name="link"]').val(q.canonicalUrl||q.url);q.title&&u.find('[name="title"]').val(q.title);q.description&&u.find('[name="description"]').val(q.description);q.shortUrl&&u.find('[name="surl"]').val(q.shortUrl);this.startCounter(q)}});f.addFn({profilePic:function(q){return q&&q[0]&&q[0].value||"i/face2.png"},serviceName:function(q){return m[q].name}});window.closeShare=F;i=function(q,u){d("div.status").addClass("hidden");
E.removeClass("hidden");d("#"+q).removeClass("hidden");if(u===true)setTimeout(function(){k.pub("success",{domain:n.domain,username:n.username,userid:n.userid})},2E3);else u&&d("#"+q+"Message").text(u)};window.showStatus=i;window.showStatusShared=A;window.handleCaptcha=w;if(b){g=g.queryToObject(b);if(g.options)p=JSON.parse(g.options)}p.prefs=p.prefs||{};if(!p.title)p.title=p.url;if(!p.prefs.system)p.prefs.system="prod";if(p.version)L.extensionVersion=p.version;if(p.prefs)for(r in p.prefs)if(p.prefs.hasOwnProperty(r))L["prefs."+
r]=p.prefs[r];if(r=L.newTimerV2){r=JSON.parse(r);if((new Date).getTime()-r<2592E5)P=true}else{L.newTimerV1=(new Date).getTime();P=true}d(function(){var q,u=L.sessionRestore,H,J="",M="",N;s.domainList.forEach(function(I){var Q=s.domains[I];Q.domain=I;if(I==="linkedin.com")Q.features.subject=false;J+=f("#tabsTemplate",Q);M+=f("#panelsTemplate",Q)});d(".nav .debugTab").before(J);d("#tabs #debug").before(M);q=d("img.thumb");y=d("body");E=d("#clickBlock");p.prefs.system&&d(document.documentElement).addClass(p.prefs.system);
if(p.prefs.system==="dev"){d("#debugOutput").val(JSON.stringify(p));d("#debugCurrentLocation").val(location.href)}P&&d("#newLink").removeClass("hidden");y.delegate("#statusAuthButton, .statusErrorButton","click",function(){v()}).delegate(".statusErrorCloseButton","click",function(){F()}).delegate(".statusResetErrorButton","click",function(){location.reload()}).delegate(".nav .close","click",F);d("#authOkButton").click(function(){a(n.domain,false,function(I){if(I){l.clear();l()}else i("statusOAuthFailed")})});
d("#captchaButton").click(function(){v();E.removeClass("hidden");n.HumanVerification=d("#captcha").attr("value");n.HumanVerificationImage=d("#captchaImage").attr("src");D()});l.onChange();if(o.type==="memory")i("statusEnableLocalStorage");else{l(function(I){S=I;G=false;aa(S);G=true;if(R=T()){d("."+R.slice(1)+"Tab").addClass("ui-tabs-selected ui-state-active");H=d(R);H.removeClass("ui-tabs-hide");Y(null,{panel:H[0]});B=d("#tabs");B.tabs({fx:{opacity:"toggle",duration:100}});B.bind("tabsselect",Y);
B.removeClass("invisible");y.removeClass("loading");V()}else i("statusSettings")},function(I,Q,U){I.status===503?i("statusServerBusyClose"):i("statusServerError",U)});for(N in s.domains)s.domains.hasOwnProperty(N)&&s.domains[N].setFormData(p);if(u)u=JSON.parse(u);p.title&&d(".title").text(p.title);p.description&&d(".description").text(p.description);if(p.previews&&p.previews.length){u=C(p.previews[0]);q.attr("src",u)}else p.thumbnail&&q.attr("src",C(p.thumbnail));d(".title").textOverflow(null,true);
d(".description").textOverflow(null,true);d(".url").textOverflow(null,true);d(".surl").textOverflow(null,true);d("form.messageForm").submit(function(I){I=I.target;var Q,U,$;n={};d.each(I.elements,function(W,X){W=X.value.trim();if(X.getAttribute("placeholder")===W)W="";X.value=W;if(X.value)n[X.name]=X.value});I=s.domains[n.domain];if(p.shortUrl)n.shorturl=p.shortUrl;else if(I.shorten)n.shorten=true;if(n.to){Q=I.getContacts(L);$=[];if(Q){I=n.to.split(",");I.forEach(function(W){if((U=Q[W.trim()])&&!U.email)$.push(U.userid?
U.userid:U.username)})}if($.length>0)n.to=$.join(", ")}D();return false}).each(function(I,Q){h(Q)})}})});