/*
 blade/func Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/object Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/jig Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/array Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/url Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
*/
define("blade/fn",[],function(){var b=Array.prototype.slice,d=Object.prototype.toString;return{is:function(e){return d.call(e)==="[object Function]"},bind:function(e,c){if(!c)return e;if(typeof c==="string")c=e[c];var a=b.call(arguments,2);return function(){return c.apply(e,a.concat(b.call(arguments,0)))}}}});
define("blade/object",["./fn"],function(b){function d(){}var e={},c=function(a,f,g){a=a||{};var h,i=c.create(a.prototype,f);a=function(j,p,q){return i[p].apply(j,q)};f=c.create(i);c.mixin(f,b.is(g)?g(a):g,true);h=function(){if(!(this instanceof h))throw new Error('blade/object: constructor function called without "new" in front');this.init&&this.init.apply(this,arguments)};h.prototype=f;return h};c.create=function(a,f){d.prototype=a;a=new d;var g,h;d.prototype=null;if(f)for(g=0;h=f[g];g++)c.mixin(a,
h);return a};c.mixin=function(a,f,g){for(var h in f)if(!(h in e)&&(!(h in a)||g))a[h]=f[h]};return c});
define("blade/jig",["require","./object"],function(b,d){function e(k){return G.call(k)==="[object Array]"}function c(k,l,m){l=l;var o,s;for(o=0;l&&(s=k[o]);o++)l=typeof l==="object"&&s in l?l[s]:m&&o===0&&s in m?m[s]:undefined;return l}function a(k){return k?parseInt(k,10):0}function f(k,l,m){var o=/\[([\w0-9\.'":]+)\]/,s=k,r=l,u=true,B,C;if(k===z)return l;if(v.test(k))return a(k);if(k==="")return"";B=k.charAt(0);if(B==="'"||B==="'")return k.substring(1,k.length-1);if((B=k.indexOf("("))!==-1){o=k.lastIndexOf(")");
u=k.substring(0,B);s=m.fn[u];if(!s){q.error("Cannot find function named: "+u+" for "+k);return""}u=k.substring(B+1,o);if(u.indexOf(",")!==-1){u=u.split(",");for(r=u.length-1;r>=0;r--)u[r]=f(u[r],l,m);s=s.apply(null,u)}else s=s(f(u,l,m));if(o<k.length-1){if(k.charAt(o+1)===".")o+=1;return f(k.substring(o+1,k.length),s,m)}else return s}for(;B=o.exec(s);){l=B[1].replace(/['"]/g,"");C=s.substring(0,B.index);s=s.substring(B.index+B[0].length,s.length);if(s.indexOf(".")===0)s=s.substring(1,s.length);r=
c(C.split("."),r,u?m.context:null);u=false;if(!r&&l){q.error('blade/jig: No property "'+l+'" on '+r);return""}if(l.indexOf(":")!==-1){B=l.split(":");l=a(B[0]);r=(B=a(B[1]))?r.slice(l,B):r.slice(l)}else{m.strict&&!(l in r)&&q.error('blade/jig: no property "'+l+'"');r=r[l]}r=r}s=s?c(s.split("."),r,u?m.context:null):r;m.strict&&s===undefined&&q.error('blade/jig: undefined value for property "'+k+'"');return s}function g(k,l){l=l||{};var m=q.cache(k,l);if(m===undefined&&typeof document!=="undefined"){(m=
document.getElementById(k))&&q.parse([m],l);m=q.cache(k,l)}if(m===undefined)throw new Error("blade/jig: no template or node with ID: "+k);return m}function h(k,l){for(var m=[],o=0,s=false,r=0,u,B,C,R,S,P;(u=k.indexOf(l.startToken,o))!==-1;){u!==o&&m.push(k.substring(o,u));o=k.substring(u);if(B=l.endRegExp.exec(o)){o=u+B[0].length;C=k.substring(u+l.startToken.length,u+B[0].length-l.endToken.length).trim();C=K(C);if(A.test(C))throw new Error("blade/jig: end block tags should not be commented: "+C);
u=C.charAt(0);if(u==="]"&&r){s=C.substring(1).trim();if(s==="[")u=">";else{u=s.charAt(0);C=s}}if(u&&!l.propertyRegExp.test(u))C=C.substring(1).trim();else u="_default_";if(s=C.indexOf(l.rawHtmlToken)===0)C=C.substring(l.rawHtmlToken.length,C.length);if(u===N)s=true;C=C.split(l.argSeparator);R=C[C.length-1];S=R.charAt(R.length-1);P=null;if(u==="]"){if(S!=="["){m.templateEnd=o;m.endControl=true}else m.templateEnd=o-B[0].length;return m}else if(S==="["){r||(r=U++);C[C.length-1]=R.substring(0,R.length-
1);P=h(k.substring(o),l);o+=P.templateEnd}if(u==="+")l.templates[C[0]]=P;else if(u!=="/"){if(C.length>1)for(B=C.length-1;B>=0;B--)if(C[B].charAt(C[B].length-1)===","){C[B]+=C[B+1];C.splice(B+1,1)}m.push({action:l.commands[u].action,useRawHtml:s,args:C,controlId:r,children:P})}if(P&&P.endControl)r=0}else{m.push(o);return m}}o!==k.length-1&&m.push(k.substring(o,k.length));return m}function i(k,l){var m,o=k.id;m=l.templates||I;if(m[o])return m[o];l.onBeforeParse&&l.onBeforeParse(k);if(k.nodeName.toUpperCase()===
"SCRIPT"){m=k.text.trim();k.parentNode&&k.parentNode.removeChild(k)}else{V.appendChild(k);k.removeAttribute("id");(m=(k.getAttribute("class")||"").trim())&&k.setAttribute("class",m.replace(Z,"$1$3"));m=V.innerHTML.replace(/%7B/g,"{").replace(/%7D/g,"}");V.removeChild(k)}k=q.compile(m,l);q.cache(o,k,l);return k}function j(k,l,m){var o="",s,r,u,B,C;if(typeof k==="string")o=k;else if(e(k))for(s=0;s<k.length;s++){u=k[s].controlId;if(!u||u!==r||!C){B=j(k[s],l,m);o+=B;if(u){r=u;C=B}}}else if(o=k.action(k.args,
l,m,k.children,j)){if(!k.useRawHtml&&!k.children)o=q.htmlEscape(o.toString())}else o="";if(m.attachData)if(w.test(o)){k="id"+aa++;o=o.replace(w,'$& data-blade-jig="'+k+'" ');W[k]=l}return o}function p(k){k.fn.jig=function(l,m){m=m||{};var o=this.selector;if(o.charAt(0)!=="#")throw new Error('blade/jig: only ID selectors, like "#something" are allowed with jig()');o=o.substring(1,o.length);(o=(m.templates||I)[o])||(o=i(this[0]));return k(q.render(o,l,m))}}var q,D,G=Object.prototype.toString,K=typeof decodeURIComponent===
"undefined"?function(){}:decodeURIComponent,N="#",y=/[_\[\^\w]/,z="_",w=/<\s*\w+/,v=/^\d+$/,A=/\/(\/)?\s*\]/,I={},O={openCurly:function(){return"{"},closeCurly:function(){return"}"},eq:function(k,l){return k===l},gt:function(k,l){return k>l},gte:function(k,l){return k>=l},lt:function(k,l){return k<l},lte:function(k,l){return k<=l},or:function(k,l){return k||l},and:function(k,l){return k&&l},is:function(k){return!!k},eachProp:function(k){var l,m=[];for(l in k)k.hasOwnProperty(l)&&m.push({prop:l,value:k[l]});
return m.sort(function(o,s){return o.prop>s.prop?1:-1})}},aa=1,U=1,W={},V=typeof document!=="undefined"&&document.createElement?document.createElement("div"):null,Z=/(\s*)(template)(\s*)/;D={_default_:{doc:"Property reference",action:function(k,l,m,o,s){var r=k[0]?f(k[0],l,m):l,u=k[1]?f(k[1],l,m):undefined,B="";if(k[1]){u=r===u;r=l}else u=r;if(u===false||u===null||u===undefined||e(u)&&!u.length)return"";else if(o)if(e(r))for(k=0;k<r.length;k++)B+=s(o,r[k],m);else{if(typeof r==="boolean")r=l;B=s(o,
r,m)}else B=r;return B}},"!":{doc:"Not",action:function(k,l,m,o,s){var r=f(k[0],l,m),u=k[1]?f(k[1],l,m):undefined;u=k[1]?r===u:r;if(o&&!u)return s(o,l,m);return""}},"#":{doc:"Template reference",action:function(k,l,m,o,s){o=g(k[0],m);l=f(k.length>1?k[1]:z,l,m);return s(o,l,m)}},".":{doc:"Variable declaration",action:function(k,l,m){m.context[k[0]]=f(k[1],l,m);return""}},">":{doc:"Else",action:function(k,l,m,o,s){if(o)return s(o,l,m);return""}}};q=function(k,l,m){if(typeof k==="string")if(k.charAt(0)===
"#"){k=k.substring(1,k.length);k=g(k,m)}else k=q.compile(k,m);return q.render(k,l,m)};q.htmlEscape=function(k){return k.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};q.compile=function(k,l){l=l||{};d.mixin(l,{startToken:"{",endToken:"}",rawHtmlToken:"^",propertyRegExp:y,commands:D,argSeparator:" ",templates:I});l.endRegExp=/[^\r\n]*?}/;U=1;return h(k,l)};q.parse=function(k,l){if(k&&!k.length){l=k;k=null}l=l||{};k=k||document.querySelectorAll('.template, script[type="text/template"]');
var m,o;for(o=k.length-1;o>-1&&(m=k[o]);o--)i(m,l)};q.render=function(k,l,m){var o,s="";m=m||{};d.mixin(m,{templates:I,attachData:false,strict:q.strict});if(m.fn)d.mixin(m.fn,O);else m.fn=O;m.context=m.context||d.create(l);if(e(l)){for(o=0;o<l.length;o++)s+=j(k,l[o],m);return s}return j(k,l,m)};q.strict=false;q.error=function(k){throw k;};q.addFn=function(k){d.mixin(O,k,true)};q.data=function(k,l){if(typeof k!=="string"){k.nodeType||(k=k[0]);k=k.getAttribute("data-blade-jig")}return l!==undefined?
(W[k]=l):W[k]};q.removeData=function(k){delete W[k]};q.getObject=f;q.cache=function(k,l,m){if(typeof l==="string")l=q.compile(l,m);if(!e(l)){m=l;l=undefined}m=m&&m.templates||I;if(l!==undefined)m[k]=l;return m[k]||I[k]};typeof jQuery!=="undefined"&&p(jQuery);return q});
define("friendly",["require","exports","module"],function(){var b={timestamp:function(d){return b.date(new Date(d*1E3))},date:function(d){var e=((new Date).getTime()-d.getTime())/1E3,c=Math.floor(e/86400),a={friendly:d.toLocaleDateString(),additional:d.toLocaleTimeString(),utc:d.toUTCString(),locale:d.toLocaleString()};if(c<0){a.friendly="in the future";return a}else if(isNaN(c)){a.friendly=a.additional="unknown";return a}if(c===0){if(e<60){a.friendly="just now";return a}if(e<150){a.friendly="a minute ago";
return a}if(e<3600){a.friendly=Math.floor(e/60)+" minutes ago";return a}if(e<7200){a.friendly="1 hour ago";return a}if(e<86400){a.friendly=Math.floor(e/3600)+" hours ago";return a}}if(c===1){a.friendly="yesterday";return a}if(c<7){a.friendly=c+" days ago";return a}if(c<8){a.friendly="last week";return a}if(c<31){a.friendly=Math.ceil(c/7)+" weeks ago";return a}if(c<62){a.friendly="a month ago";return a}if(c<365){a.friendly=Math.ceil(c/31)+" months ago";return a}if(c>=365&&c<730){a.additional=d.toLocaleDateString();
a.friendly="a year ago";return a}if(c>=365){a.additional=d.toLocaleDateString();a.friendly=Math.ceil(c/365)+" years ago";return a}return a},name:function(d){d=d.split(" ")[0];if(d.indexOf("@")!==-1)d=d.split("@")[0];d=d.replace(" ","");d=d.replace("'","");return d=d.replace('"',"")}};return b});
define("isoDate",[],function(){var b=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+\-](\d{2}):(\d{2}))|Z)?)?$/,d=function(e,c){var a=b.exec(e);e=null;var f,g;if(a){a.shift();a[1]&&a[1]--;if(a[6])a[6]*=1E3;if(c){c=new Date(c);["FullYear","Month","Date","Hours","Minutes","Seconds","Milliseconds"].map(function(h){return c["get"+h]()}).forEach(function(h,i){a[i]=a[i]||h})}e=new Date(a[0]||1970,a[1]||0,a[2]||1,a[3]||0,a[4]||0,a[5]||0,a[6]||0);if(a[0]<100)e.setFullYear(a[0]||
1970);f=0;g=a[7]&&a[7].charAt(0);if(g!=="Z"){f=(a[8]||0)*60+(Number(a[9])||0);if(g!=="-")f*=-1}if(g)f-=e.getTimezoneOffset();f&&e.setTime(e.getTime()+f*6E4)}return e};d.toIsoString=function(e,c){var a=function(i){return i<10?"0"+i:i},f,g,h;c=c||{};f=[];g=c.zulu?"getUTC":"get";h="";if(c.selector!=="time"){h=e[g+"FullYear"]();h=["0000".substr((h+"").length)+h,a(e[g+"Month"]()+1),a(e[g+"Date"]())].join("-")}f.push(h);if(c.selector!=="date"){h=[a(e[g+"Hours"]()),a(e[g+"Minutes"]()),a(e[g+"Seconds"]())].join(":");
g=e[g+"Milliseconds"]();if(c.milliseconds)h+="."+(g<100?"0":"")+a(g);if(c.zulu)h+="Z";else if(c.selector!=="time"){e=e.getTimezoneOffset();c=Math.abs(e);h+=(e>0?"-":"+")+a(Math.floor(c/60))+":"+a(c%60)}f.push(h)}return f.join("T")};return d});var EXPORTED_SYMBOLS=["hex_md5"],hexcase=0,b64pad="";function hex_md5(b){return rstr2hex(rstr_md5(str2rstr_utf8(b)))}function b64_md5(b){return rstr2b64(rstr_md5(str2rstr_utf8(b)))}function any_md5(b,d){return rstr2any(rstr_md5(str2rstr_utf8(b)),d)}
function hex_hmac_md5(b,d){return rstr2hex(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)))}function b64_hmac_md5(b,d){return rstr2b64(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)))}function any_hmac_md5(b,d,e){return rstr2any(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)),e)}function md5_vm_test(){return hex_md5("abc").toLowerCase()=="900150983cd24fb0d6963f7d28e17f72"}function rstr_md5(b){return binl2rstr(binl_md5(rstr2binl(b),b.length*8))}
function rstr_hmac_md5(b,d){var e=rstr2binl(b);if(e.length>16)e=binl_md5(e,b.length*8);var c=Array(16);b=Array(16);for(var a=0;a<16;a++){c[a]=e[a]^909522486;b[a]=e[a]^1549556828}d=binl_md5(c.concat(rstr2binl(d)),512+d.length*8);return binl2rstr(binl_md5(b.concat(d),640))}function rstr2hex(b){for(var d=hexcase?"0123456789ABCDEF":"0123456789abcdef",e="",c,a=0;a<b.length;a++){c=b.charCodeAt(a);e+=d.charAt(c>>>4&15)+d.charAt(c&15)}return e}
function rstr2b64(b){for(var d="",e=b.length,c=0;c<e;c+=3)for(var a=b.charCodeAt(c)<<16|(c+1<e?b.charCodeAt(c+1)<<8:0)|(c+2<e?b.charCodeAt(c+2):0),f=0;f<4;f++)d+=c*8+f*6>b.length*8?b64pad:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>6*(3-f)&63);return d}
function rstr2any(b,d){var e=d.length,c,a,f,g,h,i=Array(Math.ceil(b.length/2));for(c=0;c<i.length;c++)i[c]=b.charCodeAt(c*2)<<8|b.charCodeAt(c*2+1);var j=Math.ceil(b.length*8/(Math.log(d.length)/Math.log(2)));b=Array(j);for(a=0;a<j;a++){h=Array();for(c=g=0;c<i.length;c++){g=(g<<16)+i[c];f=Math.floor(g/e);g-=f*e;if(h.length>0||f>0)h[h.length]=f}b[a]=g;i=h}e="";for(c=b.length-1;c>=0;c--)e+=d.charAt(b[c]);return e}
function str2rstr_utf8(b){for(var d="",e=-1,c,a;++e<b.length;){c=b.charCodeAt(e);a=e+1<b.length?b.charCodeAt(e+1):0;if(55296<=c&&c<=56319&&56320<=a&&a<=57343){c=65536+((c&1023)<<10)+(a&1023);e++}if(c<=127)d+=String.fromCharCode(c);else if(c<=2047)d+=String.fromCharCode(192|c>>>6&31,128|c&63);else if(c<=65535)d+=String.fromCharCode(224|c>>>12&15,128|c>>>6&63,128|c&63);else if(c<=2097151)d+=String.fromCharCode(240|c>>>18&7,128|c>>>12&63,128|c>>>6&63,128|c&63)}return d}
function str2rstr_utf16le(b){for(var d="",e=0;e<b.length;e++)d+=String.fromCharCode(b.charCodeAt(e)&255,b.charCodeAt(e)>>>8&255);return d}function str2rstr_utf16be(b){for(var d="",e=0;e<b.length;e++)d+=String.fromCharCode(b.charCodeAt(e)>>>8&255,b.charCodeAt(e)&255);return d}function rstr2binl(b){for(var d=Array(b.length>>2),e=0;e<d.length;e++)d[e]=0;for(e=0;e<b.length*8;e+=8)d[e>>5]|=(b.charCodeAt(e/8)&255)<<e%32;return d}
function binl2rstr(b){for(var d="",e=0;e<b.length*32;e+=8)d+=String.fromCharCode(b[e>>5]>>>e%32&255);return d}
function binl_md5(b,d){b[d>>5]|=128<<d%32;b[(d+64>>>9<<4)+14]=d;d=1732584193;for(var e=-271733879,c=-1732584194,a=271733878,f=0;f<b.length;f+=16){var g=d,h=e,i=c,j=a;d=md5_ff(d,e,c,a,b[f+0],7,-680876936);a=md5_ff(a,d,e,c,b[f+1],12,-389564586);c=md5_ff(c,a,d,e,b[f+2],17,606105819);e=md5_ff(e,c,a,d,b[f+3],22,-1044525330);d=md5_ff(d,e,c,a,b[f+4],7,-176418897);a=md5_ff(a,d,e,c,b[f+5],12,1200080426);c=md5_ff(c,a,d,e,b[f+6],17,-1473231341);e=md5_ff(e,c,a,d,b[f+7],22,-45705983);d=md5_ff(d,e,c,a,b[f+8],7,
1770035416);a=md5_ff(a,d,e,c,b[f+9],12,-1958414417);c=md5_ff(c,a,d,e,b[f+10],17,-42063);e=md5_ff(e,c,a,d,b[f+11],22,-1990404162);d=md5_ff(d,e,c,a,b[f+12],7,1804603682);a=md5_ff(a,d,e,c,b[f+13],12,-40341101);c=md5_ff(c,a,d,e,b[f+14],17,-1502002290);e=md5_ff(e,c,a,d,b[f+15],22,1236535329);d=md5_gg(d,e,c,a,b[f+1],5,-165796510);a=md5_gg(a,d,e,c,b[f+6],9,-1069501632);c=md5_gg(c,a,d,e,b[f+11],14,643717713);e=md5_gg(e,c,a,d,b[f+0],20,-373897302);d=md5_gg(d,e,c,a,b[f+5],5,-701558691);a=md5_gg(a,d,e,c,b[f+
10],9,38016083);c=md5_gg(c,a,d,e,b[f+15],14,-660478335);e=md5_gg(e,c,a,d,b[f+4],20,-405537848);d=md5_gg(d,e,c,a,b[f+9],5,568446438);a=md5_gg(a,d,e,c,b[f+14],9,-1019803690);c=md5_gg(c,a,d,e,b[f+3],14,-187363961);e=md5_gg(e,c,a,d,b[f+8],20,1163531501);d=md5_gg(d,e,c,a,b[f+13],5,-1444681467);a=md5_gg(a,d,e,c,b[f+2],9,-51403784);c=md5_gg(c,a,d,e,b[f+7],14,1735328473);e=md5_gg(e,c,a,d,b[f+12],20,-1926607734);d=md5_hh(d,e,c,a,b[f+5],4,-378558);a=md5_hh(a,d,e,c,b[f+8],11,-2022574463);c=md5_hh(c,a,d,e,b[f+
11],16,1839030562);e=md5_hh(e,c,a,d,b[f+14],23,-35309556);d=md5_hh(d,e,c,a,b[f+1],4,-1530992060);a=md5_hh(a,d,e,c,b[f+4],11,1272893353);c=md5_hh(c,a,d,e,b[f+7],16,-155497632);e=md5_hh(e,c,a,d,b[f+10],23,-1094730640);d=md5_hh(d,e,c,a,b[f+13],4,681279174);a=md5_hh(a,d,e,c,b[f+0],11,-358537222);c=md5_hh(c,a,d,e,b[f+3],16,-722521979);e=md5_hh(e,c,a,d,b[f+6],23,76029189);d=md5_hh(d,e,c,a,b[f+9],4,-640364487);a=md5_hh(a,d,e,c,b[f+12],11,-421815835);c=md5_hh(c,a,d,e,b[f+15],16,530742520);e=md5_hh(e,c,a,
d,b[f+2],23,-995338651);d=md5_ii(d,e,c,a,b[f+0],6,-198630844);a=md5_ii(a,d,e,c,b[f+7],10,1126891415);c=md5_ii(c,a,d,e,b[f+14],15,-1416354905);e=md5_ii(e,c,a,d,b[f+5],21,-57434055);d=md5_ii(d,e,c,a,b[f+12],6,1700485571);a=md5_ii(a,d,e,c,b[f+3],10,-1894986606);c=md5_ii(c,a,d,e,b[f+10],15,-1051523);e=md5_ii(e,c,a,d,b[f+1],21,-2054922799);d=md5_ii(d,e,c,a,b[f+8],6,1873313359);a=md5_ii(a,d,e,c,b[f+15],10,-30611744);c=md5_ii(c,a,d,e,b[f+6],15,-1560198380);e=md5_ii(e,c,a,d,b[f+13],21,1309151649);d=md5_ii(d,
e,c,a,b[f+4],6,-145523070);a=md5_ii(a,d,e,c,b[f+11],10,-1120210379);c=md5_ii(c,a,d,e,b[f+2],15,718787259);e=md5_ii(e,c,a,d,b[f+9],21,-343485551);d=safe_add(d,g);e=safe_add(e,h);c=safe_add(c,i);a=safe_add(a,j)}return Array(d,e,c,a)}function md5_cmn(b,d,e,c,a,f){return safe_add(bit_rol(safe_add(safe_add(d,b),safe_add(c,f)),a),e)}function md5_ff(b,d,e,c,a,f,g){return md5_cmn(d&e|~d&c,b,d,a,f,g)}function md5_gg(b,d,e,c,a,f,g){return md5_cmn(d&c|e&~c,b,d,a,f,g)}
function md5_hh(b,d,e,c,a,f,g){return md5_cmn(d^e^c,b,d,a,f,g)}function md5_ii(b,d,e,c,a,f,g){return md5_cmn(e^(d|~c),b,d,a,f,g)}function safe_add(b,d){var e=(b&65535)+(d&65535);return(b>>16)+(d>>16)+(e>>16)<<16|e&65535}function bit_rol(b,d){return b<<d|b>>>32-d}define("md5",function(){});
define("rdapi",["require","jquery","blade/object","blade/jig","friendly","isoDate","md5"],function(b,d,e,c,a,f){function g(y){if(typeof y==="string")y={template:y};else if(y.templateId)y.template=c.cache(y.templateId);if(!("attachData"in y))y.attachData=p.attachTemplateData;if(y.emptyTemplateId)y.emptyTemplate=c.cache(y.emptyTemplateId);return y}function h(){var y=D.exec(document.cookie);return y&&y[1]?y[1]:null}function i(y,z){z.url=N.baseUrl+N.apiPath+y;e.mixin(z,{limit:30,message_limit:3,dataType:"json",
error:function(A,I,O){throw O;}});var w=z.success,v=h();z.success=function(A){A&&A.contacts&&e.mixin(G,A.contacts,true);return w?w.apply(null,arguments):A};if(v)z.beforeSend=function(A){A.setRequestHeader(q,v)};d.ajax(z)}function j(y,z){var w=z.forId?document.getElementById(z.forId):null;if(w)w.innerHTML=y;z.onTemplateDone&&z.onTemplateDone(y);d(document).trigger("rdapi-done",w)}var p,q="X-CSRF",D=/csrf=([^\; ]+)/,G={},K={contact:function(y){return y.iid&&y.domain?G[y.iid]||{}:y},contactPhotoUrl:function(y){var z=
"i/face2.png",w,v;y=K.contact(y);if((w=y.photos)&&w.length){z=w[0].value;w.forEach(function(A){if(A.primary)z=A.value})}else if(y.emails&&y.emails.length){v=y.emails[0].value;y.emails.forEach(function(A){if(A.primary)v=A.value});z="http://www.gravatar.com/avatar/"+hex_md5(v)+"?s=24 &d=identicon"}return z},allMessages:function(y){return[y.topic].concat(y.messages||[])},friendlyDate:function(y){return a.date(f(y)).friendly},htmlBody:function(y){return c.htmlEscape(y).replace(/\n/g,"<br>")}},N={baseUrl:"/",
apiPath:"api/",saveTemplateData:true};c.addFn(K);p=function(y,z){z=g(z);e.mixin(z,{success:function(w){var v=z.template,A=z.emptyTemplate,I="";if(z.forId&&v){if(z.prop)w=c.getObject(z.prop,w,z);if(b.isArray(w))if(w.length)w.forEach(function(O){I+=c(v,O,z)});else I+=c(A,w,z);else I+=c(!w?A:v,w,z);j(I,z)}},error:function(w,v,A){if(z.emptyTemplate){w=c(z.emptyTemplate,A,z);j(w,z)}else throw A;}});i(y,z)};p.contactPhotoUrl=K.contactPhotoUrl;p.attachTemplateData=false;b.ready(function(){var y=[];c.parse({onBeforeParse:function(z){var w=
z.id,v=z.getAttribute("data-rdapi"),A=z.getAttribute("data-rdfor"),I=z.getAttribute("data-rdprop");v&&y.push({templateId:w,api:v,forId:A,prop:I});["data-rdapi","data-rdprop","data-rdfor"].forEach(function(O){z.removeAttribute(O)})}});y.forEach(function(z){p(z.api,z)})});return p});
define("oauth",[],function(){var b,d,e=0;window.addEventListener("message",function(c){if(c=c.data){c=c==="oauth_success"?true:false;d=null;if(b){b(c);b=null}}},false);return function(c,a){if(a)b=a;a=location.protocol+"//"+location.host+"/auth.html";var f=(new Date).getTime();if(d&&d.closed)d=null;if(f>e+4E3){e=f;c=a+"?domain="+c;try{d=window.open(c,"ffshareOAuth","dialog=yes, modal=yes, width=900, height=500, scrollbars=yes");d.focus()}catch(g){window.location=c+"&end_point_success="+encodeURI(window.location)}}else d&&
d.focus()}});define("blade/array",[],function(){var b=Object.prototype.toString,d=Array.prototype.slice;return{is:function(e){return b.call(e)==="[object Array]"},to:function(){return[].concat(d.call(arguments,0))}}});
define("blade/url",["./array"],function(b){var d=Object.prototype.toString;return{objectToQuery:function(e){var c=encodeURIComponent,a=[],f={},g,h,i,j;for(g in e)if(e.hasOwnProperty(g)){h=e[g];if(h!==f[g]){i=c(g)+"=";if(b.is(h))for(j=0;j<h.length;j++)a.push(i+c(h[j]));else a.push(i+c(h))}}return a.join("&")},queryToObject:function(e){var c={};e=e.split("&");var a=decodeURIComponent,f,g,h;e.forEach(function(i){if(i.length){f=i.split("=");g=a(f.shift());h=a(f.join("="));if(typeof c[g]==="string")c[g]=
[c[g]];if(d.call(c[g])==="[object Array]")c[g].push(h);else c[g]=h}});return c}}});
define("placeholder",["jquery"],function(b){function d(a){var f=!("placeholder"in a),g=a.getAttribute("placeholder"),h=a.value.trim();if(!h||h===g){if(f){b(a).addClass("placeholder");a.value=g;if(g==="password"&&a.type==="password")a.type="text"}}else b(a).removeClass("placeholder")}function e(a){a=a.target;var f=a.getAttribute("placeholder");if(a.value===f){if(!("placeholder"in a)){a.value="";if(f==="password"&&a.type==="text")a.type="password"}b(a).removeClass("placeholder")}}function c(a){d(a.target)}
return function(a){b('input[type="text"], input[type="password"], textarea',a).each(function(f,g){if(g.getAttribute("data-rdwPlaceholder")!=="set"){b(g).focus(e).blur(c);g.setAttribute("data-rdwPlaceholder","set")}d(g)})}});
define("TextCounter",["jquery","blade/object","blade/fn"],function(b,d,e){return d(null,null,{init:function(c,a,f){this.dom=b(c);this.domPlaceholderText=this.dom[0].getAttribute("placeholder")||"";this.countDom=b(a);this.limit=f;this.dom.bind("keyup",e.bind(this,"checkCount"));this.checkCount()},checkCount:function(){var c=this.dom[0].value;if(c.trim()===this.domPlaceholderText)c="";c=this.limit-c.length;c<0?this.countDom.addClass("TextCountOver"):this.countDom.removeClass("TextCountOver");this.countDom.text(c===
this.limit?"":c)},updateLimit:function(c){this.limit=c;this.checkCount()},isOver:function(){return this.dom[0].value.length>this.limit}})});
define("dispatch",["jquery"],function(){var b=location.protocol+"//"+location.host;return{sub:function(d,e,c,a){c=c||window;a=a||b;var f=function(g){if(g.origin===a||g.origin==="chrome://browser")try{var h=JSON.parse(g.data),i=h.topic;i&&i===d&&e(h.data)}catch(j){}};c.addEventListener("message",f,false);return f},unsub:function(d,e){e=e||window;e.removeEventListener("message",d,false)},pub:function(d,e,c){c=c||window;c.postMessage(JSON.stringify({topic:d,data:e}),b)}}});
define("AutoComplete",["jquery","blade/object","blade/fn","dispatch"],function(b,d,e){return d(null,null,{init:function(c){this.dom=b(c);this.dom.bind("keyup",e.bind(this,"onKeyUp"))},onKeyUp:function(){}})});define("storage",[],function(){function b(){return d}var d=localStorage,e="localStorage";try{d.tempVar="temp";delete d.tempVar}catch(c){d={};e="memory"}b.type=e;return b});
define("accounts",["storage","dispatch","rdapi"],function(b,d,e){function c(h,i){return g.accounts(h,i)}function a(){location.reload()}var f=b(),g;g={localStorage:{accounts:function(h,i){var j=f.accountCache,p=f.lastAccountCheck||0,q=(new Date).getTime(),D=false;if(!j||q-p>3E3)D=true;j=j?JSON.parse(j):[];h&&h(j);D&&g.fetch(null,i)},fetch:function(h,i){e("account/get",{success:function(j){if(j.error)j=[];f.lastAccountCheck=(new Date).getTime();h&&h(j);var p=f.accountCache,q;p=p?JSON.parse(p):[];if(q=
j.length===p.length)q=!j.some(function(D,G){return D.identifier!==p[G].identifier});if(!q){f.accountCache=JSON.stringify(j);g.changed()}},error:i||function(){}})},changed:function(){f.accountChanged=(new Date).getTime();opener&&!opener.closed&&d.pub("accountsChanged",null,opener);d.pub("accountsChanged")},onChange:function(h){var i=f.accountChanged;window.addEventListener("storage",function(){f.accountChanged!==i&&h()},false);d.sub("accountsChanged",h)}},memory:{accounts:function(h,i){g.fetch(h,i)},
fetch:function(h,i){e("account/get",{success:function(j){if(j.error)j=[];h&&h(j)},error:i||function(){}})},changed:function(){f.accountChanged=(new Date).getTime();opener&&d.pub("accountsChanged",null,opener);d.pub("accountsChanged")},onChange:function(h){d.sub("accountsChanged",h)}}}[b.type];c.fetch=function(h,i){g.fetch(h,i)};c.clear=function(){delete f.accountCache};c.changed=function(){return g.changed()};c.onChange=function(h){return g.onChange(h||a)};return c});
define("services",["rdapi","blade/object","blade/array","TextCounter"],function(b,d,e){function c(h,i){if(h){this.name=h;this.type=h.replace(/\s/g,"").toLowerCase();this.tabName=this.type+"Tab";this.icon="i/"+this.type+"Icon.png";this.autoCompleteWidget=null;this.features={counter:false,direct:false,subject:false};d.mixin(this,i,true)}}function a(){c.constructor.apply(this,arguments);this.features.direct=true;this.features.subject=true}var f,g;c.constructor=c;c.prototype={clearCache:function(h){delete h[this.type+
"Contacts"]},getContacts:function(h){if(h[this.type+"Contacts"]){var i=JSON.parse(h[this.type+"Contacts"]);if(!f.isFF36&&i&&e.is(i)){i=null;delete h[this.type+"Contacts"]}return i}return null},setContacts:function(h,i){h[this.type+"Contacts"]=JSON.stringify(i)},getFormattedContacts:function(h){var i={};h.forEach(function(j){j.accounts&&j.accounts.length&&j.accounts.forEach(function(p){i[j.displayName]={email:"",userid:p.userid,username:p.username}})});return i},get36FormattedContacts:function(){return null}};
a.prototype=new c;a.constructor=a;a.prototype.validate=function(h){if(!h.to||!h.to.trim())return false;return true};a.prototype.getFormattedContacts=function(h){var i={};h.forEach(function(j){j.emails&&j.emails.length&&j.emails.forEach(function(p){i[j.displayName?j.displayName:p.value]={email:p.value,userid:null,username:null}})});return i};a.prototype.get36FormattedContacts=function(h){var i=[];h.forEach(function(j){j.emails&&j.emails.length&&j.emails.forEach(function(p){i.push({displayName:j.displayName?
j.displayName:p.value,email:p.value})})});return i};f={domains:{"twitter.com":new c("Twitter",{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"public",name:"public"},{type:"direct",name:"direct message",showTo:true,toLabel:"type in name of recipient"}],textLimit:140,shorten:true,serviceUrl:"http://twitter.com",revokeUrl:"http://twitter.com/settings/connections",signOutUrl:"http://twitter.com/logout",accountLink:function(h){return"http://twitter.com/"+h.username}}),"facebook.com":new c("Facebook",
{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"wall",name:"my wall"},{type:"groupWall",name:"group wall",showTo:true,toLabel:"type in the name of the group"}],textLimit:420,serviceUrl:"http://facebook.com",revokeUrl:"http://www.facebook.com/editapps.php?v=allowed",signOutUrl:"http://facebook.com",accountLink:function(h){return"http://www.facebook.com/profile.php?id="+h.userid}}),"google.com":new a("Gmail",{shareTypes:[{type:"direct",name:"direct",showTo:true}],serviceUrl:"https://mail.google.com",
revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(h){return"http://google.com/profiles/"+h.username}}),"googleapps.com":new a("Google Apps",{shareTypes:[{type:"direct",name:"direct",showTo:true}],icon:"i/gmailIcon.png",serviceUrl:"https://mail.google.com",revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(h){return"http://google.com/profiles/"+
h.username}}),"yahoo.com":new a("Yahoo",{shareTypes:[{type:"direct",name:"direct",showTo:true}],name:"Yahoo!",serviceUrl:"http://mail.yahoo.com",revokeUrl:"https://api.login.yahoo.com/WSLogin/V1/unlink",signOutUrl:"https://login.yahoo.com/config/login?logout=1",accountLink:function(h){return"http://profiles.yahoo.com/"+h.username}}),"linkedin.com":new c("LinkedIn",{isNew:true,features:{direct:true,subject:true,counter:false},shareTypes:[{type:"public",name:"anyone"},{type:"myConnections",name:"connections only",
specialTo:"connections-only"},{type:"contact",name:"send message",showTo:true,toLabel:"type in the name of the contact"}],serviceUrl:"http://linkedin.com",revokeUrl:"http://linkedin.com/settings/connections",signOutUrl:"http://linkedin.com/logout",accountLink:function(h){return"http://linkedin.com/"+h.username},overlays:{"widgets/AccountPanel":"widgets/AccountPanelLinkedIn"}})},domainList:[],svcBaseProto:c.prototype};for(g in f.domains)f.domains.hasOwnProperty(g)&&f.domainList.push(g);return f});
(function(b,d){function e(c){return!b(c).parents().andSelf().filter(function(){return b.curCSS(this,"visibility")==="hidden"||b.expr.filters.hidden(this)}).length}b.ui=b.ui||{};if(!b.ui.version){b.extend(b.ui,{version:"1.8.6",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});b.fn.extend({_focus:b.fn.focus,focus:function(c,a){return typeof c==="number"?this.each(function(){var f=this;setTimeout(function(){b(f).focus();a&&a.call(f)},c)}):this._focus.apply(this,arguments)},scrollParent:function(){var c;c=b.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.curCSS(this,
"position",1))&&/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!c.length?b(document):c},zIndex:function(c){if(c!==d)return this.css("zIndex",c);if(this.length){c=b(this[0]);for(var a;c.length&&c[0]!==document;){a=c.css("position");
if(a==="absolute"||a==="relative"||a==="fixed"){a=parseInt(c.css("zIndex"),10);if(!isNaN(a)&&a!==0)return a}c=c.parent()}}return 0},disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(c){c.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});b.each(["Width","Height"],function(c,a){function f(j,p,q,D){b.each(g,function(){p-=parseFloat(b.curCSS(j,"padding"+this,true))||0;if(q)p-=parseFloat(b.curCSS(j,
"border"+this+"Width",true))||0;if(D)p-=parseFloat(b.curCSS(j,"margin"+this,true))||0});return p}var g=a==="Width"?["Left","Right"]:["Top","Bottom"],h=a.toLowerCase(),i={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+a]=function(j){if(j===d)return i["inner"+a].call(this);return this.each(function(){b(this).css(h,f(this,j)+"px")})};b.fn["outer"+a]=function(j,p){if(typeof j!=="number")return i["outer"+a].call(this,j);return this.each(function(){b(this).css(h,
f(this,j,true,p)+"px")})}});b.extend(b.expr[":"],{data:function(c,a,f){return!!b.data(c,f[3])},focusable:function(c){var a=c.nodeName.toLowerCase(),f=b.attr(c,"tabindex");if("area"===a){a=c.parentNode;f=a.name;if(!c.href||!f||a.nodeName.toLowerCase()!=="map")return false;c=b("img[usemap=#"+f+"]")[0];return!!c&&e(c)}return(/input|select|textarea|button|object/.test(a)?!c.disabled:"a"==a?c.href||!isNaN(f):!isNaN(f))&&e(c)},tabbable:function(c){var a=b.attr(c,"tabindex");return(isNaN(a)||a>=0)&&b(c).is(":focusable")}});
b(function(){var c=document.body,a=c.appendChild(a=document.createElement("div"));b.extend(a.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});b.support.minHeight=a.offsetHeight===100;b.support.selectstart="onselectstart"in a;c.removeChild(a).style.display="none"});b.extend(b.ui,{plugin:{add:function(c,a,f){c=b.ui[c].prototype;for(var g in f){c.plugins[g]=c.plugins[g]||[];c.plugins[g].push([a,f[g]])}},call:function(c,a,f){if((a=c.plugins[a])&&c.element[0].parentNode)for(var g=0;g<a.length;g++)c.options[a[g][0]]&&
a[g][1].apply(c.element,f)}},contains:function(c,a){return document.compareDocumentPosition?c.compareDocumentPosition(a)&16:c!==a&&c.contains(a)},hasScroll:function(c,a){if(b(c).css("overflow")==="hidden")return false;a=a&&a==="left"?"scrollLeft":"scrollTop";var f=false;if(c[a]>0)return true;c[a]=1;f=c[a]>0;c[a]=0;return f},isOverAxis:function(c,a,f){return c>a&&c<a+f},isOver:function(c,a,f,g,h,i){return b.ui.isOverAxis(c,f,h)&&b.ui.isOverAxis(a,g,i)}})}})(jQuery);
(function(b,d){if(b.cleanData){var e=b.cleanData;b.cleanData=function(a){for(var f=0,g;(g=a[f])!=null;f++)b(g).triggerHandler("remove");e(a)}}else{var c=b.fn.remove;b.fn.remove=function(a,f){return this.each(function(){if(!f)if(!a||b.filter(a,[this]).length)b("*",this).add([this]).each(function(){b(this).triggerHandler("remove")});return c.call(b(this),a,f)})}}b.widget=function(a,f,g){var h=a.split(".")[0],i;a=a.split(".")[1];i=h+"-"+a;if(!g){g=f;f=b.Widget}b.expr[":"][i]=function(j){return!!b.data(j,
a)};b[h]=b[h]||{};b[h][a]=function(j,p){arguments.length&&this._createWidget(j,p)};f=new f;f.options=b.extend(true,{},f.options);b[h][a].prototype=b.extend(true,f,{namespace:h,widgetName:a,widgetEventPrefix:b[h][a].prototype.widgetEventPrefix||a,widgetBaseClass:i},g);b.widget.bridge(a,b[h][a])};b.widget.bridge=function(a,f){b.fn[a]=function(g){var h=typeof g==="string",i=Array.prototype.slice.call(arguments,1),j=this;g=!h&&i.length?b.extend.apply(null,[true,g].concat(i)):g;if(h&&g.charAt(0)==="_")return j;
h?this.each(function(){var p=b.data(this,a),q=p&&b.isFunction(p[g])?p[g].apply(p,i):p;if(q!==p&&q!==d){j=q;return false}}):this.each(function(){var p=b.data(this,a);p?p.option(g||{})._init():b.data(this,a,new f(g,this))});return j}};b.Widget=function(a,f){arguments.length&&this._createWidget(a,f)};b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(a,f){b.data(f,this.widgetName,this);this.element=b(f);this.options=b.extend(true,{},this.options,
this._getCreateOptions(),a);var g=this;this.element.bind("remove."+this.widgetName,function(){g.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return b.metadata&&b.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(a,f){var g=a;if(arguments.length===0)return b.extend({},this.options);if(typeof a==="string"){if(f===d)return this.options[a];g={};g[a]=f}this._setOptions(g);return this},_setOptions:function(a){var f=this;b.each(a,function(g,h){f._setOption(g,h)});return this},_setOption:function(a,f){this.options[a]=f;if(a==="disabled")this.widget()[f?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",f);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(a,f,g){var h=this.options[a];f=b.Event(f);f.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase();g=g||{};if(f.originalEvent){a=b.event.props.length;for(var i;a;){i=b.event.props[--a];f[i]=f.originalEvent[i]}}this.element.trigger(f,g);return!(b.isFunction(h)&&h.call(this.element[0],f,g)===false||f.isDefaultPrevented())}}})(jQuery);
(function(b,d){function e(){return++a}function c(){return++f}var a=0,f=0;b.widget("ui.tabs",{options:{add:null,ajaxOptions:null,cache:false,cookie:null,collapsible:false,disable:null,disabled:[],enable:null,event:"click",fx:null,idPrefix:"ui-tabs-",load:null,panelTemplate:"<div></div>",remove:null,select:null,show:null,spinner:"<em>Loading&#8230;</em>",tabTemplate:"<li><a href='#{href}'><span>#{label}</span></a></li>"},_create:function(){this._tabify(true)},_setOption:function(g,h){if(g=="selected")this.options.collapsible&&
h==this.options.selected||this.select(h);else{this.options[g]=h;this._tabify()}},_tabId:function(g){return g.title&&g.title.replace(/\s/g,"_").replace(/[^\w\u00c0-\uFFFF-]/g,"")||this.options.idPrefix+e()},_sanitizeSelector:function(g){return g.replace(/:/g,"\\:")},_cookie:function(){var g=this.cookie||(this.cookie=this.options.cookie.name||"ui-tabs-"+c());return b.cookie.apply(null,[g].concat(b.makeArray(arguments)))},_ui:function(g,h){return{tab:g,panel:h,index:this.anchors.index(g)}},_cleanup:function(){this.lis.filter(".ui-state-processing").removeClass("ui-state-processing").find("span:data(label.tabs)").each(function(){var g=
b(this);g.html(g.data("label.tabs")).removeData("label.tabs")})},_tabify:function(g){function h(w,v){w.css("display","");!b.support.opacity&&v.opacity&&w[0].style.removeAttribute("filter")}var i=this,j=this.options,p=/^#.+/;this.list=this.element.find("ol,ul").eq(0);this.lis=b(" > li:has(a[href])",this.list);this.anchors=this.lis.map(function(){return b("a",this)[0]});this.panels=b([]);this.anchors.each(function(w,v){var A=b(v).attr("href"),I=A.split("#")[0],O;if(I&&(I===location.toString().split("#")[0]||
(O=b("base")[0])&&I===O.href)){A=v.hash;v.href=A}if(p.test(A))i.panels=i.panels.add(i._sanitizeSelector(A));else if(A&&A!=="#"){b.data(v,"href.tabs",A);b.data(v,"load.tabs",A.replace(/#.*$/,""));A=i._tabId(v);v.href="#"+A;v=b("#"+A);if(!v.length){v=b(j.panelTemplate).attr("id",A).addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").insertAfter(i.panels[w-1]||i.list);v.data("destroy.tabs",true)}i.panels=i.panels.add(v)}else j.disabled.push(w)});if(g){this.element.addClass("ui-tabs ui-widget ui-widget-content ui-corner-all");
this.list.addClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.lis.addClass("ui-state-default ui-corner-top");this.panels.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom");if(j.selected===d){location.hash&&this.anchors.each(function(w,v){if(v.hash==location.hash){j.selected=w;return false}});if(typeof j.selected!=="number"&&j.cookie)j.selected=parseInt(i._cookie(),10);if(typeof j.selected!=="number"&&this.lis.filter(".ui-tabs-selected").length)j.selected=
this.lis.index(this.lis.filter(".ui-tabs-selected"));j.selected=j.selected||(this.lis.length?0:-1)}else if(j.selected===null)j.selected=-1;j.selected=j.selected>=0&&this.anchors[j.selected]||j.selected<0?j.selected:0;j.disabled=b.unique(j.disabled.concat(b.map(this.lis.filter(".ui-state-disabled"),function(w){return i.lis.index(w)}))).sort();b.inArray(j.selected,j.disabled)!=-1&&j.disabled.splice(b.inArray(j.selected,j.disabled),1);this.panels.addClass("ui-tabs-hide");this.lis.removeClass("ui-tabs-selected ui-state-active");
if(j.selected>=0&&this.anchors.length){b(i._sanitizeSelector(i.anchors[j.selected].hash)).removeClass("ui-tabs-hide");this.lis.eq(j.selected).addClass("ui-tabs-selected ui-state-active");i.element.queue("tabs",function(){i._trigger("show",null,i._ui(i.anchors[j.selected],b(i._sanitizeSelector(i.anchors[j.selected].hash))))});this.load(j.selected)}b(window).bind("unload",function(){i.lis.add(i.anchors).unbind(".tabs");i.lis=i.anchors=i.panels=null})}else j.selected=this.lis.index(this.lis.filter(".ui-tabs-selected"));
this.element[j.collapsible?"addClass":"removeClass"]("ui-tabs-collapsible");j.cookie&&this._cookie(j.selected,j.cookie);g=0;for(var q;q=this.lis[g];g++)b(q)[b.inArray(g,j.disabled)!=-1&&!b(q).hasClass("ui-tabs-selected")?"addClass":"removeClass"]("ui-state-disabled");j.cache===false&&this.anchors.removeData("cache.tabs");this.lis.add(this.anchors).unbind(".tabs");if(j.event!=="mouseover"){var D=function(w,v){v.is(":not(.ui-state-disabled)")&&v.addClass("ui-state-"+w)},G=function(w,v){v.removeClass("ui-state-"+
w)};this.lis.bind("mouseover.tabs",function(){D("hover",b(this))});this.lis.bind("mouseout.tabs",function(){G("hover",b(this))});this.anchors.bind("focus.tabs",function(){D("focus",b(this).closest("li"))});this.anchors.bind("blur.tabs",function(){G("focus",b(this).closest("li"))})}var K,N;if(j.fx)if(b.isArray(j.fx)){K=j.fx[0];N=j.fx[1]}else K=N=j.fx;var y=N?function(w,v){b(w).closest("li").addClass("ui-tabs-selected ui-state-active");v.hide().removeClass("ui-tabs-hide").animate(N,N.duration||"normal",
function(){h(v,N);i._trigger("show",null,i._ui(w,v[0]))})}:function(w,v){b(w).closest("li").addClass("ui-tabs-selected ui-state-active");v.removeClass("ui-tabs-hide");i._trigger("show",null,i._ui(w,v[0]))},z=K?function(w,v){v.animate(K,K.duration||"normal",function(){i.lis.removeClass("ui-tabs-selected ui-state-active");v.addClass("ui-tabs-hide");h(v,K);i.element.dequeue("tabs")})}:function(w,v){i.lis.removeClass("ui-tabs-selected ui-state-active");v.addClass("ui-tabs-hide");i.element.dequeue("tabs")};
this.anchors.bind(j.event+".tabs",function(){var w=this,v=b(w).closest("li"),A=i.panels.filter(":not(.ui-tabs-hide)"),I=b(i._sanitizeSelector(w.hash));if(v.hasClass("ui-tabs-selected")&&!j.collapsible||v.hasClass("ui-state-disabled")||v.hasClass("ui-state-processing")||i.panels.filter(":animated").length||i._trigger("select",null,i._ui(this,I[0]))===false){this.blur();return false}j.selected=i.anchors.index(this);i.abort();if(j.collapsible)if(v.hasClass("ui-tabs-selected")){j.selected=-1;j.cookie&&
i._cookie(j.selected,j.cookie);i.element.queue("tabs",function(){z(w,A)}).dequeue("tabs");this.blur();return false}else if(!A.length){j.cookie&&i._cookie(j.selected,j.cookie);i.element.queue("tabs",function(){y(w,I)});i.load(i.anchors.index(this));this.blur();return false}j.cookie&&i._cookie(j.selected,j.cookie);if(I.length){A.length&&i.element.queue("tabs",function(){z(w,A)});i.element.queue("tabs",function(){y(w,I)});i.load(i.anchors.index(this))}else throw"jQuery UI Tabs: Mismatching fragment identifier.";
b.browser.msie&&this.blur()});this.anchors.bind("click.tabs",function(){return false})},_getIndex:function(g){if(typeof g=="string")g=this.anchors.index(this.anchors.filter("[href$="+g+"]"));return g},destroy:function(){var g=this.options;this.abort();this.element.unbind(".tabs").removeClass("ui-tabs ui-widget ui-widget-content ui-corner-all ui-tabs-collapsible").removeData("tabs");this.list.removeClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.anchors.each(function(){var h=
b.data(this,"href.tabs");if(h)this.href=h;var i=b(this).unbind(".tabs");b.each(["href","load","cache"],function(j,p){i.removeData(p+".tabs")})});this.lis.unbind(".tabs").add(this.panels).each(function(){b.data(this,"destroy.tabs")?b(this).remove():b(this).removeClass("ui-state-default ui-corner-top ui-tabs-selected ui-state-active ui-state-hover ui-state-focus ui-state-disabled ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide")});g.cookie&&this._cookie(null,g.cookie);return this},add:function(g,
h,i){if(i===d)i=this.anchors.length;var j=this,p=this.options;h=b(p.tabTemplate.replace(/#\{href\}/g,g).replace(/#\{label\}/g,h));g=!g.indexOf("#")?g.replace("#",""):this._tabId(b("a",h)[0]);h.addClass("ui-state-default ui-corner-top").data("destroy.tabs",true);var q=b("#"+g);q.length||(q=b(p.panelTemplate).attr("id",g).data("destroy.tabs",true));q.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide");if(i>=this.lis.length){h.appendTo(this.list);q.appendTo(this.list[0].parentNode)}else{h.insertBefore(this.lis[i]);
q.insertBefore(this.panels[i])}p.disabled=b.map(p.disabled,function(D){return D>=i?++D:D});this._tabify();if(this.anchors.length==1){p.selected=0;h.addClass("ui-tabs-selected ui-state-active");q.removeClass("ui-tabs-hide");this.element.queue("tabs",function(){j._trigger("show",null,j._ui(j.anchors[0],j.panels[0]))});this.load(0)}this._trigger("add",null,this._ui(this.anchors[i],this.panels[i]));return this},remove:function(g){g=this._getIndex(g);var h=this.options,i=this.lis.eq(g).remove(),j=this.panels.eq(g).remove();
if(i.hasClass("ui-tabs-selected")&&this.anchors.length>1)this.select(g+(g+1<this.anchors.length?1:-1));h.disabled=b.map(b.grep(h.disabled,function(p){return p!=g}),function(p){return p>=g?--p:p});this._tabify();this._trigger("remove",null,this._ui(i.find("a")[0],j[0]));return this},enable:function(g){g=this._getIndex(g);var h=this.options;if(b.inArray(g,h.disabled)!=-1){this.lis.eq(g).removeClass("ui-state-disabled");h.disabled=b.grep(h.disabled,function(i){return i!=g});this._trigger("enable",null,
this._ui(this.anchors[g],this.panels[g]));return this}},disable:function(g){g=this._getIndex(g);var h=this.options;if(g!=h.selected){this.lis.eq(g).addClass("ui-state-disabled");h.disabled.push(g);h.disabled.sort();this._trigger("disable",null,this._ui(this.anchors[g],this.panels[g]))}return this},select:function(g){g=this._getIndex(g);if(g==-1)if(this.options.collapsible&&this.options.selected!=-1)g=this.options.selected;else return this;this.anchors.eq(g).trigger(this.options.event+".tabs");return this},
load:function(g){g=this._getIndex(g);var h=this,i=this.options,j=this.anchors.eq(g)[0],p=b.data(j,"load.tabs");this.abort();if(!p||this.element.queue("tabs").length!==0&&b.data(j,"cache.tabs"))this.element.dequeue("tabs");else{this.lis.eq(g).addClass("ui-state-processing");if(i.spinner){var q=b("span",j);q.data("label.tabs",q.html()).html(i.spinner)}this.xhr=b.ajax(b.extend({},i.ajaxOptions,{url:p,success:function(D,G){b(h._sanitizeSelector(j.hash)).html(D);h._cleanup();i.cache&&b.data(j,"cache.tabs",
true);h._trigger("load",null,h._ui(h.anchors[g],h.panels[g]));try{i.ajaxOptions.success(D,G)}catch(K){}},error:function(D,G){h._cleanup();h._trigger("load",null,h._ui(h.anchors[g],h.panels[g]));try{i.ajaxOptions.error(D,G,g,j)}catch(K){}}}));h.element.dequeue("tabs");return this}},abort:function(){this.element.queue([]);this.panels.stop(false,true);this.element.queue("tabs",this.element.queue("tabs").splice(-2,2));if(this.xhr){this.xhr.abort();delete this.xhr}this._cleanup();return this},url:function(g,
h){this.anchors.eq(g).removeData("cache.tabs").data("load.tabs",h);return this},length:function(){return this.anchors.length}});b.extend(b.ui.tabs,{version:"1.8.6"});b.extend(b.ui.tabs.prototype,{rotation:null,rotate:function(g,h){var i=this,j=this.options,p=i._rotate||(i._rotate=function(q){clearTimeout(i.rotation);i.rotation=setTimeout(function(){var D=j.selected;i.select(++D<i.anchors.length?D:0)},g);q&&q.stopPropagation()});h=i._unrotate||(i._unrotate=!h?function(q){q.clientX&&i.rotate(null)}:
function(){t=j.selected;p()});if(g){this.element.bind("tabsshow",p);this.anchors.bind(j.event+".tabs",h);p()}else{clearTimeout(i.rotation);this.element.unbind("tabsshow",p);this.anchors.unbind(j.event+".tabs",h);delete this._rotate;delete this._unrotate}return this}})})(jQuery);define("jquery-ui-1.8.6.custom.min",function(){});
(function(b){var d=document.documentElement.style,e="textOverflow"in d||"OTextOverflow"in d,c=function(a,f){var g=0,h=[],i=function(j){var p=0,q;if(!(g>f))for(p=0;p<j.length;p+=1)if(j[p].nodeType===1){q=j[p].cloneNode(false);h[h.length-1].appendChild(q);h.push(q);i(j[p].childNodes);h.pop()}else if(j[p].nodeType===3){if(g+j[p].length<f)h[h.length-1].appendChild(j[p].cloneNode(false));else{q=j[p].cloneNode(false);q.textContent=b.trim(q.textContent.substring(0,f-g));h[h.length-1].appendChild(q)}g+=j[p].length}else h.appendChild(j[p].cloneNode(false))};
h.push(a.cloneNode(false));i(a.childNodes);return b(h.pop().childNodes)};b.extend(b.fn,{textOverflow:function(a,f){var g=a||"&#x2026;";return e?this:this.each(function(){var h=b(this),i=h.clone(),j=h.clone(),p=h.text(),q=h.width(),D=0,G=0,K=p.length,N=function(){if(q!==h.width()){h.replaceWith(j);h=j;j=h.clone();h.textOverflow(a,false);q=h.width()}};h.after(i.hide().css({position:"absolute",width:"auto",overflow:"visible","max-width":"inherit"}));if(i.width()>q){for(;D<K;){G=Math.floor(D+(K-D)/2);
i.empty().append(c(j.get(0),G)).append(g);if(i.width()<q)D=G+1;else K=G}D<p.length&&h.empty().append(c(j.get(0),D-1)).append(g)}i.remove();f&&setInterval(N,200)})}})})(jQuery);define("jquery.textOverflow",function(){});
define("index",["require","jquery","blade/fn","rdapi","oauth","blade/jig","blade/url","placeholder","TextCounter","AutoComplete","dispatch","accounts","storage","services","blade/object","jquery-ui-1.8.6.custom.min","jquery.textOverflow"],function(b,d,e,c,a,f,g,h,i,j,p,q,D,G,K){function N(n){return n?n.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"):n}function y(){p.pub("hide")}function z(){C.addClass("hidden");d("div.status").addClass("hidden");h()}function w(){var n=o&&o.domain||
"twitter.com",x=r.siteName,E=r.url||"",H=E.indexOf("//")+2;d("#statusShared").empty().append(f("#sharedTemplate",{domain:x||E.slice(H,E.indexOf("/",H)),service:m[n].name,href:m[n].serviceUrl})).find(".shareTitle").textOverflow(null,true);l("statusShared",true)}function v(n,x){d("#captchaImage").attr("src",n.imageurl);x&&d("#captchaMsg").text(x.message);d("#captchaSound").attr("src",n.audiourl);l("statusCaptcha",false)}function A(){var n={link:o.link,domain:o.domain,formData:m[o.domain].getFormData()};
J.sessionRestore=JSON.stringify(n);l("statusAuth")}function I(){l("statusSharing");m[o.domain].validate(o)?c("send",{type:"POST",data:o,success:function(n){if(n.error&&n.error.status){var x=n.error.status;if(x===401||x===535)A();else if(n.error.code==="Client.HumanVerificationRequired")v(n.error.detail);else n.error.code==="Client.WrongInput"?v(n.error.detail,n.error):l("statusError",n.error.message)}else if(n.error)l("statusError",n.error.message);else{J.lastSelection=m[o.domain].type;w()}delete J.sessionRestore},
error:function(n,x,E){if(n.status===403)A();else n.status===503?l("statusServerBusy"):l("statusError",E)}}):l("statusToError")}function O(n){var x=G.domains[n],E=d("#"+x.type).find('[name="to"]')[0],H=x.getContacts(J);H||(H=[]);if(!x.autoCompleteWidget)x.autoCompleteWidget=new j(E);n==="google.com"&&p.pub("autoCompleteData",H)}function aa(n,x){var E=x.accounts[0],H=G.domains[E.domain];H.getContacts(J)?O(E.domain):c("contacts/"+E.domain,{type:"POST",data:{username:E.username,userid:E.userid,startindex:0,
maxresults:500},success:function(L){if(L&&!L.error){var M=[];M=H.get36FormattedContacts(L.result.entry);H.setContacts(J,M);O(E.domain)}}})}function U(n,x){var E=n="",H=true,L="",M=x.panel.id,F=d(".user-info");if(M!=="debug"){n=d(x.panel).find("div.user img.avatar").attr("src");E=d(x.panel).find("div.user .username").text();H=d(x.panel).find("div.user").hasClass("inactive");L=d(x.panel).find("div.user input[type='hidden'][name='domain']").val()}d(".user-info img.avatar").attr("src",n);n?F.show():F.hide();
d(".user-info .status").toggleClass("inactive",H);d(".user-info .username").text(E);d(".user-info").attr("data-domain",L)}function W(n,x){d(function(){var E=x.displayName,H=x.accounts[0],L=x.photos&&x.photos[0]&&x.photos[0].value,M=d("#"+n),F;if((F=H.username)&&F!==E)E=E+" <"+F+">";d("."+n+"Tab").removeClass("hidden");E&&M.find(".username").text(E);L&&M.find(".avatar").attr("src",L);M.find('input[name="userid"]').val(H.userid);M.find('input[name="username"]').val(H.username);M.find("div.user").removeClass("inactive")})}
function V(){var n,x;if(J.lastSelection)n="#"+J.lastSelection;else if(P&&P.length){x=P[0].accounts[0].domain;if(m[x])if(x=m[x].type)n="#"+x}return n}function Z(){d(".ui-tabs-nav > li").removeClass("first").removeClass("last").filter(function(){var n=d(this),x=n.hasClass("hidden");n=n.hasClass("debugTab");return!x&&!n}).first().addClass("first").end().last().addClass("last")}function k(n){var x=false,E={},H=J.sessionRestore,L;n&&n.length&&n.forEach(function(M){var F=M.accounts[0].domain;if(F&&m[F]){x||
(x=m[F].type===J.lastSelection);E[m[F].type]=M}});!x&&!J.accountAdded&&J.lastSelection&&delete J.lastSelection;J.accountAdded&&delete J.accountAdded;for(L in E)if(E.hasOwnProperty(L)){W(L,E[L]);aa(L,E[L])}if(H){H=JSON.parse(H);if(r.link!==H.link){H=null;delete J.sessionRestore}if(H){m[H.domain].setFormData(H.formData);h()}}if(R){n=V();u.tabs("select",n);U(null,{panel:d(n)[0]})}Z()}G.isFF36=true;var l,m=G.domains;b=location.href.split("#")[1];var o,s,r={},u,B,C,R=true,S,P,ba,J=D();K.mixin(G.svcBaseProto,
{validate:function(){if(this.counter)return!this.counter||!this.counter.isOver();return true},startCounter:function(n){if(!(this.textLimit<1)){if(!this.counter)this.counter=new i(d("#"+this.type+" textarea.message"),d("#"+this.type+" .counter"),this.textLimit-this.urlsize);this.counter.updateLimit(n.shortUrl?this.textLimit-(n.shortUrl.length+1):this.textLimit-this.urlsize)}},getFormData:function(){var n=d("#"+this.type);return{to:n.find('[name="to"]').val().trim()||"",subject:n.find('[name="subject"]').val().trim()||
"",message:n.find("textarea.message").val().trim()||"",picture:n.find('[name="picture"]').val().trim()||"",canonicalUrl:n.find('[name="link"]').val().trim()||"",title:n.find('[name="title"]').val().trim()||"",description:n.find('[name="description"]').val().trim()||"",shortUrl:n.find('[name="surl"]').val().trim()||""}},setFormData:function(n){var x=d("#"+this.type);n.to&&x.find('[name="to"]').val(n.to);n.subject&&x.find('[name="subject"]').val(n.subject);n.message&&x.find("textarea.message").val(n.message);
n.previews&&n.previews.length&&x.find('[name="picture"]').val(n.previews[0]);if(n.canonicalUrl||n.url)x.find('[name="link"]').val(n.canonicalUrl||n.url);n.title&&x.find('[name="title"]').val(n.title);n.description&&x.find('[name="description"]').val(n.description);n.shortUrl&&x.find('[name="surl"]').val(n.shortUrl);this.startCounter(n)}});f.addFn({profilePic:function(n){return n&&n[0]&&n[0].value||"i/face2.png"},serviceName:function(n){return m[n].name}});window.closeShare=y;l=function(n,x){d("div.status").addClass("hidden");
C.removeClass("hidden");d("#"+n).removeClass("hidden");if(x===true)setTimeout(function(){p.pub("success",{domain:o.domain,username:o.username,userid:o.userid})},2E3);else x&&d("#"+n+"Message").text(x)};window.showStatus=l;window.showStatusShared=w;window.handleCaptcha=v;if(b){g=g.queryToObject(b);if(g.options)r=JSON.parse(g.options)}r.prefs=r.prefs||{};if(!r.title)r.title=r.url;if(!r.prefs.system)r.prefs.system="prod";if(r.version)J.extensionVersion=r.version;if(r.prefs)for(s in r.prefs)if(r.prefs.hasOwnProperty(s))J["prefs."+
s]=r.prefs[s];if(s=J.newTimerV2){s=JSON.parse(s);if((new Date).getTime()-s<2592E5)ba=true}else{J.newTimerV1=(new Date).getTime();ba=true}d(function(){var n,x=J.sessionRestore,E,H="",L="",M;G.domainList.forEach(function(F){var Q=G.domains[F];Q.domain=F;if(F==="linkedin.com")Q.features.subject=false;H+=f("#tabsTemplate",Q);L+=f("#panelsTemplate",Q)});d(".nav .debugTab").before(H);d("#tabs #debug").before(L);n=d("img.thumb");B=d("body");C=d("#clickBlock");r.prefs.system&&d(document.documentElement).addClass(r.prefs.system);
if(r.prefs.system==="dev"){d("#debugOutput").val(JSON.stringify(r));d("#debugCurrentLocation").val(location.href)}ba&&d("#newLink").removeClass("hidden");B.delegate("#statusAuthButton, .statusErrorButton","click",function(){z()}).delegate(".statusErrorCloseButton","click",function(){y()}).delegate(".statusResetErrorButton","click",function(){location.reload()}).delegate(".nav .close","click",y);d("#authOkButton").click(function(){a(o.domain,function(F){if(F){q.clear();q()}else l("statusOAuthFailed")})});
d("#captchaButton").click(function(){z();C.removeClass("hidden");o.HumanVerification=d("#captcha").attr("value");o.HumanVerificationImage=d("#captchaImage").attr("src");I()});q.onChange();if(D.type==="memory")l("statusEnableLocalStorage");else{q(function(F){P=F;R=false;k(P);R=true;if(S=V()){d("."+S.slice(1)+"Tab").addClass("ui-tabs-selected ui-state-active");E=d(S);E.removeClass("ui-tabs-hide");U(null,{panel:E[0]});u=d("#tabs");u.tabs({fx:{opacity:"toggle",duration:100}});u.bind("tabsselect",U);u.removeClass("invisible");
B.removeClass("loading");Z()}else l("statusSettings")},function(F,Q,T){F.status===503?l("statusServerBusyClose"):l("statusServerError",T)});for(M in G.domains)G.domains.hasOwnProperty(M)&&G.domains[M].setFormData(r);if(x)x=JSON.parse(x);r.title&&d(".title").text(r.title);r.description&&d(".description").text(r.description);if(r.previews&&r.previews.length){x=N(r.previews[0]);n.attr("src",x)}else r.thumbnail&&n.attr("src",N(r.thumbnail));d(".title").textOverflow(null,true);d(".description").textOverflow(null,
true);d(".url").textOverflow(null,true);d(".surl").textOverflow(null,true);d("form.messageForm").submit(function(F){F=F.target;var Q,T,$;o={};d.each(F.elements,function(X,Y){X=Y.value.trim();if(Y.getAttribute("placeholder")===X)X="";Y.value=X;if(Y.value)o[Y.name]=Y.value});F=G.domains[o.domain];if(r.shortUrl)o.shorturl=r.shortUrl;else if(F.shorten)o.shorten=true;if(o.to){Q=F.getContacts(J);$=[];if(Q){F=o.to.split(",");F.forEach(function(X){if((T=Q[X.trim()])&&!T.email)$.push(T.userid?T.userid:T.username)})}if($.length>
0)o.to=$.join(", ")}I();return false}).each(function(F,Q){h(Q)})}})});