/*
 blade/func Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/object Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/jig Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/array Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/url Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
*/
define("blade/fn",[],function(){var b=Array.prototype.slice,d=Object.prototype.toString;return{is:function(f){return d.call(f)==="[object Function]"},bind:function(f,c){if(!c)return f;if(typeof c==="string")c=f[c];var a=b.call(arguments,2);return function(){return c.apply(f,a.concat(b.call(arguments,0)))}}}});
define("blade/object",["./fn"],function(b){function d(){}var f={},c=function(a,e,g){a=a||{};var h,i=c.create(a.prototype,e);a=function(k,p,q){return i[p].apply(k,q)};e=c.create(i);c.mixin(e,b.is(g)?g(a):g,true);h=function(){if(!(this instanceof h))throw new Error('blade/object: constructor function called without "new" in front');this.init&&this.init.apply(this,arguments)};h.prototype=e;return h};c.create=function(a,e){d.prototype=a;a=new d;var g,h;d.prototype=null;if(e)for(g=0;h=e[g];g++)c.mixin(a,
h);return a};c.mixin=function(a,e,g){for(var h in e)if(!(h in f)&&(!(h in a)||g))a[h]=e[h]};return c});
define("blade/jig",["require","./object"],function(b,d){function f(j){return G.call(j)==="[object Array]"}function c(j,l,m){l=l;var o,s;for(o=0;l&&(s=j[o]);o++)l=typeof l==="object"&&s in l?l[s]:m&&o===0&&s in m?m[s]:undefined;return l}function a(j){return j?parseInt(j,10):0}function e(j,l,m){var o=/\[([\w0-9\.'":]+)\]/,s=j,r=l,u=true,B,C;if(j===z)return l;if(v.test(j))return a(j);if(j==="")return"";B=j.charAt(0);if(B==="'"||B==="'")return j.substring(1,j.length-1);if((B=j.indexOf("("))!==-1){o=j.lastIndexOf(")");
u=j.substring(0,B);s=m.fn[u];if(!s){q.error("Cannot find function named: "+u+" for "+j);return""}u=j.substring(B+1,o);if(u.indexOf(",")!==-1){u=u.split(",");for(r=u.length-1;r>=0;r--)u[r]=e(u[r],l,m);s=s.apply(null,u)}else s=s(e(u,l,m));if(o<j.length-1){if(j.charAt(o+1)===".")o+=1;return e(j.substring(o+1,j.length),s,m)}else return s}for(;B=o.exec(s);){l=B[1].replace(/['"]/g,"");C=s.substring(0,B.index);s=s.substring(B.index+B[0].length,s.length);if(s.indexOf(".")===0)s=s.substring(1,s.length);r=
c(C.split("."),r,u?m.context:null);u=false;if(!r&&l){q.error('blade/jig: No property "'+l+'" on '+r);return""}if(l.indexOf(":")!==-1){B=l.split(":");l=a(B[0]);r=(B=a(B[1]))?r.slice(l,B):r.slice(l)}else{m.strict&&!(l in r)&&q.error('blade/jig: no property "'+l+'"');r=r[l]}r=r}s=s?c(s.split("."),r,u?m.context:null):r;m.strict&&s===undefined&&q.error('blade/jig: undefined value for property "'+j+'"');return s}function g(j,l){l=l||{};var m=q.cache(j,l);if(m===undefined&&typeof document!=="undefined"){(m=
document.getElementById(j))&&q.parse([m],l);m=q.cache(j,l)}if(m===undefined)throw new Error("blade/jig: no template or node with ID: "+j);return m}function h(j,l){for(var m=[],o=0,s=false,r=0,u,B,C,Q,R,P;(u=j.indexOf(l.startToken,o))!==-1;){u!==o&&m.push(j.substring(o,u));o=j.substring(u);if(B=l.endRegExp.exec(o)){o=u+B[0].length;C=j.substring(u+l.startToken.length,u+B[0].length-l.endToken.length).trim();C=K(C);if(A.test(C))throw new Error("blade/jig: end block tags should not be commented: "+C);
u=C.charAt(0);if(u==="]"&&r){s=C.substring(1).trim();if(s==="[")u=">";else{u=s.charAt(0);C=s}}if(u&&!l.propertyRegExp.test(u))C=C.substring(1).trim();else u="_default_";if(s=C.indexOf(l.rawHtmlToken)===0)C=C.substring(l.rawHtmlToken.length,C.length);if(u===N)s=true;C=C.split(l.argSeparator);Q=C[C.length-1];R=Q.charAt(Q.length-1);P=null;if(u==="]"){if(R!=="["){m.templateEnd=o;m.endControl=true}else m.templateEnd=o-B[0].length;return m}else if(R==="["){r||(r=T++);C[C.length-1]=Q.substring(0,Q.length-
1);P=h(j.substring(o),l);o+=P.templateEnd}if(u==="+")l.templates[C[0]]=P;else if(u!=="/"){if(C.length>1)for(B=C.length-1;B>=0;B--)if(C[B].charAt(C[B].length-1)===","){C[B]+=C[B+1];C.splice(B+1,1)}m.push({action:l.commands[u].action,useRawHtml:s,args:C,controlId:r,children:P})}if(P&&P.endControl)r=0}else{m.push(o);return m}}o!==j.length-1&&m.push(j.substring(o,j.length));return m}function i(j,l){var m,o=j.id;m=l.templates||I;if(m[o])return m[o];l.onBeforeParse&&l.onBeforeParse(j);if(j.nodeName.toUpperCase()===
"SCRIPT"){m=j.text.trim();j.parentNode&&j.parentNode.removeChild(j)}else{U.appendChild(j);j.removeAttribute("id");(m=(j.getAttribute("class")||"").trim())&&j.setAttribute("class",m.replace(Z,"$1$3"));m=U.innerHTML.replace(/%7B/g,"{").replace(/%7D/g,"}");U.removeChild(j)}j=q.compile(m,l);q.cache(o,j,l);return j}function k(j,l,m){var o="",s,r,u,B,C;if(typeof j==="string")o=j;else if(f(j))for(s=0;s<j.length;s++){u=j[s].controlId;if(!u||u!==r||!C){B=k(j[s],l,m);o+=B;if(u){r=u;C=B}}}else if(o=j.action(j.args,
l,m,j.children,k)){if(!j.useRawHtml&&!j.children)o=q.htmlEscape(o.toString())}else o="";if(m.attachData)if(w.test(o)){j="id"+aa++;o=o.replace(w,'$& data-blade-jig="'+j+'" ');V[j]=l}return o}function p(j){j.fn.jig=function(l,m){m=m||{};var o=this.selector;if(o.charAt(0)!=="#")throw new Error('blade/jig: only ID selectors, like "#something" are allowed with jig()');o=o.substring(1,o.length);(o=(m.templates||I)[o])||(o=i(this[0]));return j(q.render(o,l,m))}}var q,D,G=Object.prototype.toString,K=typeof decodeURIComponent===
"undefined"?function(){}:decodeURIComponent,N="#",y=/[_\[\^\w]/,z="_",w=/<\s*\w+/,v=/^\d+$/,A=/\/(\/)?\s*\]/,I={},O={openCurly:function(){return"{"},closeCurly:function(){return"}"},eq:function(j,l){return j===l},gt:function(j,l){return j>l},gte:function(j,l){return j>=l},lt:function(j,l){return j<l},lte:function(j,l){return j<=l},or:function(j,l){return j||l},and:function(j,l){return j&&l},is:function(j){return!!j},eachProp:function(j){var l,m=[];for(l in j)j.hasOwnProperty(l)&&m.push({prop:l,value:j[l]});
return m.sort(function(o,s){return o.prop>s.prop?1:-1})}},aa=1,T=1,V={},U=typeof document!=="undefined"&&document.createElement?document.createElement("div"):null,Z=/(\s*)(template)(\s*)/;D={_default_:{doc:"Property reference",action:function(j,l,m,o,s){var r=j[0]?e(j[0],l,m):l,u=j[1]?e(j[1],l,m):undefined,B="";if(j[1]){u=r===u;r=l}else u=r;if(u===false||u===null||u===undefined||f(u)&&!u.length)return"";else if(o)if(f(r))for(j=0;j<r.length;j++)B+=s(o,r[j],m);else{if(typeof r==="boolean")r=l;B=s(o,
r,m)}else B=r;return B}},"!":{doc:"Not",action:function(j,l,m,o,s){var r=e(j[0],l,m),u=j[1]?e(j[1],l,m):undefined;u=j[1]?r===u:r;if(o&&!u)return s(o,l,m);return""}},"#":{doc:"Template reference",action:function(j,l,m,o,s){o=g(j[0],m);l=e(j.length>1?j[1]:z,l,m);return s(o,l,m)}},".":{doc:"Variable declaration",action:function(j,l,m){m.context[j[0]]=e(j[1],l,m);return""}},">":{doc:"Else",action:function(j,l,m,o,s){if(o)return s(o,l,m);return""}}};q=function(j,l,m){if(typeof j==="string")if(j.charAt(0)===
"#"){j=j.substring(1,j.length);j=g(j,m)}else j=q.compile(j,m);return q.render(j,l,m)};q.htmlEscape=function(j){return j.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};q.compile=function(j,l){l=l||{};d.mixin(l,{startToken:"{",endToken:"}",rawHtmlToken:"^",propertyRegExp:y,commands:D,argSeparator:" ",templates:I});l.endRegExp=/[^\r\n]*?}/;T=1;return h(j,l)};q.parse=function(j,l){if(j&&!j.length){l=j;j=null}l=l||{};j=j||document.querySelectorAll('.template, script[type="text/template"]');
var m,o;for(o=j.length-1;o>-1&&(m=j[o]);o--)i(m,l)};q.render=function(j,l,m){var o,s="";m=m||{};d.mixin(m,{templates:I,attachData:false,strict:q.strict});if(m.fn)d.mixin(m.fn,O);else m.fn=O;m.context=m.context||d.create(l);if(f(l)){for(o=0;o<l.length;o++)s+=k(j,l[o],m);return s}return k(j,l,m)};q.strict=false;q.error=function(j){throw j;};q.addFn=function(j){d.mixin(O,j,true)};q.data=function(j,l){if(typeof j!=="string"){j.nodeType||(j=j[0]);j=j.getAttribute("data-blade-jig")}return l!==undefined?
(V[j]=l):V[j]};q.removeData=function(j){delete V[j]};q.getObject=e;q.cache=function(j,l,m){if(typeof l==="string")l=q.compile(l,m);if(!f(l)){m=l;l=undefined}m=m&&m.templates||I;if(l!==undefined)m[j]=l;return m[j]||I[j]};typeof jQuery!=="undefined"&&p(jQuery);return q});
define("friendly",["require","exports","module"],function(){var b={timestamp:function(d){return b.date(new Date(d*1E3))},date:function(d){var f=((new Date).getTime()-d.getTime())/1E3,c=Math.floor(f/86400),a={friendly:d.toLocaleDateString(),additional:d.toLocaleTimeString(),utc:d.toUTCString(),locale:d.toLocaleString()};if(c<0){a.friendly="in the future";return a}else if(isNaN(c)){a.friendly=a.additional="unknown";return a}if(c===0){if(f<60){a.friendly="just now";return a}if(f<150){a.friendly="a minute ago";
return a}if(f<3600){a.friendly=Math.floor(f/60)+" minutes ago";return a}if(f<7200){a.friendly="1 hour ago";return a}if(f<86400){a.friendly=Math.floor(f/3600)+" hours ago";return a}}if(c===1){a.friendly="yesterday";return a}if(c<7){a.friendly=c+" days ago";return a}if(c<8){a.friendly="last week";return a}if(c<31){a.friendly=Math.ceil(c/7)+" weeks ago";return a}if(c<62){a.friendly="a month ago";return a}if(c<365){a.friendly=Math.ceil(c/31)+" months ago";return a}if(c>=365&&c<730){a.additional=d.toLocaleDateString();
a.friendly="a year ago";return a}if(c>=365){a.additional=d.toLocaleDateString();a.friendly=Math.ceil(c/365)+" years ago";return a}return a},name:function(d){d=d.split(" ")[0];if(d.indexOf("@")!==-1)d=d.split("@")[0];d=d.replace(" ","");d=d.replace("'","");return d=d.replace('"',"")}};return b});
define("isoDate",[],function(){var b=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+\-](\d{2}):(\d{2}))|Z)?)?$/,d=function(f,c){var a=b.exec(f);f=null;var e,g;if(a){a.shift();a[1]&&a[1]--;if(a[6])a[6]*=1E3;if(c){c=new Date(c);["FullYear","Month","Date","Hours","Minutes","Seconds","Milliseconds"].map(function(h){return c["get"+h]()}).forEach(function(h,i){a[i]=a[i]||h})}f=new Date(a[0]||1970,a[1]||0,a[2]||1,a[3]||0,a[4]||0,a[5]||0,a[6]||0);if(a[0]<100)f.setFullYear(a[0]||
1970);e=0;g=a[7]&&a[7].charAt(0);if(g!=="Z"){e=(a[8]||0)*60+(Number(a[9])||0);if(g!=="-")e*=-1}if(g)e-=f.getTimezoneOffset();e&&f.setTime(f.getTime()+e*6E4)}return f};d.toIsoString=function(f,c){var a=function(i){return i<10?"0"+i:i},e,g,h;c=c||{};e=[];g=c.zulu?"getUTC":"get";h="";if(c.selector!=="time"){h=f[g+"FullYear"]();h=["0000".substr((h+"").length)+h,a(f[g+"Month"]()+1),a(f[g+"Date"]())].join("-")}e.push(h);if(c.selector!=="date"){h=[a(f[g+"Hours"]()),a(f[g+"Minutes"]()),a(f[g+"Seconds"]())].join(":");
g=f[g+"Milliseconds"]();if(c.milliseconds)h+="."+(g<100?"0":"")+a(g);if(c.zulu)h+="Z";else if(c.selector!=="time"){f=f.getTimezoneOffset();c=Math.abs(f);h+=(f>0?"-":"+")+a(Math.floor(c/60))+":"+a(c%60)}e.push(h)}return e.join("T")};return d});var EXPORTED_SYMBOLS=["hex_md5"],hexcase=0,b64pad="";function hex_md5(b){return rstr2hex(rstr_md5(str2rstr_utf8(b)))}function b64_md5(b){return rstr2b64(rstr_md5(str2rstr_utf8(b)))}function any_md5(b,d){return rstr2any(rstr_md5(str2rstr_utf8(b)),d)}
function hex_hmac_md5(b,d){return rstr2hex(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)))}function b64_hmac_md5(b,d){return rstr2b64(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)))}function any_hmac_md5(b,d,f){return rstr2any(rstr_hmac_md5(str2rstr_utf8(b),str2rstr_utf8(d)),f)}function md5_vm_test(){return hex_md5("abc").toLowerCase()=="900150983cd24fb0d6963f7d28e17f72"}function rstr_md5(b){return binl2rstr(binl_md5(rstr2binl(b),b.length*8))}
function rstr_hmac_md5(b,d){var f=rstr2binl(b);if(f.length>16)f=binl_md5(f,b.length*8);var c=Array(16);b=Array(16);for(var a=0;a<16;a++){c[a]=f[a]^909522486;b[a]=f[a]^1549556828}d=binl_md5(c.concat(rstr2binl(d)),512+d.length*8);return binl2rstr(binl_md5(b.concat(d),640))}function rstr2hex(b){for(var d=hexcase?"0123456789ABCDEF":"0123456789abcdef",f="",c,a=0;a<b.length;a++){c=b.charCodeAt(a);f+=d.charAt(c>>>4&15)+d.charAt(c&15)}return f}
function rstr2b64(b){for(var d="",f=b.length,c=0;c<f;c+=3)for(var a=b.charCodeAt(c)<<16|(c+1<f?b.charCodeAt(c+1)<<8:0)|(c+2<f?b.charCodeAt(c+2):0),e=0;e<4;e++)d+=c*8+e*6>b.length*8?b64pad:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>6*(3-e)&63);return d}
function rstr2any(b,d){var f=d.length,c,a,e,g,h,i=Array(Math.ceil(b.length/2));for(c=0;c<i.length;c++)i[c]=b.charCodeAt(c*2)<<8|b.charCodeAt(c*2+1);var k=Math.ceil(b.length*8/(Math.log(d.length)/Math.log(2)));b=Array(k);for(a=0;a<k;a++){h=Array();for(c=g=0;c<i.length;c++){g=(g<<16)+i[c];e=Math.floor(g/f);g-=e*f;if(h.length>0||e>0)h[h.length]=e}b[a]=g;i=h}f="";for(c=b.length-1;c>=0;c--)f+=d.charAt(b[c]);return f}
function str2rstr_utf8(b){for(var d="",f=-1,c,a;++f<b.length;){c=b.charCodeAt(f);a=f+1<b.length?b.charCodeAt(f+1):0;if(55296<=c&&c<=56319&&56320<=a&&a<=57343){c=65536+((c&1023)<<10)+(a&1023);f++}if(c<=127)d+=String.fromCharCode(c);else if(c<=2047)d+=String.fromCharCode(192|c>>>6&31,128|c&63);else if(c<=65535)d+=String.fromCharCode(224|c>>>12&15,128|c>>>6&63,128|c&63);else if(c<=2097151)d+=String.fromCharCode(240|c>>>18&7,128|c>>>12&63,128|c>>>6&63,128|c&63)}return d}
function str2rstr_utf16le(b){for(var d="",f=0;f<b.length;f++)d+=String.fromCharCode(b.charCodeAt(f)&255,b.charCodeAt(f)>>>8&255);return d}function str2rstr_utf16be(b){for(var d="",f=0;f<b.length;f++)d+=String.fromCharCode(b.charCodeAt(f)>>>8&255,b.charCodeAt(f)&255);return d}function rstr2binl(b){for(var d=Array(b.length>>2),f=0;f<d.length;f++)d[f]=0;for(f=0;f<b.length*8;f+=8)d[f>>5]|=(b.charCodeAt(f/8)&255)<<f%32;return d}
function binl2rstr(b){for(var d="",f=0;f<b.length*32;f+=8)d+=String.fromCharCode(b[f>>5]>>>f%32&255);return d}
function binl_md5(b,d){b[d>>5]|=128<<d%32;b[(d+64>>>9<<4)+14]=d;d=1732584193;for(var f=-271733879,c=-1732584194,a=271733878,e=0;e<b.length;e+=16){var g=d,h=f,i=c,k=a;d=md5_ff(d,f,c,a,b[e+0],7,-680876936);a=md5_ff(a,d,f,c,b[e+1],12,-389564586);c=md5_ff(c,a,d,f,b[e+2],17,606105819);f=md5_ff(f,c,a,d,b[e+3],22,-1044525330);d=md5_ff(d,f,c,a,b[e+4],7,-176418897);a=md5_ff(a,d,f,c,b[e+5],12,1200080426);c=md5_ff(c,a,d,f,b[e+6],17,-1473231341);f=md5_ff(f,c,a,d,b[e+7],22,-45705983);d=md5_ff(d,f,c,a,b[e+8],7,
1770035416);a=md5_ff(a,d,f,c,b[e+9],12,-1958414417);c=md5_ff(c,a,d,f,b[e+10],17,-42063);f=md5_ff(f,c,a,d,b[e+11],22,-1990404162);d=md5_ff(d,f,c,a,b[e+12],7,1804603682);a=md5_ff(a,d,f,c,b[e+13],12,-40341101);c=md5_ff(c,a,d,f,b[e+14],17,-1502002290);f=md5_ff(f,c,a,d,b[e+15],22,1236535329);d=md5_gg(d,f,c,a,b[e+1],5,-165796510);a=md5_gg(a,d,f,c,b[e+6],9,-1069501632);c=md5_gg(c,a,d,f,b[e+11],14,643717713);f=md5_gg(f,c,a,d,b[e+0],20,-373897302);d=md5_gg(d,f,c,a,b[e+5],5,-701558691);a=md5_gg(a,d,f,c,b[e+
10],9,38016083);c=md5_gg(c,a,d,f,b[e+15],14,-660478335);f=md5_gg(f,c,a,d,b[e+4],20,-405537848);d=md5_gg(d,f,c,a,b[e+9],5,568446438);a=md5_gg(a,d,f,c,b[e+14],9,-1019803690);c=md5_gg(c,a,d,f,b[e+3],14,-187363961);f=md5_gg(f,c,a,d,b[e+8],20,1163531501);d=md5_gg(d,f,c,a,b[e+13],5,-1444681467);a=md5_gg(a,d,f,c,b[e+2],9,-51403784);c=md5_gg(c,a,d,f,b[e+7],14,1735328473);f=md5_gg(f,c,a,d,b[e+12],20,-1926607734);d=md5_hh(d,f,c,a,b[e+5],4,-378558);a=md5_hh(a,d,f,c,b[e+8],11,-2022574463);c=md5_hh(c,a,d,f,b[e+
11],16,1839030562);f=md5_hh(f,c,a,d,b[e+14],23,-35309556);d=md5_hh(d,f,c,a,b[e+1],4,-1530992060);a=md5_hh(a,d,f,c,b[e+4],11,1272893353);c=md5_hh(c,a,d,f,b[e+7],16,-155497632);f=md5_hh(f,c,a,d,b[e+10],23,-1094730640);d=md5_hh(d,f,c,a,b[e+13],4,681279174);a=md5_hh(a,d,f,c,b[e+0],11,-358537222);c=md5_hh(c,a,d,f,b[e+3],16,-722521979);f=md5_hh(f,c,a,d,b[e+6],23,76029189);d=md5_hh(d,f,c,a,b[e+9],4,-640364487);a=md5_hh(a,d,f,c,b[e+12],11,-421815835);c=md5_hh(c,a,d,f,b[e+15],16,530742520);f=md5_hh(f,c,a,
d,b[e+2],23,-995338651);d=md5_ii(d,f,c,a,b[e+0],6,-198630844);a=md5_ii(a,d,f,c,b[e+7],10,1126891415);c=md5_ii(c,a,d,f,b[e+14],15,-1416354905);f=md5_ii(f,c,a,d,b[e+5],21,-57434055);d=md5_ii(d,f,c,a,b[e+12],6,1700485571);a=md5_ii(a,d,f,c,b[e+3],10,-1894986606);c=md5_ii(c,a,d,f,b[e+10],15,-1051523);f=md5_ii(f,c,a,d,b[e+1],21,-2054922799);d=md5_ii(d,f,c,a,b[e+8],6,1873313359);a=md5_ii(a,d,f,c,b[e+15],10,-30611744);c=md5_ii(c,a,d,f,b[e+6],15,-1560198380);f=md5_ii(f,c,a,d,b[e+13],21,1309151649);d=md5_ii(d,
f,c,a,b[e+4],6,-145523070);a=md5_ii(a,d,f,c,b[e+11],10,-1120210379);c=md5_ii(c,a,d,f,b[e+2],15,718787259);f=md5_ii(f,c,a,d,b[e+9],21,-343485551);d=safe_add(d,g);f=safe_add(f,h);c=safe_add(c,i);a=safe_add(a,k)}return Array(d,f,c,a)}function md5_cmn(b,d,f,c,a,e){return safe_add(bit_rol(safe_add(safe_add(d,b),safe_add(c,e)),a),f)}function md5_ff(b,d,f,c,a,e,g){return md5_cmn(d&f|~d&c,b,d,a,e,g)}function md5_gg(b,d,f,c,a,e,g){return md5_cmn(d&c|f&~c,b,d,a,e,g)}
function md5_hh(b,d,f,c,a,e,g){return md5_cmn(d^f^c,b,d,a,e,g)}function md5_ii(b,d,f,c,a,e,g){return md5_cmn(f^(d|~c),b,d,a,e,g)}function safe_add(b,d){var f=(b&65535)+(d&65535);return(b>>16)+(d>>16)+(f>>16)<<16|f&65535}function bit_rol(b,d){return b<<d|b>>>32-d}define("md5",function(){});
define("rdapi",["require","jquery","blade/object","blade/jig","friendly","isoDate","md5"],function(b,d,f,c,a,e){function g(y){if(typeof y==="string")y={template:y};else if(y.templateId)y.template=c.cache(y.templateId);if(!("attachData"in y))y.attachData=p.attachTemplateData;if(y.emptyTemplateId)y.emptyTemplate=c.cache(y.emptyTemplateId);return y}function h(){var y=D.exec(document.cookie);return y&&y[1]?y[1]:null}function i(y,z){z.url=N.baseUrl+N.apiPath+y;f.mixin(z,{limit:30,message_limit:3,dataType:"json",
error:function(A,I,O){throw O;}});var w=z.success,v=h();z.success=function(A){A&&A.contacts&&f.mixin(G,A.contacts,true);return w?w.apply(null,arguments):A};if(v)z.beforeSend=function(A){A.setRequestHeader(q,v)};d.ajax(z)}function k(y,z){var w=z.forId?document.getElementById(z.forId):null;if(w)w.innerHTML=y;z.onTemplateDone&&z.onTemplateDone(y);d(document).trigger("rdapi-done",w)}var p,q="X-CSRF",D=/csrf=([^\; ]+)/,G={},K={contact:function(y){return y.iid&&y.domain?G[y.iid]||{}:y},contactPhotoUrl:function(y){var z=
"i/face2.png",w,v;y=K.contact(y);if((w=y.photos)&&w.length){z=w[0].value;w.forEach(function(A){if(A.primary)z=A.value})}else if(y.emails&&y.emails.length){v=y.emails[0].value;y.emails.forEach(function(A){if(A.primary)v=A.value});z="http://www.gravatar.com/avatar/"+hex_md5(v)+"?s=24 &d=identicon"}return z},allMessages:function(y){return[y.topic].concat(y.messages||[])},friendlyDate:function(y){return a.date(e(y)).friendly},htmlBody:function(y){return c.htmlEscape(y).replace(/\n/g,"<br>")}},N={baseUrl:"/",
apiPath:"api/",saveTemplateData:true};c.addFn(K);p=function(y,z){z=g(z);f.mixin(z,{success:function(w){var v=z.template,A=z.emptyTemplate,I="";if(z.forId&&v){if(z.prop)w=c.getObject(z.prop,w,z);if(b.isArray(w))if(w.length)w.forEach(function(O){I+=c(v,O,z)});else I+=c(A,w,z);else I+=c(!w?A:v,w,z);k(I,z)}},error:function(w,v,A){if(z.emptyTemplate){w=c(z.emptyTemplate,A,z);k(w,z)}else throw A;}});i(y,z)};p.contactPhotoUrl=K.contactPhotoUrl;p.attachTemplateData=false;b.ready(function(){var y=[];c.parse({onBeforeParse:function(z){var w=
z.id,v=z.getAttribute("data-rdapi"),A=z.getAttribute("data-rdfor"),I=z.getAttribute("data-rdprop");v&&y.push({templateId:w,api:v,forId:A,prop:I});["data-rdapi","data-rdprop","data-rdfor"].forEach(function(O){z.removeAttribute(O)})}});y.forEach(function(z){p(z.api,z)})});return p});
define("oauth",[],function(){var b,d,f=0;window.addEventListener("message",function(c){if(c=c.data){c=c==="oauth_success"?true:false;d=null;if(b){b(c);b=null}}},false);return function(c,a){if(a)b=a;a=location.protocol+"//"+location.host+"/auth.html";var e=(new Date).getTime();if(d&&d.closed)d=null;if(e>f+4E3){f=e;c=a+"?domain="+c;try{d=window.open(c,"ffshareOAuth","dialog=yes, modal=yes, width=900, height=500, scrollbars=yes");d.focus()}catch(g){window.location=c+"&end_point_success="+encodeURI(window.location)}}else d&&
d.focus()}});define("blade/array",[],function(){var b=Object.prototype.toString,d=Array.prototype.slice;return{is:function(f){return b.call(f)==="[object Array]"},to:function(){return[].concat(d.call(arguments,0))}}});
define("blade/url",["./array"],function(b){var d=Object.prototype.toString;return{objectToQuery:function(f){var c=encodeURIComponent,a=[],e={},g,h,i,k;for(g in f)if(f.hasOwnProperty(g)){h=f[g];if(h!==e[g]){i=c(g)+"=";if(b.is(h))for(k=0;k<h.length;k++)a.push(i+c(h[k]));else a.push(i+c(h))}}return a.join("&")},queryToObject:function(f){var c={};f=f.split("&");var a=decodeURIComponent,e,g,h;f.forEach(function(i){if(i.length){e=i.split("=");g=a(e.shift());h=a(e.join("="));if(typeof c[g]==="string")c[g]=
[c[g]];if(d.call(c[g])==="[object Array]")c[g].push(h);else c[g]=h}});return c}}});
define("placeholder",["jquery"],function(b){function d(a){var e=!("placeholder"in a),g=a.getAttribute("placeholder"),h=a.value.trim();if(!h||h===g){if(e){b(a).addClass("placeholder");a.value=g;if(g==="password"&&a.type==="password")a.type="text"}}else b(a).removeClass("placeholder")}function f(a){a=a.target;var e=a.getAttribute("placeholder");if(a.value===e){if(!("placeholder"in a)){a.value="";if(e==="password"&&a.type==="text")a.type="password"}b(a).removeClass("placeholder")}}function c(a){d(a.target)}
return function(a){b('input[type="text"], input[type="password"], textarea',a).each(function(e,g){if(g.getAttribute("data-rdwPlaceholder")!=="set"){b(g).focus(f).blur(c);g.setAttribute("data-rdwPlaceholder","set")}d(g)})}});
define("TextCounter",["jquery","blade/object","blade/fn"],function(b,d,f){return d(null,null,{init:function(c,a,e){this.dom=b(c);this.domPlaceholderText=this.dom[0].getAttribute("placeholder")||"";this.countDom=b(a);this.limit=e;this.dom.bind("keyup",f.bind(this,"checkCount"));this.checkCount()},checkCount:function(){var c=this.dom[0].value;if(c.trim()===this.domPlaceholderText)c="";c=this.limit-c.length;c<0?this.countDom.addClass("TextCountOver"):this.countDom.removeClass("TextCountOver");this.countDom.text(c===
this.limit?"":c)},updateLimit:function(c){this.limit=c;this.checkCount()},isOver:function(){return this.dom[0].value.length>this.limit}})});
define("dispatch",["jquery"],function(){var b=location.protocol+"//"+location.host;return{sub:function(d,f,c,a){c=c||window;a=a||b;var e=function(g){if(g.origin===a||g.origin==="chrome://browser")try{var h=JSON.parse(g.data),i=h.topic;i&&i===d&&f(h.data)}catch(k){}};c.addEventListener("message",e,false);return e},unsub:function(d,f){f=f||window;f.removeEventListener("message",d,false)},pub:function(d,f,c){c=c||window;c.postMessage(JSON.stringify({topic:d,data:f}),b)}}});
define("AutoComplete",["jquery","blade/object","blade/fn","dispatch"],function(b,d,f){return d(null,null,{init:function(c){this.dom=b(c);this.dom.bind("keyup",f.bind(this,"onKeyUp"))},onKeyUp:function(){}})});define("storage",[],function(){function b(){return d}var d=localStorage,f="localStorage";try{d.tempVar="temp";delete d.tempVar}catch(c){d={};f="memory"}b.type=f;return b});
define("accounts",["storage","dispatch","rdapi"],function(b,d,f){function c(h,i){return g.accounts(h,i)}function a(){location.reload()}var e=b(),g;g={localStorage:{accounts:function(h,i){var k=e.accountCache,p=e.lastAccountCheck||0,q=(new Date).getTime(),D=false;if(!k||q-p>3E3)D=true;k=k?JSON.parse(k):[];h&&h(k);D&&g.fetch(null,i)},fetch:function(h,i){f("account/get",{success:function(k){if(k.error)k=[];e.lastAccountCheck=(new Date).getTime();h&&h(k);var p=e.accountCache,q;p=p?JSON.parse(p):[];if(q=
k.length===p.length)q=!k.some(function(D,G){return D.identifier!==p[G].identifier});if(!q){e.accountCache=JSON.stringify(k);g.changed()}},error:i||function(){}})},changed:function(){e.accountChanged=(new Date).getTime();opener&&!opener.closed&&d.pub("accountsChanged",null,opener);d.pub("accountsChanged")},onChange:function(h){var i=e.accountChanged;window.addEventListener("storage",function(){e.accountChanged!==i&&h()},false);d.sub("accountsChanged",h)}},memory:{accounts:function(h,i){g.fetch(h,i)},
fetch:function(h,i){f("account/get",{success:function(k){if(k.error)k=[];h&&h(k)},error:i||function(){}})},changed:function(){e.accountChanged=(new Date).getTime();opener&&d.pub("accountsChanged",null,opener);d.pub("accountsChanged")},onChange:function(h){d.sub("accountsChanged",h)}}}[b.type];c.fetch=function(h,i){g.fetch(h,i)};c.clear=function(){delete e.accountCache};c.changed=function(){return g.changed()};c.onChange=function(h){return g.onChange(h||a)};return c});
define("services",["rdapi","blade/object","TextCounter"],function(b,d){function f(e,g){if(e){this.name=e;this.type=e.replace(/\s/g,"").toLowerCase();this.tabName=this.type+"Tab";this.icon="i/"+this.type+"Icon.png";this.autoCompleteWidget=null;this.features={counter:false,direct:false,subject:false};d.mixin(this,g,true)}}function c(){f.constructor.apply(this,arguments);this.features.direct=true;this.features.subject=true}var a;f.constructor=f;f.prototype={clearCache:function(e){delete e[this.type+
"Contacts"]},getContacts:function(e){if(e[this.type+"Contacts"])return JSON.parse(e[this.type+"Contacts"]);return null},setContacts:function(e,g){e[this.type+"Contacts"]=JSON.stringify(g)},getFormattedContacts:function(e){var g={};e.forEach(function(h){h.accounts&&h.accounts.length&&h.accounts.forEach(function(i){g[h.displayName]={email:"",userid:i.userid,username:i.username}})});return g}};c.prototype=new f;c.constructor=c;c.prototype.validate=function(e){if(!e.to||!e.to.trim())return false;return true};
c.prototype.getFormattedContacts=function(e){var g={};e.forEach(function(h){h.emails&&h.emails.length&&h.emails.forEach(function(i){g[h.displayName?h.displayName:i.value]={email:i.value,userid:null,username:null}})});return g};b={domains:{"twitter.com":new f("Twitter",{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"public",name:"public"},{type:"direct",name:"direct message",showTo:true,toLabel:"type in name of recipient"}],textLimit:140,shorten:true,serviceUrl:"http://twitter.com",
revokeUrl:"http://twitter.com/settings/connections",signOutUrl:"http://twitter.com/logout",accountLink:function(e){return"http://twitter.com/"+e.username}}),"facebook.com":new f("Facebook",{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"wall",name:"my wall"},{type:"groupWall",name:"group wall",showTo:true,toLabel:"type in the name of the group"}],textLimit:420,serviceUrl:"http://facebook.com",revokeUrl:"http://www.facebook.com/editapps.php?v=allowed",signOutUrl:"http://facebook.com",
accountLink:function(e){return"http://www.facebook.com/profile.php?id="+e.userid}}),"google.com":new c("Gmail",{shareTypes:[{type:"direct",name:"direct",showTo:true}],serviceUrl:"https://mail.google.com",revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(e){return"http://google.com/profiles/"+e.username}}),"googleapps.com":new c("Google Apps",{shareTypes:[{type:"direct",name:"direct",showTo:true}],icon:"i/gmailIcon.png",
serviceUrl:"https://mail.google.com",revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(e){return"http://google.com/profiles/"+e.username}}),"yahoo.com":new c("Yahoo",{shareTypes:[{type:"direct",name:"direct",showTo:true}],name:"Yahoo!",serviceUrl:"http://mail.yahoo.com",revokeUrl:"https://api.login.yahoo.com/WSLogin/V1/unlink",signOutUrl:"https://login.yahoo.com/config/login?logout=1",accountLink:function(e){return"http://profiles.yahoo.com/"+
e.username}}),"linkedin.com":new f("LinkedIn",{isNew:true,features:{direct:true,subject:true,counter:false},shareTypes:[{type:"public",name:"anyone"},{type:"myConnections",name:"connections only",specialTo:"connections-only"},{type:"contact",name:"send message",showTo:true,toLabel:"type in the name of the contact"}],serviceUrl:"http://linkedin.com",revokeUrl:"http://linkedin.com/settings/connections",signOutUrl:"http://linkedin.com/logout",accountLink:function(e){return"http://linkedin.com/"+e.username},
overlays:{"widgets/AccountPanel":"widgets/AccountPanelLinkedIn"}})},domainList:[],svcBaseProto:f.prototype};for(a in b.domains)b.domains.hasOwnProperty(a)&&b.domainList.push(a);return b});
(function(b,d){function f(c){return!b(c).parents().andSelf().filter(function(){return b.curCSS(this,"visibility")==="hidden"||b.expr.filters.hidden(this)}).length}b.ui=b.ui||{};if(!b.ui.version){b.extend(b.ui,{version:"1.8.6",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});b.fn.extend({_focus:b.fn.focus,focus:function(c,a){return typeof c==="number"?this.each(function(){var e=this;setTimeout(function(){b(e).focus();a&&a.call(e)},c)}):this._focus.apply(this,arguments)},scrollParent:function(){var c;c=b.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.curCSS(this,
"position",1))&&/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!c.length?b(document):c},zIndex:function(c){if(c!==d)return this.css("zIndex",c);if(this.length){c=b(this[0]);for(var a;c.length&&c[0]!==document;){a=c.css("position");
if(a==="absolute"||a==="relative"||a==="fixed"){a=parseInt(c.css("zIndex"),10);if(!isNaN(a)&&a!==0)return a}c=c.parent()}}return 0},disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(c){c.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});b.each(["Width","Height"],function(c,a){function e(k,p,q,D){b.each(g,function(){p-=parseFloat(b.curCSS(k,"padding"+this,true))||0;if(q)p-=parseFloat(b.curCSS(k,
"border"+this+"Width",true))||0;if(D)p-=parseFloat(b.curCSS(k,"margin"+this,true))||0});return p}var g=a==="Width"?["Left","Right"]:["Top","Bottom"],h=a.toLowerCase(),i={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+a]=function(k){if(k===d)return i["inner"+a].call(this);return this.each(function(){b(this).css(h,e(this,k)+"px")})};b.fn["outer"+a]=function(k,p){if(typeof k!=="number")return i["outer"+a].call(this,k);return this.each(function(){b(this).css(h,
e(this,k,true,p)+"px")})}});b.extend(b.expr[":"],{data:function(c,a,e){return!!b.data(c,e[3])},focusable:function(c){var a=c.nodeName.toLowerCase(),e=b.attr(c,"tabindex");if("area"===a){a=c.parentNode;e=a.name;if(!c.href||!e||a.nodeName.toLowerCase()!=="map")return false;c=b("img[usemap=#"+e+"]")[0];return!!c&&f(c)}return(/input|select|textarea|button|object/.test(a)?!c.disabled:"a"==a?c.href||!isNaN(e):!isNaN(e))&&f(c)},tabbable:function(c){var a=b.attr(c,"tabindex");return(isNaN(a)||a>=0)&&b(c).is(":focusable")}});
b(function(){var c=document.body,a=c.appendChild(a=document.createElement("div"));b.extend(a.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});b.support.minHeight=a.offsetHeight===100;b.support.selectstart="onselectstart"in a;c.removeChild(a).style.display="none"});b.extend(b.ui,{plugin:{add:function(c,a,e){c=b.ui[c].prototype;for(var g in e){c.plugins[g]=c.plugins[g]||[];c.plugins[g].push([a,e[g]])}},call:function(c,a,e){if((a=c.plugins[a])&&c.element[0].parentNode)for(var g=0;g<a.length;g++)c.options[a[g][0]]&&
a[g][1].apply(c.element,e)}},contains:function(c,a){return document.compareDocumentPosition?c.compareDocumentPosition(a)&16:c!==a&&c.contains(a)},hasScroll:function(c,a){if(b(c).css("overflow")==="hidden")return false;a=a&&a==="left"?"scrollLeft":"scrollTop";var e=false;if(c[a]>0)return true;c[a]=1;e=c[a]>0;c[a]=0;return e},isOverAxis:function(c,a,e){return c>a&&c<a+e},isOver:function(c,a,e,g,h,i){return b.ui.isOverAxis(c,e,h)&&b.ui.isOverAxis(a,g,i)}})}})(jQuery);
(function(b,d){if(b.cleanData){var f=b.cleanData;b.cleanData=function(a){for(var e=0,g;(g=a[e])!=null;e++)b(g).triggerHandler("remove");f(a)}}else{var c=b.fn.remove;b.fn.remove=function(a,e){return this.each(function(){if(!e)if(!a||b.filter(a,[this]).length)b("*",this).add([this]).each(function(){b(this).triggerHandler("remove")});return c.call(b(this),a,e)})}}b.widget=function(a,e,g){var h=a.split(".")[0],i;a=a.split(".")[1];i=h+"-"+a;if(!g){g=e;e=b.Widget}b.expr[":"][i]=function(k){return!!b.data(k,
a)};b[h]=b[h]||{};b[h][a]=function(k,p){arguments.length&&this._createWidget(k,p)};e=new e;e.options=b.extend(true,{},e.options);b[h][a].prototype=b.extend(true,e,{namespace:h,widgetName:a,widgetEventPrefix:b[h][a].prototype.widgetEventPrefix||a,widgetBaseClass:i},g);b.widget.bridge(a,b[h][a])};b.widget.bridge=function(a,e){b.fn[a]=function(g){var h=typeof g==="string",i=Array.prototype.slice.call(arguments,1),k=this;g=!h&&i.length?b.extend.apply(null,[true,g].concat(i)):g;if(h&&g.charAt(0)==="_")return k;
h?this.each(function(){var p=b.data(this,a),q=p&&b.isFunction(p[g])?p[g].apply(p,i):p;if(q!==p&&q!==d){k=q;return false}}):this.each(function(){var p=b.data(this,a);p?p.option(g||{})._init():b.data(this,a,new e(g,this))});return k}};b.Widget=function(a,e){arguments.length&&this._createWidget(a,e)};b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(a,e){b.data(e,this.widgetName,this);this.element=b(e);this.options=b.extend(true,{},this.options,
this._getCreateOptions(),a);var g=this;this.element.bind("remove."+this.widgetName,function(){g.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return b.metadata&&b.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(a,e){var g=a;if(arguments.length===0)return b.extend({},this.options);if(typeof a==="string"){if(e===d)return this.options[a];g={};g[a]=e}this._setOptions(g);return this},_setOptions:function(a){var e=this;b.each(a,function(g,h){e._setOption(g,h)});return this},_setOption:function(a,e){this.options[a]=e;if(a==="disabled")this.widget()[e?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",e);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(a,e,g){var h=this.options[a];e=b.Event(e);e.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase();g=g||{};if(e.originalEvent){a=b.event.props.length;for(var i;a;){i=b.event.props[--a];e[i]=e.originalEvent[i]}}this.element.trigger(e,g);return!(b.isFunction(h)&&h.call(this.element[0],e,g)===false||e.isDefaultPrevented())}}})(jQuery);
(function(b,d){function f(){return++a}function c(){return++e}var a=0,e=0;b.widget("ui.tabs",{options:{add:null,ajaxOptions:null,cache:false,cookie:null,collapsible:false,disable:null,disabled:[],enable:null,event:"click",fx:null,idPrefix:"ui-tabs-",load:null,panelTemplate:"<div></div>",remove:null,select:null,show:null,spinner:"<em>Loading&#8230;</em>",tabTemplate:"<li><a href='#{href}'><span>#{label}</span></a></li>"},_create:function(){this._tabify(true)},_setOption:function(g,h){if(g=="selected")this.options.collapsible&&
h==this.options.selected||this.select(h);else{this.options[g]=h;this._tabify()}},_tabId:function(g){return g.title&&g.title.replace(/\s/g,"_").replace(/[^\w\u00c0-\uFFFF-]/g,"")||this.options.idPrefix+f()},_sanitizeSelector:function(g){return g.replace(/:/g,"\\:")},_cookie:function(){var g=this.cookie||(this.cookie=this.options.cookie.name||"ui-tabs-"+c());return b.cookie.apply(null,[g].concat(b.makeArray(arguments)))},_ui:function(g,h){return{tab:g,panel:h,index:this.anchors.index(g)}},_cleanup:function(){this.lis.filter(".ui-state-processing").removeClass("ui-state-processing").find("span:data(label.tabs)").each(function(){var g=
b(this);g.html(g.data("label.tabs")).removeData("label.tabs")})},_tabify:function(g){function h(w,v){w.css("display","");!b.support.opacity&&v.opacity&&w[0].style.removeAttribute("filter")}var i=this,k=this.options,p=/^#.+/;this.list=this.element.find("ol,ul").eq(0);this.lis=b(" > li:has(a[href])",this.list);this.anchors=this.lis.map(function(){return b("a",this)[0]});this.panels=b([]);this.anchors.each(function(w,v){var A=b(v).attr("href"),I=A.split("#")[0],O;if(I&&(I===location.toString().split("#")[0]||
(O=b("base")[0])&&I===O.href)){A=v.hash;v.href=A}if(p.test(A))i.panels=i.panels.add(i._sanitizeSelector(A));else if(A&&A!=="#"){b.data(v,"href.tabs",A);b.data(v,"load.tabs",A.replace(/#.*$/,""));A=i._tabId(v);v.href="#"+A;v=b("#"+A);if(!v.length){v=b(k.panelTemplate).attr("id",A).addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").insertAfter(i.panels[w-1]||i.list);v.data("destroy.tabs",true)}i.panels=i.panels.add(v)}else k.disabled.push(w)});if(g){this.element.addClass("ui-tabs ui-widget ui-widget-content ui-corner-all");
this.list.addClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.lis.addClass("ui-state-default ui-corner-top");this.panels.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom");if(k.selected===d){location.hash&&this.anchors.each(function(w,v){if(v.hash==location.hash){k.selected=w;return false}});if(typeof k.selected!=="number"&&k.cookie)k.selected=parseInt(i._cookie(),10);if(typeof k.selected!=="number"&&this.lis.filter(".ui-tabs-selected").length)k.selected=
this.lis.index(this.lis.filter(".ui-tabs-selected"));k.selected=k.selected||(this.lis.length?0:-1)}else if(k.selected===null)k.selected=-1;k.selected=k.selected>=0&&this.anchors[k.selected]||k.selected<0?k.selected:0;k.disabled=b.unique(k.disabled.concat(b.map(this.lis.filter(".ui-state-disabled"),function(w){return i.lis.index(w)}))).sort();b.inArray(k.selected,k.disabled)!=-1&&k.disabled.splice(b.inArray(k.selected,k.disabled),1);this.panels.addClass("ui-tabs-hide");this.lis.removeClass("ui-tabs-selected ui-state-active");
if(k.selected>=0&&this.anchors.length){b(i._sanitizeSelector(i.anchors[k.selected].hash)).removeClass("ui-tabs-hide");this.lis.eq(k.selected).addClass("ui-tabs-selected ui-state-active");i.element.queue("tabs",function(){i._trigger("show",null,i._ui(i.anchors[k.selected],b(i._sanitizeSelector(i.anchors[k.selected].hash))))});this.load(k.selected)}b(window).bind("unload",function(){i.lis.add(i.anchors).unbind(".tabs");i.lis=i.anchors=i.panels=null})}else k.selected=this.lis.index(this.lis.filter(".ui-tabs-selected"));
this.element[k.collapsible?"addClass":"removeClass"]("ui-tabs-collapsible");k.cookie&&this._cookie(k.selected,k.cookie);g=0;for(var q;q=this.lis[g];g++)b(q)[b.inArray(g,k.disabled)!=-1&&!b(q).hasClass("ui-tabs-selected")?"addClass":"removeClass"]("ui-state-disabled");k.cache===false&&this.anchors.removeData("cache.tabs");this.lis.add(this.anchors).unbind(".tabs");if(k.event!=="mouseover"){var D=function(w,v){v.is(":not(.ui-state-disabled)")&&v.addClass("ui-state-"+w)},G=function(w,v){v.removeClass("ui-state-"+
w)};this.lis.bind("mouseover.tabs",function(){D("hover",b(this))});this.lis.bind("mouseout.tabs",function(){G("hover",b(this))});this.anchors.bind("focus.tabs",function(){D("focus",b(this).closest("li"))});this.anchors.bind("blur.tabs",function(){G("focus",b(this).closest("li"))})}var K,N;if(k.fx)if(b.isArray(k.fx)){K=k.fx[0];N=k.fx[1]}else K=N=k.fx;var y=N?function(w,v){b(w).closest("li").addClass("ui-tabs-selected ui-state-active");v.hide().removeClass("ui-tabs-hide").animate(N,N.duration||"normal",
function(){h(v,N);i._trigger("show",null,i._ui(w,v[0]))})}:function(w,v){b(w).closest("li").addClass("ui-tabs-selected ui-state-active");v.removeClass("ui-tabs-hide");i._trigger("show",null,i._ui(w,v[0]))},z=K?function(w,v){v.animate(K,K.duration||"normal",function(){i.lis.removeClass("ui-tabs-selected ui-state-active");v.addClass("ui-tabs-hide");h(v,K);i.element.dequeue("tabs")})}:function(w,v){i.lis.removeClass("ui-tabs-selected ui-state-active");v.addClass("ui-tabs-hide");i.element.dequeue("tabs")};
this.anchors.bind(k.event+".tabs",function(){var w=this,v=b(w).closest("li"),A=i.panels.filter(":not(.ui-tabs-hide)"),I=b(i._sanitizeSelector(w.hash));if(v.hasClass("ui-tabs-selected")&&!k.collapsible||v.hasClass("ui-state-disabled")||v.hasClass("ui-state-processing")||i.panels.filter(":animated").length||i._trigger("select",null,i._ui(this,I[0]))===false){this.blur();return false}k.selected=i.anchors.index(this);i.abort();if(k.collapsible)if(v.hasClass("ui-tabs-selected")){k.selected=-1;k.cookie&&
i._cookie(k.selected,k.cookie);i.element.queue("tabs",function(){z(w,A)}).dequeue("tabs");this.blur();return false}else if(!A.length){k.cookie&&i._cookie(k.selected,k.cookie);i.element.queue("tabs",function(){y(w,I)});i.load(i.anchors.index(this));this.blur();return false}k.cookie&&i._cookie(k.selected,k.cookie);if(I.length){A.length&&i.element.queue("tabs",function(){z(w,A)});i.element.queue("tabs",function(){y(w,I)});i.load(i.anchors.index(this))}else throw"jQuery UI Tabs: Mismatching fragment identifier.";
b.browser.msie&&this.blur()});this.anchors.bind("click.tabs",function(){return false})},_getIndex:function(g){if(typeof g=="string")g=this.anchors.index(this.anchors.filter("[href$="+g+"]"));return g},destroy:function(){var g=this.options;this.abort();this.element.unbind(".tabs").removeClass("ui-tabs ui-widget ui-widget-content ui-corner-all ui-tabs-collapsible").removeData("tabs");this.list.removeClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.anchors.each(function(){var h=
b.data(this,"href.tabs");if(h)this.href=h;var i=b(this).unbind(".tabs");b.each(["href","load","cache"],function(k,p){i.removeData(p+".tabs")})});this.lis.unbind(".tabs").add(this.panels).each(function(){b.data(this,"destroy.tabs")?b(this).remove():b(this).removeClass("ui-state-default ui-corner-top ui-tabs-selected ui-state-active ui-state-hover ui-state-focus ui-state-disabled ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide")});g.cookie&&this._cookie(null,g.cookie);return this},add:function(g,
h,i){if(i===d)i=this.anchors.length;var k=this,p=this.options;h=b(p.tabTemplate.replace(/#\{href\}/g,g).replace(/#\{label\}/g,h));g=!g.indexOf("#")?g.replace("#",""):this._tabId(b("a",h)[0]);h.addClass("ui-state-default ui-corner-top").data("destroy.tabs",true);var q=b("#"+g);q.length||(q=b(p.panelTemplate).attr("id",g).data("destroy.tabs",true));q.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide");if(i>=this.lis.length){h.appendTo(this.list);q.appendTo(this.list[0].parentNode)}else{h.insertBefore(this.lis[i]);
q.insertBefore(this.panels[i])}p.disabled=b.map(p.disabled,function(D){return D>=i?++D:D});this._tabify();if(this.anchors.length==1){p.selected=0;h.addClass("ui-tabs-selected ui-state-active");q.removeClass("ui-tabs-hide");this.element.queue("tabs",function(){k._trigger("show",null,k._ui(k.anchors[0],k.panels[0]))});this.load(0)}this._trigger("add",null,this._ui(this.anchors[i],this.panels[i]));return this},remove:function(g){g=this._getIndex(g);var h=this.options,i=this.lis.eq(g).remove(),k=this.panels.eq(g).remove();
if(i.hasClass("ui-tabs-selected")&&this.anchors.length>1)this.select(g+(g+1<this.anchors.length?1:-1));h.disabled=b.map(b.grep(h.disabled,function(p){return p!=g}),function(p){return p>=g?--p:p});this._tabify();this._trigger("remove",null,this._ui(i.find("a")[0],k[0]));return this},enable:function(g){g=this._getIndex(g);var h=this.options;if(b.inArray(g,h.disabled)!=-1){this.lis.eq(g).removeClass("ui-state-disabled");h.disabled=b.grep(h.disabled,function(i){return i!=g});this._trigger("enable",null,
this._ui(this.anchors[g],this.panels[g]));return this}},disable:function(g){g=this._getIndex(g);var h=this.options;if(g!=h.selected){this.lis.eq(g).addClass("ui-state-disabled");h.disabled.push(g);h.disabled.sort();this._trigger("disable",null,this._ui(this.anchors[g],this.panels[g]))}return this},select:function(g){g=this._getIndex(g);if(g==-1)if(this.options.collapsible&&this.options.selected!=-1)g=this.options.selected;else return this;this.anchors.eq(g).trigger(this.options.event+".tabs");return this},
load:function(g){g=this._getIndex(g);var h=this,i=this.options,k=this.anchors.eq(g)[0],p=b.data(k,"load.tabs");this.abort();if(!p||this.element.queue("tabs").length!==0&&b.data(k,"cache.tabs"))this.element.dequeue("tabs");else{this.lis.eq(g).addClass("ui-state-processing");if(i.spinner){var q=b("span",k);q.data("label.tabs",q.html()).html(i.spinner)}this.xhr=b.ajax(b.extend({},i.ajaxOptions,{url:p,success:function(D,G){b(h._sanitizeSelector(k.hash)).html(D);h._cleanup();i.cache&&b.data(k,"cache.tabs",
true);h._trigger("load",null,h._ui(h.anchors[g],h.panels[g]));try{i.ajaxOptions.success(D,G)}catch(K){}},error:function(D,G){h._cleanup();h._trigger("load",null,h._ui(h.anchors[g],h.panels[g]));try{i.ajaxOptions.error(D,G,g,k)}catch(K){}}}));h.element.dequeue("tabs");return this}},abort:function(){this.element.queue([]);this.panels.stop(false,true);this.element.queue("tabs",this.element.queue("tabs").splice(-2,2));if(this.xhr){this.xhr.abort();delete this.xhr}this._cleanup();return this},url:function(g,
h){this.anchors.eq(g).removeData("cache.tabs").data("load.tabs",h);return this},length:function(){return this.anchors.length}});b.extend(b.ui.tabs,{version:"1.8.6"});b.extend(b.ui.tabs.prototype,{rotation:null,rotate:function(g,h){var i=this,k=this.options,p=i._rotate||(i._rotate=function(q){clearTimeout(i.rotation);i.rotation=setTimeout(function(){var D=k.selected;i.select(++D<i.anchors.length?D:0)},g);q&&q.stopPropagation()});h=i._unrotate||(i._unrotate=!h?function(q){q.clientX&&i.rotate(null)}:
function(){t=k.selected;p()});if(g){this.element.bind("tabsshow",p);this.anchors.bind(k.event+".tabs",h);p()}else{clearTimeout(i.rotation);this.element.unbind("tabsshow",p);this.anchors.unbind(k.event+".tabs",h);delete this._rotate;delete this._unrotate}return this}})})(jQuery);define("jquery-ui-1.8.6.custom.min",function(){});
(function(b){var d=document.documentElement.style,f="textOverflow"in d||"OTextOverflow"in d,c=function(a,e){var g=0,h=[],i=function(k){var p=0,q;if(!(g>e))for(p=0;p<k.length;p+=1)if(k[p].nodeType===1){q=k[p].cloneNode(false);h[h.length-1].appendChild(q);h.push(q);i(k[p].childNodes);h.pop()}else if(k[p].nodeType===3){if(g+k[p].length<e)h[h.length-1].appendChild(k[p].cloneNode(false));else{q=k[p].cloneNode(false);q.textContent=b.trim(q.textContent.substring(0,e-g));h[h.length-1].appendChild(q)}g+=k[p].length}else h.appendChild(k[p].cloneNode(false))};
h.push(a.cloneNode(false));i(a.childNodes);return b(h.pop().childNodes)};b.extend(b.fn,{textOverflow:function(a,e){var g=a||"&#x2026;";return f?this:this.each(function(){var h=b(this),i=h.clone(),k=h.clone(),p=h.text(),q=h.width(),D=0,G=0,K=p.length,N=function(){if(q!==h.width()){h.replaceWith(k);h=k;k=h.clone();h.textOverflow(a,false);q=h.width()}};h.after(i.hide().css({position:"absolute",width:"auto",overflow:"visible","max-width":"inherit"}));if(i.width()>q){for(;D<K;){G=Math.floor(D+(K-D)/2);
i.empty().append(c(k.get(0),G)).append(g);if(i.width()<q)D=G+1;else K=G}D<p.length&&h.empty().append(c(k.get(0),D-1)).append(g)}i.remove();e&&setInterval(N,200)})}})})(jQuery);define("jquery.textOverflow",function(){});
define("index",["require","jquery","blade/fn","rdapi","oauth","blade/jig","blade/url","placeholder","TextCounter","AutoComplete","dispatch","accounts","storage","services","blade/object","jquery-ui-1.8.6.custom.min","jquery.textOverflow"],function(b,d,f,c,a,e,g,h,i,k,p,q,D,G,K){function N(n){return n?n.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"):n}function y(){p.pub("hide")}function z(){C.addClass("hidden");d("div.status").addClass("hidden");h()}function w(){var n=o&&o.domain||
"twitter.com",x=r.siteName,E=r.url||"",H=E.indexOf("//")+2;d("#statusShared").empty().append(e("#sharedTemplate",{domain:x||E.slice(H,E.indexOf("/",H)),service:m[n].name,href:m[n].serviceUrl})).find(".shareTitle").textOverflow(null,true);l("statusShared",true)}function v(n,x){d("#captchaImage").attr("src",n.imageurl);x&&d("#captchaMsg").text(x.message);d("#captchaSound").attr("src",n.audiourl);l("statusCaptcha",false)}function A(){var n={link:o.link,domain:o.domain,formData:m[o.domain].getFormData()};
J.sessionRestore=JSON.stringify(n);l("statusAuth")}function I(){l("statusSharing");m[o.domain].validate(o)?c("send",{type:"POST",data:o,success:function(n){if(n.error&&n.error.status){var x=n.error.status;if(x===401||x===535)A();else if(n.error.code==="Client.HumanVerificationRequired")v(n.error.detail);else n.error.code==="Client.WrongInput"?v(n.error.detail,n.error):l("statusError",n.error.message)}else if(n.error)l("statusError",n.error.message);else{J.lastSelection=m[o.domain].type;w()}delete J.sessionRestore},
error:function(n,x,E){if(n.status===403)A();else n.status===503?l("statusServerBusy"):l("statusError",E)}}):l("statusToError")}function O(n){var x=G.domains[n],E=d("#"+x.type).find('[name="to"]')[0],H=x.getContacts(J);H||(H={});if(!x.autoCompleteWidget)x.autoCompleteWidget=new k(E);p.pub("autoCompleteData",{domain:n,contacts:H})}function aa(n,x){var E=x.accounts[0],H=G.domains[E.domain];H.getContacts(J)?O(E.domain):c("contacts/"+E.domain,{type:"POST",data:{username:E.username,userid:E.userid,startindex:0,
maxresults:500},success:function(L){if(L&&!L.error){var M=[];M=H.getFormattedContacts(L.result.entry);H.setContacts(J,M);O(E.domain)}}})}function T(n,x){var E=n="",H=true,L="",M=x.panel.id,F=d(".user-info");if(M!=="debug"){n=d(x.panel).find("div.user img.avatar").attr("src");E=d(x.panel).find("div.user .username").text();H=d(x.panel).find("div.user").hasClass("inactive");L=d(x.panel).find("div.user input[type='hidden'][name='domain']").val()}d(".user-info img.avatar").attr("src",n);n?F.show():F.hide();
d(".user-info .status").toggleClass("inactive",H);d(".user-info .username").text(E);d(".user-info").attr("data-domain",L)}function V(n,x){d(function(){var E=x.displayName,H=x.accounts[0],L=x.photos&&x.photos[0]&&x.photos[0].value,M=d("#"+n),F;if((F=H.username)&&F!==E)E=E+" <"+F+">";d("."+n+"Tab").removeClass("hidden");E&&M.find(".username").text(E);L&&M.find(".avatar").attr("src",L);M.find('input[name="userid"]').val(H.userid);M.find('input[name="username"]').val(H.username);M.find("div.user").removeClass("inactive")})}
function U(){var n,x;if(J.lastSelection)n="#"+J.lastSelection;else if(P&&P.length){x=P[0].accounts[0].domain;if(m[x])if(x=m[x].type)n="#"+x}return n}function Z(){d(".ui-tabs-nav > li").removeClass("first").removeClass("last").filter(function(){var n=d(this),x=n.hasClass("hidden");n=n.hasClass("debugTab");return!x&&!n}).first().addClass("first").end().last().addClass("last")}function j(n){var x=false,E={},H=J.sessionRestore,L;n&&n.length&&n.forEach(function(M){var F=M.accounts[0].domain;if(F&&m[F]){x||
(x=m[F].type===J.lastSelection);E[m[F].type]=M}});!x&&!J.accountAdded&&J.lastSelection&&delete J.lastSelection;J.accountAdded&&delete J.accountAdded;for(L in E)if(E.hasOwnProperty(L)){V(L,E[L]);aa(L,E[L])}if(H){H=JSON.parse(H);if(r.link!==H.link){H=null;delete J.sessionRestore}if(H){m[H.domain].setFormData(H.formData);h()}}if(Q){n=U();u.tabs("select",n);T(null,{panel:d(n)[0]})}Z()}var l,m=G.domains;b=location.href.split("#")[1];var o,s,r={},u,B,C,Q=true,R,P,ba,J=D();K.mixin(G.svcBaseProto,{validate:function(){if(this.counter)return!this.counter||
!this.counter.isOver();return true},startCounter:function(n){if(!(this.textlimit<1)){if(!this.counter)this.counter=new i(d("#"+this.type+" textarea.message"),d("#"+this.type+" .counter"),this.textlimit-this.urlsize);this.counter.updateLimit(n.shortUrl?this.textlimit-(n.shortUrl.length+1):this.textlimit-this.urlsize)}},getFormData:function(){var n=d("#"+this.type);return{to:n.find('[name="to"]').val().trim()||"",subject:n.find('[name="subject"]').val().trim()||"",message:n.find("textarea.message").val().trim()||
"",picture:n.find('[name="picture"]').val().trim()||"",picture_base64:n.find('[name="picture_base64"]').val().trim()||"",canonicalUrl:n.find('[name="link"]').val().trim()||"",title:n.find('[name="title"]').val().trim()||"",description:n.find('[name="description"]').val().trim()||"",shortUrl:n.find('[name="surl"]').val().trim()||""}},setFormData:function(n){var x=d("#"+this.type);n.to&&x.find('[name="to"]').val(n.to);n.subject&&x.find('[name="subject"]').val(n.subject);n.message&&x.find("textarea.message").val(n.message);
if(n.previews&&n.previews.length){x.find('[name="picture"]').val(n.previews[0]);x.find('[name="picture_base64"]').val(r.previews[0])}if(n.canonicalUrl||n.url)x.find('[name="link"]').val(n.canonicalUrl||n.url);n.title&&x.find('[name="title"]').val(n.title);n.description&&x.find('[name="description"]').val(n.description);n.shortUrl&&x.find('[name="surl"]').val(n.shortUrl);this.startCounter(n)}});e.addFn({profilePic:function(n){return n&&n[0]&&n[0].value||"i/face2.png"},serviceName:function(n){return m[n].name}});
window.closeShare=y;l=function(n,x){d("div.status").addClass("hidden");C.removeClass("hidden");d("#"+n).removeClass("hidden");if(x===true)setTimeout(function(){p.pub("success",{domain:o.domain,username:o.username,userid:o.userid})},2E3);else x&&d("#"+n+"Message").text(x)};window.showStatus=l;window.showStatusShared=w;window.handleCaptcha=v;if(b){g=g.queryToObject(b);if(g.options)r=JSON.parse(g.options)}r.prefs=r.prefs||{};if(!r.title)r.title=r.url;if(!r.prefs.system)r.prefs.system="prod";if(r.version)J.extensionVersion=
r.version;if(r.prefs)for(s in r.prefs)if(r.prefs.hasOwnProperty(s))J["prefs."+s]=r.prefs[s];if(s=J.newTimerV2){s=JSON.parse(s);if((new Date).getTime()-s<2592E5)ba=true}else{J.newTimerV1=(new Date).getTime();ba=true}d(function(){var n,x=J.sessionRestore,E,H="",L="",M;G.domainList.forEach(function(F){G.domains[F].domain=F;H+=e("#tabsTemplate",G.domains[F]);L+=e("#panelsTemplate",G.domains[F])});d(".nav .debugTab").before(H);d("#tabs #debug").before(L);n=d("img.thumb");B=d("body");C=d("#clickBlock");
r.prefs.system&&d(document.documentElement).addClass(r.prefs.system);if(r.prefs.system==="dev"){d("#debugOutput").val(JSON.stringify(r));d("#debugCurrentLocation").val(location.href)}ba&&d("#newLink").removeClass("hidden");B.delegate("#statusAuthButton, .statusErrorButton","click",function(){z()}).delegate(".statusErrorCloseButton","click",function(){y()}).delegate(".statusResetErrorButton","click",function(){location.reload()}).delegate(".nav .close","click",y);d("#authOkButton").click(function(){a(o.domain,
function(F){if(F){q.clear();q()}else l("statusOAuthFailed")})});d("#captchaButton").click(function(){z();C.removeClass("hidden");o.HumanVerification=d("#captcha").attr("value");o.HumanVerificationImage=d("#captchaImage").attr("src");I()});q.onChange();if(D.type==="memory")l("statusEnableLocalStorage");else{q(function(F){P=F;Q=false;j(P);Q=true;if(R=U()){d("."+R.slice(1)+"Tab").addClass("ui-tabs-selected ui-state-active");E=d(R);E.removeClass("ui-tabs-hide");T(null,{panel:E[0]});u=d("#tabs");u.tabs({fx:{opacity:"toggle",
duration:100}});u.bind("tabsselect",T);u.removeClass("invisible");B.removeClass("loading");Z()}else l("statusSettings")},function(F,W,S){F.status===503?l("statusServerBusyClose"):l("statusServerError",S)});for(M in G.domains)G.domains.hasOwnProperty(M)&&G.domains[M].setFormData(r);if(x)x=JSON.parse(x);r.title&&d(".title").text(r.title);r.description&&d(".description").text(r.description);if(r.previews&&r.previews.length){x=N(r.previews[0]);n.attr("src",x)}else r.thumbnail&&n.attr("src",N(r.thumbnail));
d(".title").textOverflow(null,true);d(".description").textOverflow(null,true);d(".url").textOverflow(null,true);d(".surl").textOverflow(null,true);d("form.messageForm").submit(function(F){F=F.target;var W,S,$;o={};d.each(F.elements,function(X,Y){X=Y.value.trim();if(Y.getAttribute("placeholder")===X)X="";Y.value=X;if(Y.value)o[Y.name]=Y.value});F=G.domains[o.domain];if(r.shortUrl)o.shorturl=r.shortUrl;else if(F.shorten)o.shorten=true;if(o.to){W=F.getContacts(J);$=[];if(W){F=o.to.split(",");F.forEach(function(X){if((S=
W[X.trim()])&&!S.email)$.push(S.userid?S.userid:S.username)})}if($.length>0)o.to=$.join(", ")}I();return false}).each(function(F,W){h(W)})}})});