#!/usr/bin/env perl

use strict;

# The package version
my $version = shift;
# The list of requirements
my $requires = shift;
# The git revision
my $git = shift;
my ($git_cnt, $git_rev) = split('-', $git);
$git = $git_cnt . '.git.' . $git_rev;

my $prefix = "%{f1_name_prefix}python%{pyver}-";

my %requires;
open (my $f, $requires);
while (my $line = <$f>) {
  chomp $line;
  $line =~ s/^python-//g;
  $line = lc ($line);
  if ($line =~ />=|<=|==/) {
    $line =~ /(.*)(>=|<=|==)(.*)/;
    my ($name, $cmp, $version) = ($1, $2, $3);
    $requires{"$name"} = "$cmp $version";
  }
  else
  {
    $requires{$line} = "";
  }
}

my $requires = <<"EOF";
# Automatically added from setup.py by $0
EOF

# These are os-provided packages
my %included = (
  'httplib2' => 1,
  'nose'     => 1,
);

my %excluded = (
);

foreach my $req (sort keys %requires) {
  next if exists $excluded{$req};
  print STDERR "Inclindng $req\n";
  my $reqs;

  if (exists $included{$req}) {
    $reqs = "python%{pyver}-$req";
  }
  else {
    $reqs = $prefix . $req;
  }
$requires .= <<"EOF";
Requires:      $reqs $requires{$req}
BuildRequires: $reqs $requires{$req}

EOF
}

while (<>) {
    s/%%version%%/$version/g;
    s/%%buildrequires%%//g;
    s/%%requires%%/$requires/g;
    s/%%git%%/.$git/g;
    print;
}
