#!/usr/bin/env perl

use strict;

my $version = shift;
my $requires = shift;

my $prefix = "%{f1_name_prefix}python%{pyver}-";

my %requires;
open (my $f, $requires);
while (my $line = <$f>) {
  chomp $line;
  $line =~ s/^python-//g;
  $line = lc ($line);
  if ($line =~ />=|<=|==/) {
    $line =~ /(.*)(>=|<=|==)(.*)/;
    my ($name, $cmp, $version) = ($1, $2, $3);
    $requires{"$name $cmp $version"} = 1;
  }
  else
  {
    $requires{$line} = 1;
  }
}

my $requires = <<"EOF";
# Automatically added from setup.py by $0
EOF

# These are os-provided packages
my %included = (
  'coverage' => 1,
  'httplib2' => 1,
  'nose'     => 1,
);

my %excluded = (
  'linkoauth' => 1,
   #XXX: Not ready yet
  'pylons'    => 1,
);

foreach my $req (sort keys %requires) {
  next if exists $excluded{$req};

  my $reqs;

  if (exists $included{$req}) {
    $reqs = "python%{pyver}-$req";
  }
  else {
    $reqs = $prefix . $req;
  }
$requires .= <<"EOF";
Requires:      $reqs
BuildRequires: $reqs

EOF
}

while (<>) {
    s/%%version%%/$version/g;
    s/%%buildrequires%%//g;
    s/%%requires%%/$requires/g;
    print;
}
