/*
 blade/func Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/object Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/jig Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/array Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
 blade/url Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/blade for details
*/
define("blade/fn",[],function(){var f=Array.prototype.slice,b=Object.prototype.toString;return{is:function(d){return b.call(d)==="[object Function]"},bind:function(d,a){if(!a)return d;if(typeof a==="string")a=d[a];var c=f.call(arguments,2);return function(){return a.apply(d,c.concat(f.call(arguments,0)))}}}});
define("blade/object",["./fn"],function(f){function b(){}var d={},a=function(c,e,j){c=c||{};var h,l=a.create(c.prototype,e);c=function(n,u,o){return l[u].apply(n,o)};e=a.create(l);a.mixin(e,f.is(j)?j(c):j,true);h=function(){if(!(this instanceof h))throw new Error('blade/object: constructor function called without "new" in front');this.init&&this.init.apply(this,arguments)};h.prototype=e;return h};a.create=function(c,e){b.prototype=c;c=new b;var j,h;b.prototype=null;if(e)for(j=0;h=e[j];j++)a.mixin(c,
h);return c};a.mixin=function(c,e,j){for(var h in e)if(!(h in d)&&(!(h in c)||j))c[h]=e[h]};return a});
define("blade/jig",["require","./object"],function(f,b){function d(g){return E.call(g)==="[object Array]"}function a(g,i,k){i=i;var m,p;for(m=0;i&&(p=g[m]);m++)i=typeof i==="object"&&p in i?i[p]:k&&m===0&&p in k?k[p]:undefined;return i}function c(g){return g?parseInt(g,10):0}function e(g,i,k){var m=/\[([\w0-9\.'":]+)\]/,p=g,w=i,q=true,x,A;if(g===t)return i;if(y.test(g))return c(g);if(g==="")return"";x=g.charAt(0);if(x==="'"||x==="'")return g.substring(1,g.length-1);if((x=g.indexOf("("))!==-1){m=g.lastIndexOf(")");
q=g.substring(0,x);p=k.fn[q];if(!p){o.error("Cannot find function named: "+q+" for "+g);return""}q=g.substring(x+1,m);if(q.indexOf(",")!==-1){q=q.split(",");for(w=q.length-1;w>=0;w--)q[w]=e(q[w],i,k);p=p.apply(null,q)}else p=p(e(q,i,k));if(m<g.length-1){if(g.charAt(m+1)===".")m+=1;return e(g.substring(m+1,g.length),p,k)}else return p}for(;x=m.exec(p);){i=x[1].replace(/['"]/g,"");A=p.substring(0,x.index);p=p.substring(x.index+x[0].length,p.length);if(p.indexOf(".")===0)p=p.substring(1,p.length);w=
a(A.split("."),w,q?k.context:null);q=false;if(!w&&i){o.error('blade/jig: No property "'+i+'" on '+w);return""}if(i.indexOf(":")!==-1){x=i.split(":");i=c(x[0]);w=(x=c(x[1]))?w.slice(i,x):w.slice(i)}else{k.strict&&!(i in w)&&o.error('blade/jig: no property "'+i+'"');w=w[i]}w=w}p=p?a(p.split("."),w,q?k.context:null):w;k.strict&&p===undefined&&o.error('blade/jig: undefined value for property "'+g+'"');return p}function j(g,i){i=i||{};var k=o.cache(g,i);if(k===undefined&&typeof document!=="undefined"){(k=
document.getElementById(g))&&o.parse([k],i);k=o.cache(g,i)}if(k===undefined)throw new Error("blade/jig: no template or node with ID: "+g);return k}function h(g,i){for(var k=[],m=0,p=false,w=0,q,x,A,K,M,J;(q=g.indexOf(i.startToken,m))!==-1;){q!==m&&k.push(g.substring(m,q));m=g.substring(q);if(x=i.endRegExp.exec(m)){m=q+x[0].length;A=g.substring(q+i.startToken.length,q+x[0].length-i.endToken.length).trim();A=D(A);if(v.test(A))throw new Error("blade/jig: end block tags should not be commented: "+A);
q=A.charAt(0);if(q==="]"&&w){p=A.substring(1).trim();if(p==="[")q=">";else{q=p.charAt(0);A=p}}if(q&&!i.propertyRegExp.test(q))A=A.substring(1).trim();else q="_default_";if(p=A.indexOf(i.rawHtmlToken)===0)A=A.substring(i.rawHtmlToken.length,A.length);if(q===H)p=true;A=A.split(i.argSeparator);K=A[A.length-1];M=K.charAt(K.length-1);J=null;if(q==="]"){if(M!=="["){k.templateEnd=m;k.endControl=true}else k.templateEnd=m-x[0].length;return k}else if(M==="["){w||(w=I++);A[A.length-1]=K.substring(0,K.length-
1);J=h(g.substring(m),i);m+=J.templateEnd}if(q==="+")i.templates[A[0]]=J;else if(q!=="/"){if(A.length>1)for(x=A.length-1;x>=0;x--)if(A[x].charAt(A[x].length-1)===","){A[x]+=A[x+1];A.splice(x+1,1)}k.push({action:i.commands[q].action,useRawHtml:p,args:A,controlId:w,children:J})}if(J&&J.endControl)w=0}else{k.push(m);return k}}m!==g.length-1&&k.push(g.substring(m,g.length));return k}function l(g,i){var k,m=g.id;k=i.templates||z;if(k[m])return k[m];i.onBeforeParse&&i.onBeforeParse(g);if(g.nodeName.toUpperCase()===
"SCRIPT"){k=g.text.trim();g.parentNode&&g.parentNode.removeChild(g)}else{L.appendChild(g);g.removeAttribute("id");(k=(g.getAttribute("class")||"").trim())&&g.setAttribute("class",k.replace(N,"$1$3"));k=L.innerHTML.replace(/%7B/g,"{").replace(/%7D/g,"}");L.removeChild(g)}g=o.compile(k,i);o.cache(m,g,i);return g}function n(g,i,k){var m="",p,w,q,x,A;if(typeof g==="string")m=g;else if(d(g))for(p=0;p<g.length;p++){q=g[p].controlId;if(!q||q!==w||!A){x=n(g[p],i,k);m+=x;if(q){w=q;A=x}}}else if(m=g.action(g.args,
i,k,g.children,n)){if(!g.useRawHtml&&!g.children)m=o.htmlEscape(m.toString())}else m="";if(k.attachData)if(s.test(m)){g="id"+G++;m=m.replace(s,'$& data-blade-jig="'+g+'" ');F[g]=i}return m}function u(g){g.fn.jig=function(i,k){k=k||{};var m=this.selector;if(m.charAt(0)!=="#")throw new Error('blade/jig: only ID selectors, like "#something" are allowed with jig()');m=m.substring(1,m.length);(m=(k.templates||z)[m])||(m=l(this[0]));return g(o.render(m,i,k))}}var o,C,E=Object.prototype.toString,D=typeof decodeURIComponent===
"undefined"?function(){}:decodeURIComponent,H="#",r=/[_\[\^\w]/,t="_",s=/<\s*\w+/,y=/^\d+$/,v=/\/(\/)?\s*\]/,z={},B={openCurly:function(){return"{"},closeCurly:function(){return"}"},eq:function(g,i){return g===i},gt:function(g,i){return g>i},gte:function(g,i){return g>=i},lt:function(g,i){return g<i},lte:function(g,i){return g<=i},or:function(g,i){return g||i},and:function(g,i){return g&&i},is:function(g){return!!g},eachProp:function(g){var i,k=[];for(i in g)g.hasOwnProperty(i)&&k.push({prop:i,value:g[i]});
return k.sort(function(m,p){return m.prop>p.prop?1:-1})}},G=1,I=1,F={},L=typeof document!=="undefined"&&document.createElement?document.createElement("div"):null,N=/(\s*)(template)(\s*)/;C={_default_:{doc:"Property reference",action:function(g,i,k,m,p){var w=g[0]?e(g[0],i,k):i,q=g[1]?e(g[1],i,k):undefined,x="";if(g[1]){q=w===q;w=i}else q=w;if(q===false||q===null||q===undefined||d(q)&&!q.length)return"";else if(m)if(d(w))for(g=0;g<w.length;g++)x+=p(m,w[g],k);else{if(typeof w==="boolean")w=i;x=p(m,
w,k)}else x=w;return x}},"!":{doc:"Not",action:function(g,i,k,m,p){var w=e(g[0],i,k),q=g[1]?e(g[1],i,k):undefined;q=g[1]?w===q:w;if(m&&!q)return p(m,i,k);return""}},"#":{doc:"Template reference",action:function(g,i,k,m,p){m=j(g[0],k);i=e(g.length>1?g[1]:t,i,k);return p(m,i,k)}},".":{doc:"Variable declaration",action:function(g,i,k){k.context[g[0]]=e(g[1],i,k);return""}},">":{doc:"Else",action:function(g,i,k,m,p){if(m)return p(m,i,k);return""}}};o=function(g,i,k){if(typeof g==="string")if(g.charAt(0)===
"#"){g=g.substring(1,g.length);g=j(g,k)}else g=o.compile(g,k);return o.render(g,i,k)};o.htmlEscape=function(g){return g.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};o.compile=function(g,i){i=i||{};b.mixin(i,{startToken:"{",endToken:"}",rawHtmlToken:"^",propertyRegExp:r,commands:C,argSeparator:" ",templates:z});i.endRegExp=/[^\r\n]*?}/;I=1;return h(g,i)};o.parse=function(g,i){if(g&&!g.length){i=g;g=null}i=i||{};g=g||document.querySelectorAll('.template, script[type="text/template"]');
var k,m;for(m=g.length-1;m>-1&&(k=g[m]);m--)l(k,i)};o.render=function(g,i,k){var m,p="";k=k||{};b.mixin(k,{templates:z,attachData:false,strict:o.strict});if(k.fn)b.mixin(k.fn,B);else k.fn=B;k.context=k.context||b.create(i);if(d(i)){for(m=0;m<i.length;m++)p+=n(g,i[m],k);return p}return n(g,i,k)};o.strict=false;o.error=function(g){throw g;};o.addFn=function(g){b.mixin(B,g,true)};o.data=function(g,i){if(typeof g!=="string"){g.nodeType||(g=g[0]);g=g.getAttribute("data-blade-jig")}return i!==undefined?
(F[g]=i):F[g]};o.removeData=function(g){delete F[g]};o.getObject=e;o.cache=function(g,i,k){if(typeof i==="string")i=o.compile(i,k);if(!d(i)){k=i;i=undefined}k=k&&k.templates||z;if(i!==undefined)k[g]=i;return k[g]||z[g]};typeof jQuery!=="undefined"&&u(jQuery);return o});
define("friendly",["require","exports","module"],function(){var f={timestamp:function(b){return f.date(new Date(b*1E3))},date:function(b){var d=((new Date).getTime()-b.getTime())/1E3,a=Math.floor(d/86400),c={friendly:b.toLocaleDateString(),additional:b.toLocaleTimeString(),utc:b.toUTCString(),locale:b.toLocaleString()};if(a<0){c.friendly="in the future";return c}else if(isNaN(a)){c.friendly=c.additional="unknown";return c}if(a===0){if(d<60){c.friendly="just now";return c}if(d<150){c.friendly="a minute ago";
return c}if(d<3600){c.friendly=Math.floor(d/60)+" minutes ago";return c}if(d<7200){c.friendly="1 hour ago";return c}if(d<86400){c.friendly=Math.floor(d/3600)+" hours ago";return c}}if(a===1){c.friendly="yesterday";return c}if(a<7){c.friendly=a+" days ago";return c}if(a<8){c.friendly="last week";return c}if(a<31){c.friendly=Math.ceil(a/7)+" weeks ago";return c}if(a<62){c.friendly="a month ago";return c}if(a<365){c.friendly=Math.ceil(a/31)+" months ago";return c}if(a>=365&&a<730){c.additional=b.toLocaleDateString();
c.friendly="a year ago";return c}if(a>=365){c.additional=b.toLocaleDateString();c.friendly=Math.ceil(a/365)+" years ago";return c}return c},name:function(b){b=b.split(" ")[0];if(b.indexOf("@")!==-1)b=b.split("@")[0];b=b.replace(" ","");b=b.replace("'","");return b=b.replace('"',"")}};return f});
define("isoDate",[],function(){var f=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+\-](\d{2}):(\d{2}))|Z)?)?$/,b=function(d,a){var c=f.exec(d);d=null;var e,j;if(c){c.shift();c[1]&&c[1]--;if(c[6])c[6]*=1E3;if(a){a=new Date(a);["FullYear","Month","Date","Hours","Minutes","Seconds","Milliseconds"].map(function(h){return a["get"+h]()}).forEach(function(h,l){c[l]=c[l]||h})}d=new Date(c[0]||1970,c[1]||0,c[2]||1,c[3]||0,c[4]||0,c[5]||0,c[6]||0);if(c[0]<100)d.setFullYear(c[0]||
1970);e=0;j=c[7]&&c[7].charAt(0);if(j!=="Z"){e=(c[8]||0)*60+(Number(c[9])||0);if(j!=="-")e*=-1}if(j)e-=d.getTimezoneOffset();e&&d.setTime(d.getTime()+e*6E4)}return d};b.toIsoString=function(d,a){var c=function(l){return l<10?"0"+l:l},e,j,h;a=a||{};e=[];j=a.zulu?"getUTC":"get";h="";if(a.selector!=="time"){h=d[j+"FullYear"]();h=["0000".substr((h+"").length)+h,c(d[j+"Month"]()+1),c(d[j+"Date"]())].join("-")}e.push(h);if(a.selector!=="date"){h=[c(d[j+"Hours"]()),c(d[j+"Minutes"]()),c(d[j+"Seconds"]())].join(":");
j=d[j+"Milliseconds"]();if(a.milliseconds)h+="."+(j<100?"0":"")+c(j);if(a.zulu)h+="Z";else if(a.selector!=="time"){d=d.getTimezoneOffset();a=Math.abs(d);h+=(d>0?"-":"+")+c(Math.floor(a/60))+":"+c(a%60)}e.push(h)}return e.join("T")};return b});var EXPORTED_SYMBOLS=["hex_md5"],hexcase=0,b64pad="";function hex_md5(f){return rstr2hex(rstr_md5(str2rstr_utf8(f)))}function b64_md5(f){return rstr2b64(rstr_md5(str2rstr_utf8(f)))}function any_md5(f,b){return rstr2any(rstr_md5(str2rstr_utf8(f)),b)}
function hex_hmac_md5(f,b){return rstr2hex(rstr_hmac_md5(str2rstr_utf8(f),str2rstr_utf8(b)))}function b64_hmac_md5(f,b){return rstr2b64(rstr_hmac_md5(str2rstr_utf8(f),str2rstr_utf8(b)))}function any_hmac_md5(f,b,d){return rstr2any(rstr_hmac_md5(str2rstr_utf8(f),str2rstr_utf8(b)),d)}function md5_vm_test(){return hex_md5("abc").toLowerCase()=="900150983cd24fb0d6963f7d28e17f72"}function rstr_md5(f){return binl2rstr(binl_md5(rstr2binl(f),f.length*8))}
function rstr_hmac_md5(f,b){var d=rstr2binl(f);if(d.length>16)d=binl_md5(d,f.length*8);var a=Array(16);f=Array(16);for(var c=0;c<16;c++){a[c]=d[c]^909522486;f[c]=d[c]^1549556828}b=binl_md5(a.concat(rstr2binl(b)),512+b.length*8);return binl2rstr(binl_md5(f.concat(b),640))}function rstr2hex(f){for(var b=hexcase?"0123456789ABCDEF":"0123456789abcdef",d="",a,c=0;c<f.length;c++){a=f.charCodeAt(c);d+=b.charAt(a>>>4&15)+b.charAt(a&15)}return d}
function rstr2b64(f){for(var b="",d=f.length,a=0;a<d;a+=3)for(var c=f.charCodeAt(a)<<16|(a+1<d?f.charCodeAt(a+1)<<8:0)|(a+2<d?f.charCodeAt(a+2):0),e=0;e<4;e++)b+=a*8+e*6>f.length*8?b64pad:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c>>>6*(3-e)&63);return b}
function rstr2any(f,b){var d=b.length,a,c,e,j,h,l=Array(Math.ceil(f.length/2));for(a=0;a<l.length;a++)l[a]=f.charCodeAt(a*2)<<8|f.charCodeAt(a*2+1);var n=Math.ceil(f.length*8/(Math.log(b.length)/Math.log(2)));f=Array(n);for(c=0;c<n;c++){h=Array();for(a=j=0;a<l.length;a++){j=(j<<16)+l[a];e=Math.floor(j/d);j-=e*d;if(h.length>0||e>0)h[h.length]=e}f[c]=j;l=h}d="";for(a=f.length-1;a>=0;a--)d+=b.charAt(f[a]);return d}
function str2rstr_utf8(f){for(var b="",d=-1,a,c;++d<f.length;){a=f.charCodeAt(d);c=d+1<f.length?f.charCodeAt(d+1):0;if(55296<=a&&a<=56319&&56320<=c&&c<=57343){a=65536+((a&1023)<<10)+(c&1023);d++}if(a<=127)b+=String.fromCharCode(a);else if(a<=2047)b+=String.fromCharCode(192|a>>>6&31,128|a&63);else if(a<=65535)b+=String.fromCharCode(224|a>>>12&15,128|a>>>6&63,128|a&63);else if(a<=2097151)b+=String.fromCharCode(240|a>>>18&7,128|a>>>12&63,128|a>>>6&63,128|a&63)}return b}
function str2rstr_utf16le(f){for(var b="",d=0;d<f.length;d++)b+=String.fromCharCode(f.charCodeAt(d)&255,f.charCodeAt(d)>>>8&255);return b}function str2rstr_utf16be(f){for(var b="",d=0;d<f.length;d++)b+=String.fromCharCode(f.charCodeAt(d)>>>8&255,f.charCodeAt(d)&255);return b}function rstr2binl(f){for(var b=Array(f.length>>2),d=0;d<b.length;d++)b[d]=0;for(d=0;d<f.length*8;d+=8)b[d>>5]|=(f.charCodeAt(d/8)&255)<<d%32;return b}
function binl2rstr(f){for(var b="",d=0;d<f.length*32;d+=8)b+=String.fromCharCode(f[d>>5]>>>d%32&255);return b}
function binl_md5(f,b){f[b>>5]|=128<<b%32;f[(b+64>>>9<<4)+14]=b;b=1732584193;for(var d=-271733879,a=-1732584194,c=271733878,e=0;e<f.length;e+=16){var j=b,h=d,l=a,n=c;b=md5_ff(b,d,a,c,f[e+0],7,-680876936);c=md5_ff(c,b,d,a,f[e+1],12,-389564586);a=md5_ff(a,c,b,d,f[e+2],17,606105819);d=md5_ff(d,a,c,b,f[e+3],22,-1044525330);b=md5_ff(b,d,a,c,f[e+4],7,-176418897);c=md5_ff(c,b,d,a,f[e+5],12,1200080426);a=md5_ff(a,c,b,d,f[e+6],17,-1473231341);d=md5_ff(d,a,c,b,f[e+7],22,-45705983);b=md5_ff(b,d,a,c,f[e+8],7,
1770035416);c=md5_ff(c,b,d,a,f[e+9],12,-1958414417);a=md5_ff(a,c,b,d,f[e+10],17,-42063);d=md5_ff(d,a,c,b,f[e+11],22,-1990404162);b=md5_ff(b,d,a,c,f[e+12],7,1804603682);c=md5_ff(c,b,d,a,f[e+13],12,-40341101);a=md5_ff(a,c,b,d,f[e+14],17,-1502002290);d=md5_ff(d,a,c,b,f[e+15],22,1236535329);b=md5_gg(b,d,a,c,f[e+1],5,-165796510);c=md5_gg(c,b,d,a,f[e+6],9,-1069501632);a=md5_gg(a,c,b,d,f[e+11],14,643717713);d=md5_gg(d,a,c,b,f[e+0],20,-373897302);b=md5_gg(b,d,a,c,f[e+5],5,-701558691);c=md5_gg(c,b,d,a,f[e+
10],9,38016083);a=md5_gg(a,c,b,d,f[e+15],14,-660478335);d=md5_gg(d,a,c,b,f[e+4],20,-405537848);b=md5_gg(b,d,a,c,f[e+9],5,568446438);c=md5_gg(c,b,d,a,f[e+14],9,-1019803690);a=md5_gg(a,c,b,d,f[e+3],14,-187363961);d=md5_gg(d,a,c,b,f[e+8],20,1163531501);b=md5_gg(b,d,a,c,f[e+13],5,-1444681467);c=md5_gg(c,b,d,a,f[e+2],9,-51403784);a=md5_gg(a,c,b,d,f[e+7],14,1735328473);d=md5_gg(d,a,c,b,f[e+12],20,-1926607734);b=md5_hh(b,d,a,c,f[e+5],4,-378558);c=md5_hh(c,b,d,a,f[e+8],11,-2022574463);a=md5_hh(a,c,b,d,f[e+
11],16,1839030562);d=md5_hh(d,a,c,b,f[e+14],23,-35309556);b=md5_hh(b,d,a,c,f[e+1],4,-1530992060);c=md5_hh(c,b,d,a,f[e+4],11,1272893353);a=md5_hh(a,c,b,d,f[e+7],16,-155497632);d=md5_hh(d,a,c,b,f[e+10],23,-1094730640);b=md5_hh(b,d,a,c,f[e+13],4,681279174);c=md5_hh(c,b,d,a,f[e+0],11,-358537222);a=md5_hh(a,c,b,d,f[e+3],16,-722521979);d=md5_hh(d,a,c,b,f[e+6],23,76029189);b=md5_hh(b,d,a,c,f[e+9],4,-640364487);c=md5_hh(c,b,d,a,f[e+12],11,-421815835);a=md5_hh(a,c,b,d,f[e+15],16,530742520);d=md5_hh(d,a,c,
b,f[e+2],23,-995338651);b=md5_ii(b,d,a,c,f[e+0],6,-198630844);c=md5_ii(c,b,d,a,f[e+7],10,1126891415);a=md5_ii(a,c,b,d,f[e+14],15,-1416354905);d=md5_ii(d,a,c,b,f[e+5],21,-57434055);b=md5_ii(b,d,a,c,f[e+12],6,1700485571);c=md5_ii(c,b,d,a,f[e+3],10,-1894986606);a=md5_ii(a,c,b,d,f[e+10],15,-1051523);d=md5_ii(d,a,c,b,f[e+1],21,-2054922799);b=md5_ii(b,d,a,c,f[e+8],6,1873313359);c=md5_ii(c,b,d,a,f[e+15],10,-30611744);a=md5_ii(a,c,b,d,f[e+6],15,-1560198380);d=md5_ii(d,a,c,b,f[e+13],21,1309151649);b=md5_ii(b,
d,a,c,f[e+4],6,-145523070);c=md5_ii(c,b,d,a,f[e+11],10,-1120210379);a=md5_ii(a,c,b,d,f[e+2],15,718787259);d=md5_ii(d,a,c,b,f[e+9],21,-343485551);b=safe_add(b,j);d=safe_add(d,h);a=safe_add(a,l);c=safe_add(c,n)}return Array(b,d,a,c)}function md5_cmn(f,b,d,a,c,e){return safe_add(bit_rol(safe_add(safe_add(b,f),safe_add(a,e)),c),d)}function md5_ff(f,b,d,a,c,e,j){return md5_cmn(b&d|~b&a,f,b,c,e,j)}function md5_gg(f,b,d,a,c,e,j){return md5_cmn(b&a|d&~a,f,b,c,e,j)}
function md5_hh(f,b,d,a,c,e,j){return md5_cmn(b^d^a,f,b,c,e,j)}function md5_ii(f,b,d,a,c,e,j){return md5_cmn(d^(b|~a),f,b,c,e,j)}function safe_add(f,b){var d=(f&65535)+(b&65535);return(f>>16)+(b>>16)+(d>>16)<<16|d&65535}function bit_rol(f,b){return f<<b|f>>>32-b}define("md5",function(){});
define("rdapi",["require","jquery","blade/object","blade/jig","friendly","isoDate","md5"],function(f,b,d,a,c,e){function j(r){if(typeof r==="string")r={template:r};else if(r.templateId)r.template=a.cache(r.templateId);if(!("attachData"in r))r.attachData=u.attachTemplateData;if(r.emptyTemplateId)r.emptyTemplate=a.cache(r.emptyTemplateId);return r}function h(){var r=C.exec(document.cookie);return r&&r[1]?r[1]:null}function l(r,t){t.url=H.baseUrl+H.apiPath+r;d.mixin(t,{limit:30,message_limit:3,dataType:"json",
error:function(v,z,B){throw B;}});var s=t.success,y=h();t.success=function(v){v&&v.contacts&&d.mixin(E,v.contacts,true);return s?s.apply(null,arguments):v};if(y)t.beforeSend=function(v){v.setRequestHeader(o,y)};b.ajax(t)}function n(r,t){var s=t.forId?document.getElementById(t.forId):null;if(s)s.innerHTML=r;t.onTemplateDone&&t.onTemplateDone(r);b(document).trigger("rdapi-done",s)}var u,o="X-CSRF",C=/csrf=([^\; ]+)/,E={},D={contact:function(r){return r.iid&&r.domain?E[r.iid]||{}:r},contactPhotoUrl:function(r){var t=
"i/face2.png",s,y;r=D.contact(r);if((s=r.photos)&&s.length){t=s[0].value;s.forEach(function(v){if(v.primary)t=v.value})}else if(r.emails&&r.emails.length){y=r.emails[0].value;r.emails.forEach(function(v){if(v.primary)y=v.value});t="http://www.gravatar.com/avatar/"+hex_md5(y)+"?s=24 &d=identicon"}return t},allMessages:function(r){return[r.topic].concat(r.messages||[])},friendlyDate:function(r){return c.date(e(r)).friendly},htmlBody:function(r){return a.htmlEscape(r).replace(/\n/g,"<br>")}},H={baseUrl:"/",
apiPath:"api/",saveTemplateData:true};a.addFn(D);u=function(r,t){t=j(t);d.mixin(t,{success:function(s){var y=t.template,v=t.emptyTemplate,z="";if(t.forId&&y){if(t.prop)s=a.getObject(t.prop,s,t);if(f.isArray(s))if(s.length)s.forEach(function(B){z+=a(y,B,t)});else z+=a(v,s,t);else z+=a(!s?v:y,s,t);n(z,t)}},error:function(s,y,v){if(t.emptyTemplate){s=a(t.emptyTemplate,v,t);n(s,t)}else throw v;}});l(r,t)};u.contactPhotoUrl=D.contactPhotoUrl;u.attachTemplateData=false;f.ready(function(){var r=[];a.parse({onBeforeParse:function(t){var s=
t.id,y=t.getAttribute("data-rdapi"),v=t.getAttribute("data-rdfor"),z=t.getAttribute("data-rdprop");y&&r.push({templateId:s,api:y,forId:v,prop:z});["data-rdapi","data-rdprop","data-rdfor"].forEach(function(B){t.removeAttribute(B)})}});r.forEach(function(t){u(t.api,t)})});return u});
define("oauth",[],function(){var f,b,d=0;window.addEventListener("message",function(a){if(a=a.data){a=a==="oauth_success"?true:false;b=null;if(f){f(a);f=null}}},false);return function(a,c){if(c)f=c;c=location.protocol+"//"+location.host+"/auth.html";var e=(new Date).getTime();if(b&&b.closed)b=null;if(e>d+4E3){d=e;a=c+"?domain="+a;try{b=window.open(a,"ffshareOAuth","dialog=yes, modal=yes, width=900, height=500, scrollbars=yes");b.focus()}catch(j){window.location=a+"&end_point_success="+encodeURI(window.location)}}else b&&
b.focus()}});define("dispatch",["jquery"],function(){var f=location.protocol+"//"+location.host;return{sub:function(b,d,a,c){a=a||window;c=c||f;var e=function(j){if(j.origin===c||j.origin==="chrome://browser")try{var h=JSON.parse(j.data),l=h.topic;l&&l===b&&d(h.data)}catch(n){}};a.addEventListener("message",e,false);return e},unsub:function(b,d){d=d||window;d.removeEventListener("message",b,false)},pub:function(b,d,a){a=a||window;a.postMessage(JSON.stringify({topic:b,data:d}),f)}}});
define("storage",[],function(){function f(){return b}var b=localStorage,d="localStorage";try{b.tempVar="temp";delete b.tempVar}catch(a){b={};d="memory"}f.type=d;return f});
define("accounts",["storage","dispatch","rdapi"],function(f,b,d){function a(h,l){return j.accounts(h,l)}function c(){location.reload()}var e=f(),j;j={localStorage:{accounts:function(h,l){var n=e.accountCache,u=e.lastAccountCheck||0,o=(new Date).getTime(),C=false;if(!n||o-u>3E3)C=true;n=n?JSON.parse(n):[];h&&h(n);C&&j.fetch(null,l)},fetch:function(h,l){d("account/get",{success:function(n){if(n.error)n=[];e.lastAccountCheck=(new Date).getTime();h&&h(n);var u=e.accountCache,o;u=u?JSON.parse(u):[];if(o=
n.length===u.length)o=!n.some(function(C,E){return C.identifier!==u[E].identifier});if(!o){e.accountCache=JSON.stringify(n);j.changed()}},error:l||function(){}})},changed:function(){e.accountChanged=(new Date).getTime();opener&&!opener.closed&&b.pub("accountsChanged",null,opener);b.pub("accountsChanged")},onChange:function(h){var l=e.accountChanged;window.addEventListener("storage",function(){e.accountChanged!==l&&h()},false);b.sub("accountsChanged",h)}},memory:{accounts:function(h,l){j.fetch(h,l)},
fetch:function(h,l){d("account/get",{success:function(n){if(n.error)n=[];h&&h(n)},error:l||function(){}})},changed:function(){e.accountChanged=(new Date).getTime();opener&&b.pub("accountsChanged",null,opener);b.pub("accountsChanged")},onChange:function(h){b.sub("accountsChanged",h)}}}[f.type];a.fetch=function(h,l){j.fetch(h,l)};a.clear=function(){delete e.accountCache};a.changed=function(){return j.changed()};a.onChange=function(h){return j.onChange(h||c)};return a});
define("dotCompare",[],function(){function f(b,d){b=b||"0";d=d||"0";b=b.split(".");d=d.split(".");var a,c,e,j=b.length>d.length?b.length:d.length;for(a=0;a<j;a++){c=parseInt(b[a]||"0",10);e=parseInt(d[a]||"0",10);if(c>e)return 1;else if(c<e)return-1}return 0}return f});define("blade/array",[],function(){var f=Object.prototype.toString,b=Array.prototype.slice;return{is:function(d){return f.call(d)==="[object Array]"},to:function(){return[].concat(b.call(arguments,0))}}});
define("blade/url",["./array"],function(f){var b=Object.prototype.toString;return{objectToQuery:function(d){var a=encodeURIComponent,c=[],e={},j,h,l,n;for(j in d)if(d.hasOwnProperty(j)){h=d[j];if(h!==e[j]){l=a(j)+"=";if(f.is(h))for(n=0;n<h.length;n++)c.push(l+a(h[n]));else c.push(l+a(h))}}return c.join("&")},queryToObject:function(d){var a={};d=d.split("&");var c=decodeURIComponent,e,j,h;d.forEach(function(l){if(l.length){e=l.split("=");j=c(e.shift());h=c(e.join("="));if(typeof a[j]==="string")a[j]=
[a[j]];if(b.call(a[j])==="[object Array]")a[j].push(h);else a[j]=h}});return a}}});
define("TextCounter",["jquery","blade/object","blade/fn"],function(f,b,d){return b(null,null,{init:function(a,c,e){this.dom=f(a);this.domPlaceholderText=this.dom[0].getAttribute("placeholder")||"";this.countDom=f(c);this.limit=e;this.dom.bind("keyup",d.bind(this,"checkCount"));this.checkCount()},checkCount:function(){var a=this.dom[0].value;if(a.trim()===this.domPlaceholderText)a="";a=this.limit-a.length;a<0?this.countDom.addClass("TextCountOver"):this.countDom.removeClass("TextCountOver");this.countDom.text(a===
this.limit?"":a)},updateLimit:function(a){this.limit=a;this.checkCount()},isOver:function(){return this.dom[0].value.length>this.limit}})});
define("services",["rdapi","blade/object","blade/array","TextCounter"],function(f,b,d){function a(h,l){if(h){this.name=h;this.type=h.replace(/\s/g,"").toLowerCase();this.tabName=this.type+"Tab";this.icon="i/"+this.type+"Icon.png";this.autoCompleteWidget=null;this.features={counter:false,direct:false,subject:false};b.mixin(this,l,true)}}function c(){a.constructor.apply(this,arguments);this.features.direct=true;this.features.subject=true}var e,j;a.constructor=a;a.prototype={clearCache:function(h){delete h[this.type+
"Contacts"]},getContacts:function(h){if(h[this.type+"Contacts"]){var l=JSON.parse(h[this.type+"Contacts"]);if(!e.isFF36&&l&&d.is(l)){l=null;delete h[this.type+"Contacts"]}return l}return null},setContacts:function(h,l){h[this.type+"Contacts"]=JSON.stringify(l)},getFormattedContacts:function(h){var l={};h.forEach(function(n){n.accounts&&n.accounts.length&&n.accounts.forEach(function(u){l[n.displayName]={email:"",userid:u.userid,username:u.username}})});return l},get36FormattedContacts:function(){return null}};
c.prototype=new a;c.constructor=c;c.prototype.validate=function(h){if(!h.to||!h.to.trim())return false;return true};c.prototype.getFormattedContacts=function(h){var l={};h.forEach(function(n){n.emails&&n.emails.length&&n.emails.forEach(function(u){l[n.displayName?n.displayName:u.value]={email:u.value,userid:null,username:null}})});return l};c.prototype.get36FormattedContacts=function(h){var l=[];h.forEach(function(n){n.emails&&n.emails.length&&n.emails.forEach(function(u){l.push({displayName:n.displayName?
n.displayName:u.value,email:u.value})})});return l};e={domains:{"twitter.com":new a("Twitter",{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"public",name:"public"},{type:"direct",name:"direct message",showTo:true,toLabel:"type in name of recipient"}],textLimit:140,shorten:true,serviceUrl:"http://twitter.com",revokeUrl:"http://twitter.com/settings/connections",signOutUrl:"http://twitter.com/logout",accountLink:function(h){return"http://twitter.com/"+h.username}}),"facebook.com":new a("Facebook",
{features:{direct:true,subject:false,counter:true},shareTypes:[{type:"wall",name:"my wall"},{type:"groupWall",name:"group wall",showTo:true,toLabel:"type in the name of the group"}],textLimit:420,serviceUrl:"http://facebook.com",revokeUrl:"http://www.facebook.com/editapps.php?v=allowed",signOutUrl:"http://facebook.com",accountLink:function(h){return"http://www.facebook.com/profile.php?id="+h.userid}}),"google.com":new c("Gmail",{shareTypes:[{type:"direct",name:"direct",showTo:true}],serviceUrl:"https://mail.google.com",
revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(h){return"http://google.com/profiles/"+h.username}}),"googleapps.com":new c("Google Apps",{shareTypes:[{type:"direct",name:"direct",showTo:true}],icon:"i/gmailIcon.png",serviceUrl:"https://mail.google.com",revokeUrl:"https://www.google.com/accounts/IssuedAuthSubTokens",signOutUrl:"http://google.com/preferences",accountLink:function(h){return"http://google.com/profiles/"+
h.username}}),"yahoo.com":new c("Yahoo",{shareTypes:[{type:"direct",name:"direct",showTo:true}],name:"Yahoo!",serviceUrl:"http://mail.yahoo.com",revokeUrl:"https://api.login.yahoo.com/WSLogin/V1/unlink",signOutUrl:"https://login.yahoo.com/config/login?logout=1",accountLink:function(h){return"http://profiles.yahoo.com/"+h.username}}),"linkedin.com":new a("LinkedIn",{isNew:true,features:{direct:true,subject:true,counter:false},shareTypes:[{type:"public",name:"anyone"},{type:"myConnections",name:"connections only",
specialTo:"connections-only"},{type:"contact",name:"send message",showTo:true,toLabel:"type in the name of the contact"}],serviceUrl:"http://linkedin.com",revokeUrl:"http://linkedin.com/settings/connections",signOutUrl:"http://linkedin.com/logout",accountLink:function(h){return"http://linkedin.com/"+h.username},overlays:{"widgets/AccountPanel":"widgets/AccountPanelLinkedIn"}})},domainList:[],svcBaseProto:a.prototype};for(j in e.domains)e.domains.hasOwnProperty(j)&&e.domainList.push(j);return e});
(function(f){function b(c){var e;if(c&&c.constructor==Array&&c.length==3)return c;if(e=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(c))return[parseInt(e[1]),parseInt(e[2]),parseInt(e[3])];if(e=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(c))return[parseFloat(e[1])*2.55,parseFloat(e[2])*2.55,parseFloat(e[3])*2.55];if(e=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(c))return[parseInt(e[1],16),parseInt(e[2],
16),parseInt(e[3],16)];if(e=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(c))return[parseInt(e[1]+e[1],16),parseInt(e[2]+e[2],16),parseInt(e[3]+e[3],16)];return a[f.trim(c).toLowerCase()]}function d(c,e){var j;do{j=f.curCSS(c,e);if(j!=""&&j!="transparent"||f.nodeName(c,"body"))break;e="backgroundColor"}while(c=c.parentNode);return b(j)}f.each(["backgroundColor","borderBottomColor","borderLeftColor","borderRightColor","borderTopColor","color","outlineColor"],function(c,e){f.fx.step[e]=function(j){if(j.state==
0){j.start=d(j.elem,e);j.end=b(j.end)}j.elem.style[e]="rgb("+[Math.max(Math.min(parseInt(j.pos*(j.end[0]-j.start[0])+j.start[0]),255),0),Math.max(Math.min(parseInt(j.pos*(j.end[1]-j.start[1])+j.start[1]),255),0),Math.max(Math.min(parseInt(j.pos*(j.end[2]-j.start[2])+j.start[2]),255),0)].join(",")+")"}});var a={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,
100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,
128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0]}})(jQuery);define("jquery.colorFade",function(){});
(function(f){var b=document.documentElement.style,d="textOverflow"in b||"OTextOverflow"in b,a=function(c,e){var j=0,h=[],l=function(n){var u=0,o;if(!(j>e))for(u=0;u<n.length;u+=1)if(n[u].nodeType===1){o=n[u].cloneNode(false);h[h.length-1].appendChild(o);h.push(o);l(n[u].childNodes);h.pop()}else if(n[u].nodeType===3){if(j+n[u].length<e)h[h.length-1].appendChild(n[u].cloneNode(false));else{o=n[u].cloneNode(false);o.textContent=f.trim(o.textContent.substring(0,e-j));h[h.length-1].appendChild(o)}j+=n[u].length}else h.appendChild(n[u].cloneNode(false))};
h.push(c.cloneNode(false));l(c.childNodes);return f(h.pop().childNodes)};f.extend(f.fn,{textOverflow:function(c,e){var j=c||"&#x2026;";return d?this:this.each(function(){var h=f(this),l=h.clone(),n=h.clone(),u=h.text(),o=h.width(),C=0,E=0,D=u.length,H=function(){if(o!==h.width()){h.replaceWith(n);h=n;n=h.clone();h.textOverflow(c,false);o=h.width()}};h.after(l.hide().css({position:"absolute",width:"auto",overflow:"visible","max-width":"inherit"}));if(l.width()>o){for(;C<D;){E=Math.floor(C+(D-C)/2);
l.empty().append(a(n.get(0),E)).append(j);if(l.width()<o)C=E+1;else D=E}C<u.length&&h.empty().append(a(n.get(0),C-1)).append(j)}l.remove();e&&setInterval(H,200)})}})})(jQuery);define("jquery.textOverflow",function(){});
define("index",["require","jquery","blade/fn","rdapi","oauth","blade/jig","dispatch","storage","accounts","dotCompare","blade/url","services","jquery.colorFade","jquery.textOverflow"],function(f,b,d,a,c,e,j,h,l,n,u,o){function C(s,y){b("div.status").addClass("hidden");b("#"+s).removeClass("hidden");y&&b("#"+s+" .message").text(y)}function E(s,y,v){s.status===503?C("statusServerBusyClose"):C("statusServerError",v)}var D=h(),H=n(D.extensionVersion,"0.7.3")>-1,r=u.queryToObject(location.href.split("#")[1]||
"")||{},t=r.show==="new";e.addFn({domainType:function(s){return(s=o.domains[s.accounts[0].domain])?s.type:""},domainName:function(s){return(s=o.domains[s.accounts[0].domain])?s.name:""},accountName:function(s,y){return y.username&&y.username!==s?s+", "+y.username:s}});l.onChange();l(function(s){b(function(){var y="";s.forEach(function(v){var z=o.domainList.indexOf(v.accounts[0].domain);z!==-1&&o.domainList.splice(z,1);y+=e("#accountTemplate",v)});if(y){b("#existingHeader").removeClass("hidden");b("#existing").append(y).removeClass("hidden")}y=
"";o.domainList.forEach(function(v){o.domains[v].domain=v;y+=e("#addTemplate",o.domains[v])});if(y){b("#availableHeader").removeClass("hidden");b("#available").append(y).removeClass("hidden")}t&&b(function(){b("li.newItem").animate({backgroundColor:"#ffff99"},200).delay(1E3).animate({backgroundColor:"#fafafa"},3E3)})})},E);b(function(){if(t){delete r.show;location.replace(location.href.split("#")[0]+"#"+u.objectToQuery(r))}var s=b("#manage"),y=b("#settings"),v;b(window).bind("load resize",function(){var z=
b(window).height();b("#wrapper").css({"min-height":z})});b("body").delegate(".close","click",function(){window.close()}).delegate(".auth","click",function(z){z=z.target.getAttribute("data-domain");var B=o.domains[z].type;c(z,function(G){if(G){D.lastSelection=B;l.fetch(null,E)}else C("statusOAuthFailed")})}).delegate(".remove","click",function(z){var B=z.target,G=B.getAttribute("data-domain"),I=B.getAttribute("data-username");B=B.getAttribute("data-userid");var F=o.domains[G];a("account/signout",{data:{domain:G,
userid:B,username:I},success:function(){l.fetch(null,E)},error:function(L,N,g){C("statusError",g)}});F.clearCache(D);F.type===D.lastSelection&&delete D.lastSelection;z.preventDefault()}).delegate('#settings [type="checkbox"]',"click",function(z){var B=z.target;z=B.id;B=B.checked;D["prefs."+z]=B;opener&&!opener.closed&&j.pub("prefChanged",{name:z,value:B},opener)});v=(v=D["prefs.use_accel_key"])?JSON.parse(v):false;b("#use_accel_key")[0].checked=v||false;v=(v=D["prefs.bookmarking"])?JSON.parse(v):
false;b("#bookmarking")[0].checked=v||false;b(function(){b(".overflow").textOverflow(null,true)});H&&b("li.settings").removeClass("hidden");b("ul#tabs li").click(function(){b(this).addClass("selected");b(this).siblings().removeClass("selected")});b("ul#tabs li.manage").click(function(){if(s.is(":hidden")){s.fadeIn(200);s.siblings().fadeOut(0)}});b("ul#tabs li.settings").click(function(){if(y.is(":hidden")){y.fadeIn(200);y.siblings().fadeOut(0)}});window.onFeedLoad=function(z,B){var G,I,F;if(B&&B.feed&&
B.feed.entries)for(z=0;F=B.feed.entries[z];z++)if(F.categories&&F.categories.indexOf("Sharing")!==-1){I=F.link;G=F.title;break}if(I){b("#newsFooter .headline").removeClass("invisible");b("#rssLink").attr("href",I).text(G)}};v=document.createElement("script");v.charset="utf-8";v.async=true;v.src="http://www.google.com/uds/Gfeeds?v=1.0&callback=onFeedLoad&context=&output=json&q=http%3A%2F%2Fmozillalabs.com%2Fmessaging%2Ffeed%2F";b("head")[0].appendChild(v)})});